/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\Window.glb --transform -o C:\Users\emanu\next-portfolio\public\Window.jsx --shadows 
Files: .\Window.glb [161.95KB] > C:\Users\emanu\next-portfolio\public\Window-transformed.glb [7.48KB] (95%)
*/

import React, { useState } from "react";
import { Html, Text, useGLTF } from "@react-three/drei";
import { usePointerHover } from "@/lib/usePointerHover";
import ClickBoundary from "@/lib/clickBoundary";
import { a, useSpring } from "@react-spring/three";

const colorBase = "#F1F3F4";

export function Window(props) {
  const { nodes, materials } = useGLTF(
    "/models/aboutCards/Window-transformed.glb",
  );
  const [focus, setFocus] = useState(false);
  const [isAnimating, setIsAnimating] = useState(false);
  const { handlePointerOver, handlePointerOut } = usePointerHover();

  const handleClickInside = () => {
    if (!focus) setFocus(true);
  };
  const handleClickOutside = () => {
    if (focus) setFocus(false);
  };

  const { position, scale, rotation } = useSpring({
    position: focus ? [-17, 8, props.position[2]] : props.position,
    scale: focus ? [2.25, 2.25, 2.25] : [1, 1, 1],
    rotation: focus ? [(-2 * Math.PI) / 9, 0, 0] : [0, 0, 0],
    onStart: () => setIsAnimating(true),
    onRest: () => setIsAnimating(false),
    config: {
      mass: 1,
      tension: 180,
      friction: 22,
    },
  });

  return (
    <ClickBoundary onInside={handleClickInside} onOutside={handleClickOutside}>
      <a.group
        {...props}
        dispose={null}
        position={position}
        scale={scale}
        rotation={rotation}
        onPointerOver={() => {
          if (!focus) handlePointerOver();
        }}
        onPointerOut={handlePointerOut}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Group_17svg.geometry}
          material={materials.PaletteMaterial001}
        />
        <Text
          color={colorBase}
          fontSize={0.3}
          position={[-3.85, 3.2, 0.01]}
          anchorX={"left"}
        >
          {props.file}
        </Text>
        <group
          onPointerOver={handlePointerOver}
          onPointerOut={handlePointerOut}
          onClick={props.reset}
        >
          <mesh position={[5.02, 3.2, 0.001]} rotation={[0, 0, 0]}>
            <planeGeometry args={[1.6, 0.7]} />
            <meshBasicMaterial transparent opacity={0} color={"hotpink"} />
          </mesh>
          <Text
            color={colorBase}
            fontSize={0.3}
            position={[4.45, 3.2, 0.01]}
            anchorX={"left"}
          >
            {"Reset"}
          </Text>
        </group>
        <Html
          position={[-0.02, -0.43, 0.001]}
          distanceFactor={5}
          transform
          occlude={!isAnimating}
          style={{ cursor: focus ? "auto" : "pointer" }}
        >
          {props.children}
        </Html>
      </a.group>
    </ClickBoundary>
  );
}

useGLTF.preload("/models/aboutCards/Window-transformed.glb");
