/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 boat-sail-a.glb --transform --shadows --keepgroups --output C:/Users/emanu/next-portfolio/public/World.jsx 
Files: boat-sail-a.glb [33.29KB] > C:\Users\emanu\next-portfolio\public\boat-sail-a-transformed.glb [5.54KB] (83%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function BoatSail(props) {
  const { nodes, materials } = useGLTF('/models/vehicles/boat-sail-a-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group>
        <mesh castShadow receiveShadow geometry={nodes['boat-sail-a'].geometry} material={materials.colormap} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/vehicles/boat-sail-a-transformed.glb')
