/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\commercial-train.glb --transform -o C:\Users\emanu\next-portfolio\public\commercial-train.jsx --shadows 
Files: .\commercial-train.glb [527.9KB] > C:\Users\emanu\next-portfolio\public\commercial-train-transformed.glb [23.38KB] (96%)
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function CommercialTrain(props) {
  const { nodes, materials } = useGLTF(
    "/models/vehicles/commercial-train-transformed.glb",
  );
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["train-carriage-container-red"].geometry}
        material={materials.colormap}
        position={[0, 0, -2.55]}
      />
    </group>
  );
}

useGLTF.preload("/models/vehicles/commercial-train-transformed.glb");
