/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\Rocket.glb --transform -o C:\Users\emanu\next-portfolio\public\Rocket.jsx --shadows 
Files: .\Rocket.glb [94.85KB] > C:\Users\emanu\next-portfolio\public\Rocket-transformed.glb [4.48KB] (95%)
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function Rocket(props) {
  const { nodes, materials } = useGLTF(
    "/models/vehicles/Rocket-transformed.glb",
  );
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.rocket_topA2.geometry}
        material={materials.PaletteMaterial001}
        position={[0, 3.2, 0]}
      />
    </group>
  );
}

useGLTF.preload("/models/vehicles/Rocket-transformed.glb");
