/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\train.glb --transform -o C:\Users\emanu\next-portfolio\public\train.jsx --shadows 
Files: .\train.glb [721.18KB] > C:\Users\emanu\next-portfolio\public\train-transformed.glb [30.31KB] (96%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Train(props) {
  const { nodes, materials } = useGLTF('/models/vehicles/train-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes['train-electric-bullet-a'].geometry} material={materials.colormap_003} />
    </group>
  )
}

useGLTF.preload('/models/vehicles/train-transformed.glb')
