/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ColorScreenTestPreview.glb --transform -o C:\Users\emanu\next-portfolio\public\ColorScreenTestPreview.jsx --shadows 
Files: ColorScreenTestPreview.glb [7.84MB] > C:\Users\emanu\next-portfolio\public\ColorScreenTestPreview-transformed.glb [407.35KB] (95%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function ColorScreenTestPreview(props) {
  const { nodes, materials } = useGLTF('/models/projectPreviews/ColorScreenTestPreview-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes['rotate-z'].geometry} material={materials.colormap} position={[0, 2.2, 0.2]} scale={4} />
      <mesh castShadow receiveShadow geometry={nodes.Back_Side.geometry} material={materials.PaletteMaterial001} position={[-5.363, 0.086, 0.121]} rotation={[Math.PI / 2, 0, -2.356]} scale={0.014} />
    </group>
  )
}

useGLTF.preload('/models/projectPreviews/ColorScreenTestPreview-transformed.glb')
