/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 CryptoPriceTrackerPreview.glb --transform -o C:\Users\emanu\next-portfolio\public\CryptoPriceTrackerPreview.jsx --shadows 
Files: CryptoPriceTrackerPreview.glb [4.75MB] > C:\Users\emanu\next-portfolio\public\CryptoPriceTrackerPreview-transformed.glb [165.68KB] (97%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function CryptoPriceTrackerPreview(props) {
  const { nodes, materials } = useGLTF('/models/projectPreviews/CryptoPriceTrackerPreview-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes['ride-entrance'].geometry} material={materials.colormap} position={[1.5, 0, 2.125]} rotation={[-Math.PI, 0, -Math.PI]} scale={0.75} />
      <mesh castShadow receiveShadow geometry={nodes['coin-gold'].geometry} material={materials.colormap22} position={[-1.406, 0.356, 1]} rotation={[0, Math.PI / 2, 0]} scale={0.9} />
      <mesh castShadow receiveShadow geometry={nodes.MeshInstance3D2.geometry} material={materials.Material} position={[-4.5, 6.5, 2.5]} />
      <mesh castShadow receiveShadow geometry={nodes.MeshInstance3D3.geometry} material={materials.Material2} position={[-6.375, 0.5, 2.5]} />
      <mesh castShadow receiveShadow geometry={nodes.trending_up_24dp_E3E3E3_svg.geometry} material={materials.Material} position={[4.5, 5, -3.5]} rotation={[-Math.PI, 0, -Math.PI]} scale={20} />
      <mesh castShadow receiveShadow geometry={nodes.trending_up_24dp_E3E3E3_svg2.geometry} material={materials.Material2} position={[-2.5, 5, -3.5]} rotation={[-Math.PI, 0, -Math.PI]} scale={20} />
    </group>
  )
}

useGLTF.preload('/models/projectPreviews/CryptoPriceTrackerPreview-transformed.glb')
