/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 EventToolPreview.glb --transform -o C:\Users\emanu\next-portfolio\public\EventToolPreview.jsx --shadows 
Files: EventToolPreview.glb [216.2KB] > C:\Users\emanu\next-portfolio\public\EventToolPreview-transformed.glb [16.16KB] (93%)
*/

import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function EventToolPreview(props) {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF('/EventToolPreview-transformed.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group>
        <mesh name="claw-machine" castShadow receiveShadow geometry={nodes['claw-machine'].geometry} material={materials.colormap} position={[0, 0, -1]} scale={6}>
          <mesh name="rotate-y" castShadow receiveShadow geometry={nodes['rotate-y'].geometry} material={materials.colormap} position={[0, 0.65, 0]} />
        </mesh>
        <mesh name="(_ignore)" castShadow receiveShadow geometry={nodes['(_ignore)'].geometry} material={materials.glass} position={[0, 1.5, -1]} scale={6} />
      </group>
    </group>
  )
}

useGLTF.preload('/EventToolPreview-transformed.glb')
