/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 FlynetPreview.glb --transform -o C:\Users\emanu\next-portfolio\public\FlynetPreview.jsx --shadows 
Files: FlynetPreview.glb [718.59KB] > C:\Users\emanu\next-portfolio\public\FlynetPreview-transformed.glb [57.4KB] (92%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function FlynetPreview(props) {
  const { nodes, materials } = useGLTF('/FlynetPreview-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.landingpad_large.geometry} material={materials.spacebits_texture} position={[0, 0, 0.6]} scale={2} />
      <group position={[0, 2, 0.6]} rotation={[2.65, -0.991, 2.72]} scale={2}>
        <mesh castShadow receiveShadow geometry={nodes.mesh_1.geometry} material={materials.metal} />
        <mesh castShadow receiveShadow geometry={nodes.mesh_1_1.geometry} material={materials.metalRed} />
        <mesh castShadow receiveShadow geometry={nodes.mesh_1_2.geometry} material={materials.metalDark} />
        <mesh castShadow receiveShadow geometry={nodes.mesh_1_3.geometry} material={materials.dark} />
      </group>
      <mesh castShadow receiveShadow geometry={nodes['computer-screen'].geometry} material={materials.colormap} position={[1.8, 0, 2.5]} rotation={[0, Math.PI / 4, 0]} scale={1.5} />
    </group>
  )
}

useGLTF.preload('/FlynetPreview-transformed.glb')
