/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 HotelMeanoPreview.glb --transform -o C:\Users\emanu\next-portfolio\public\HotelMeanoPreview.jsx --shadows 
Files: HotelMeanoPreview.glb [1.12MB] > C:\Users\emanu\next-portfolio\public\HotelMeanoPreview-transformed.glb [60.42KB] (95%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function HotelMeanoPreview(props) {
  const { nodes, materials } = useGLTF('/models/projectPreviews/HotelMeanoPreview-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes['building-j'].geometry} material={materials.colormap} position={[2.5, 0, 1.5]} scale={4} />
      <mesh castShadow receiveShadow geometry={nodes.lantern.geometry} material={materials.colormap2} position={[-7.5, 0, 1.5]} />
      <mesh castShadow receiveShadow geometry={nodes['wheel-front-right'].geometry} material={materials.colormap5} position={[-7.07, 0.225, -0.725]} rotation={[0, -Math.PI / 2, 0]} scale={0.75} />
      <mesh castShadow receiveShadow geometry={nodes['stall-drinks'].geometry} material={materials.colormap7} position={[-3.5, 0, -1.5]} rotation={[-Math.PI, 0, -Math.PI]} scale={1.5} />
    </group>
  )
}

useGLTF.preload('/models/projectPreviews/HotelMeanoPreview-transformed.glb')
