/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 MetaEmpirePreview.glb --transform -o C:\Users\emanu\next-portfolio\public\MetaEmpirePreview.jsx --shadows 
Files: MetaEmpirePreview.glb [193.01KB] > C:\Users\emanu\next-portfolio\public\MetaEmpirePreview-transformed.glb [10.45KB] (95%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function MetaEmpirePreview(props) {
  const { nodes, materials } = useGLTF('/models/projectPreviews/MetaEmpirePreview-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.statue.geometry} material={materials.colormap} position={[0, 0, 2]} scale={5} />
    </group>
  )
}

useGLTF.preload('/models/projectPreviews/MetaEmpirePreview-transformed.glb')
