/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 PlanItPreview.glb --transform -o C:\Users\emanu\next-portfolio\public\PlanItPreview.jsx --shadows 
Files: PlanItPreview.glb [2.25MB] > C:\Users\emanu\next-portfolio\public\PlanItPreview-transformed.glb [79.13KB] (96%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function PlanItPreview(props) {
  const { nodes, materials } = useGLTF('/models/projectPreviews/PlanItPreview-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[7.125, 0, -2.625]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={7.5}>
        <mesh castShadow receiveShadow geometry={nodes.mesh_0.geometry} material={materials.StoneDark} />
        <mesh castShadow receiveShadow geometry={nodes.mesh_0_1.geometry} material={materials.White} />
        <mesh castShadow receiveShadow geometry={nodes.mesh_0_2.geometry} material={materials.Metal} />
      </group>
      <mesh castShadow receiveShadow geometry={nodes.MeshInstance3D.geometry} material={nodes.MeshInstance3D.material} position={[7.125, 0.54, -1.5]} rotation={[Math.PI / 2, 0, 0]} scale={1.5} />
      <mesh castShadow receiveShadow geometry={nodes['robot-arm-b'].geometry} material={materials.colormap} position={[2, 0, 3.25]} rotation={[0, Math.PI / 3, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.MeshInstance3D7.geometry} material={nodes.MeshInstance3D7.material} position={[6.5, 0.01, 0.5]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.Pallet_Small.geometry} material={materials.prototype_texture} position={[-7.25, 0, -2.75]} />
    </group>
  )
}

useGLTF.preload('/models/projectPreviews/PlanItPreview-transformed.glb')
