/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 PortfolioPreview.glb --transform -o C:\Users\emanu\next-portfolio\public\PortfolioPreview.jsx --shadows 
Files: PortfolioPreview.glb [14.38MB] > C:\Users\emanu\next-portfolio\public\PortfolioPreview-transformed.glb [1.06MB] (93%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function PortfolioPreview(props) {
  const { nodes, materials } = useGLTF('/PortfolioPreview-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.table_low.geometry} material={materials.furniture_texture} position={[0, 0, 0.375]} scale={[7, 5, 5]} />
      <mesh castShadow receiveShadow geometry={nodes['square_forest_detail_(-3,_0,_-12)'].geometry} material={materials.PaletteMaterial001} position={[-7.59, 2.5, 1.4]} scale={0.33} />
      <mesh castShadow receiveShadow geometry={nodes['square_forestToPlain_detail_(2,_0,_-6)'].geometry} material={materials.Material_7_001} position={[-3.63, 2.5, -1.9]} scale={0.33} />
      <mesh castShadow receiveShadow geometry={nodes['square_plainToRock_detail_(2,_0,_-3)'].geometry} material={materials.Material_8_001} position={[-1.65, 2.5, -1.9]} scale={0.33} />
      <mesh castShadow receiveShadow geometry={nodes['square_rockToSand_detail_(2,_0,_-1)'].geometry} material={materials.Material_9_001} position={[-0.33, 2.5, -1.9]} scale={0.33} />
      <mesh castShadow receiveShadow geometry={nodes['ship-ocean-liner-small'].geometry} material={materials.colormap} position={[4.702, 2.748, 1.194]} rotation={[-Math.PI, Math.PI / 4, -Math.PI]} scale={0.083} />
      <mesh castShadow receiveShadow geometry={nodes['train-electric-bullet-a'].geometry} material={materials.colormap_003} position={[7.136, 2.83, 1.4]} scale={0.165} />
      <mesh castShadow receiveShadow geometry={nodes.Rock_1_J_Color1.geometry} material={materials.forest} position={[-7.342, 2.789, -1.488]} rotation={[0, Math.PI / 2, 0]} scale={0.33} />
      <mesh castShadow receiveShadow geometry={nodes.building_barracks_blue.geometry} material={materials.hexagons_medieval} position={[-6.806, 2.789, -0.25]} rotation={[0, Math.PI / 2, 0]} scale={0.33} />
      <mesh castShadow receiveShadow geometry={nodes.body.geometry} material={materials.colormap3} position={[-5.613, 2.855, 1.073]} rotation={[-Math.PI, Math.PI / 4, -Math.PI]} scale={0.165} />
      <mesh castShadow receiveShadow geometry={nodes.Farm_House_Barn_01.geometry} material={materials.Color_Palette_01} position={[-3.094, 2.83, 1.029]} rotation={[-Math.PI, Math.PI / 3, -Math.PI]} scale={0.066} />
      <mesh castShadow receiveShadow geometry={nodes.RocksPackCube101.geometry} material={materials.arena_atlas} position={[-1.114, 2.83, -0.044]} rotation={[0, Math.PI / 2, 0]} scale={0.066} />
      <mesh castShadow receiveShadow geometry={nodes['palm-detailed-straight'].geometry} material={materials.colormap4} position={[0.495, 2.83, -1.529]} rotation={[0, Math.PI / 2, 0]} scale={0.066} />
      <mesh castShadow receiveShadow geometry={nodes['tool-pickaxe'].geometry} material={materials.colormap17} position={[0.429, 2.83, 0.641]} rotation={[-2.724, 0.6, 2.997]} scale={0.33} />
      <mesh castShadow receiveShadow geometry={nodes.ladder.geometry} material={materials.colormap18} position={[0.412, 2.823, 0.367]} rotation={[-2.88, 0, -Math.PI]} scale={0.152} />
      <mesh castShadow receiveShadow geometry={nodes.road.geometry} material={materials.colormap20} position={[-2.145, 2.83, -0.745]} rotation={[0, Math.PI / 2, 0]} scale={0.132} />
      <mesh castShadow receiveShadow geometry={nodes['building-skyscraper-a'].geometry} material={materials.colormap25} position={[7.425, 2.83, -1.157]} rotation={[0, Math.PI / 2, 0]} scale={0.33} />
      <mesh castShadow receiveShadow geometry={nodes.cactus_small_B.geometry} material={materials.furniture_texture2} position={[-7, 2.5, 3]} scale={2} />
      <mesh castShadow receiveShadow geometry={nodes.Can_B.geometry} material={materials.prototype_texture} position={[4.375, 2.5, 3.375]} scale={2} />
    </group>
  )
}

useGLTF.preload('/PortfolioPreview-transformed.glb')
