/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 PortfolioPreview.glb --transform -o C:\Users\emanu\next-portfolio\public\PortfolioPreview.jsx --shadows 
Files: PortfolioPreview.glb [15.92MB] > C:\Users\emanu\next-portfolio\public\PortfolioPreview-transformed.glb [1.17MB] (93%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function PortfolioPreview(props) {
  const { nodes, materials } = useGLTF('/models/projectPreviews/PortfolioPreview-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes['square_forest_detail_(-3,_0,_-12)'].geometry} material={materials.PaletteMaterial001} position={[-7.59, 3.75, 1.65]} scale={0.33} />
      <mesh castShadow receiveShadow geometry={nodes['square_forestToPlain_detail_(2,_0,_-6)'].geometry} material={materials.Material_7_001} position={[-3.63, 3.75, -1.65]} scale={0.33} />
      <mesh castShadow receiveShadow geometry={nodes['square_plainToRock_detail_(2,_0,_-3)'].geometry} material={materials.Material_8_001} position={[-1.65, 3.75, -1.65]} scale={0.33} />
      <mesh castShadow receiveShadow geometry={nodes['square_rockToSand_detail_(2,_0,_-1)'].geometry} material={materials.Material_9_001} position={[-0.33, 3.75, -1.65]} scale={0.33} />
      <mesh castShadow receiveShadow geometry={nodes['ship-ocean-liner-small'].geometry} material={materials.colormap} position={[4.702, 3.998, 1.444]} rotation={[-Math.PI, Math.PI / 4, -Math.PI]} scale={0.083} />
      <mesh castShadow receiveShadow geometry={nodes['train-electric-bullet-a'].geometry} material={materials.colormap_003} position={[7.136, 4.08, 1.65]} scale={0.165} />
      <mesh castShadow receiveShadow geometry={nodes.Rock_1_J_Color1.geometry} material={materials.forest} position={[-7.342, 4.039, -1.238]} rotation={[0, Math.PI / 2, 0]} scale={0.33} />
      <mesh castShadow receiveShadow geometry={nodes.building_barracks_blue.geometry} material={materials.hexagons_medieval} position={[-6.806, 4.039, 0]} rotation={[0, Math.PI / 2, 0]} scale={0.33} />
      <mesh castShadow receiveShadow geometry={nodes.body.geometry} material={materials.colormap3} position={[-5.613, 4.105, 1.323]} rotation={[-Math.PI, Math.PI / 4, -Math.PI]} scale={0.165} />
      <mesh castShadow receiveShadow geometry={nodes.Farm_House_Barn_01.geometry} material={materials.Color_Palette_01} position={[-3.094, 4.08, 1.279]} rotation={[-Math.PI, Math.PI / 3, -Math.PI]} scale={0.066} />
      <mesh castShadow receiveShadow geometry={nodes.RocksPackCube101.geometry} material={materials.arena_atlas} position={[-1.114, 4.08, 0.206]} rotation={[0, Math.PI / 2, 0]} scale={0.066} />
      <mesh castShadow receiveShadow geometry={nodes['palm-detailed-straight'].geometry} material={materials.colormap4} position={[0.495, 4.08, -1.279]} rotation={[0, Math.PI / 2, 0]} scale={0.066} />
      <mesh castShadow receiveShadow geometry={nodes['tool-pickaxe'].geometry} material={materials.colormap17} position={[0.429, 4.08, 0.891]} rotation={[-2.724, 0.6, 2.997]} scale={0.33} />
      <mesh castShadow receiveShadow geometry={nodes.ladder.geometry} material={materials.colormap18} position={[0.412, 4.073, 0.617]} rotation={[-2.88, 0, -Math.PI]} scale={0.152} />
      <mesh castShadow receiveShadow geometry={nodes.road.geometry} material={materials.colormap20} position={[-2.145, 4.08, -0.495]} rotation={[0, Math.PI / 2, 0]} scale={0.132} />
      <mesh castShadow receiveShadow geometry={nodes['building-skyscraper-a'].geometry} material={materials.colormap25} position={[7.425, 4.08, -0.907]} rotation={[0, Math.PI / 2, 0]} scale={0.33} />
      <mesh castShadow receiveShadow geometry={nodes.cactus_small_B.geometry} material={materials.furniture_texture} position={[-6.875, 3.75, 3.25]} scale={2} />
      <mesh castShadow receiveShadow geometry={nodes.Can_B.geometry} material={materials.prototype_texture} position={[5.125, 3.75, 2.75]} scale={2} />
      <mesh castShadow receiveShadow geometry={nodes.food_burger.geometry} material={materials.restaurant} position={[4.125, 3.75, 3.375]} />
      <mesh castShadow receiveShadow geometry={nodes.Righe.geometry} material={materials.PaletteMaterial002} position={[-1.737, 4.096, 2.719]} rotation={[-1.118, 0.215, -0.164]} scale={[0.853, 0.696, 0.853]} />
    </group>
  )
}

useGLTF.preload('/models/projectPreviews/PortfolioPreview-transformed.glb')
