/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 SmartParkingAppPreview.glb --transform -o C:\Users\emanu\next-portfolio\public\SmartParkingAppPreview.jsx --shadows 
Files: SmartParkingAppPreview.glb [3.56MB] > C:\Users\emanu\next-portfolio\public\SmartParkingAppPreview-transformed.glb [149.16KB] (96%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function SmartParkingAppPreview(props) {
  const { nodes, materials } = useGLTF('/SmartParkingAppPreview-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes['brick-wall'].geometry} material={materials.colormap} position={[-7, 0, 3.5]} rotation={[-Math.PI, 0, -Math.PI]} />
      <mesh castShadow receiveShadow geometry={nodes['wheel-front-left'].geometry} material={materials.colormap4} position={[-3.275, 0.225, -1.605]} scale={0.75} />
    </group>
  )
}

useGLTF.preload('/SmartParkingAppPreview-transformed.glb')
