/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 SnipingBotPreview.glb --transform -o C:\Users\emanu\next-portfolio\public\SnipingBotPreview.jsx --shadows 
Files: SnipingBotPreview.glb [1.65MB] > C:\Users\emanu\next-portfolio\public\SnipingBotPreview-transformed.glb [144.06KB] (91%)
*/

import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function SnipingBotPreview(props) {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF('/models/projectPreviews/SnipingBotPreview-transformed.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group>
        <group name="ticket-machine" position={[6.3, 0, 1.6]} rotation={[0, -Math.PI / 4, 0]} scale={5}>
          <mesh name="rotate-y" castShadow receiveShadow geometry={nodes['rotate-y'].geometry} material={materials.colormap} position={[0, 0.725, 0.013]} />
        </group>
        <mesh name="gambling-machine" castShadow receiveShadow geometry={nodes['gambling-machine'].geometry} material={materials.colormap} position={[0.1, 0, 0]} scale={6} />
        <mesh name="Gold_Bar" castShadow receiveShadow geometry={nodes.Gold_Bar.geometry} material={materials.resource} position={[5.6, 0, 3.1]} rotation={[0, 0.262, 0]} scale={1.5} />
        <mesh name="coin_stack_large" castShadow receiveShadow geometry={nodes.coin_stack_large.geometry} material={materials.texture} position={[-1.9, 0, 0.6]} scale={1.5} />
        <group name="lootSackA" position={[7.3, 0, 2.7]} rotation={[Math.PI, -Math.PI / 3, Math.PI]}>
          <mesh name="mesh_4" castShadow receiveShadow geometry={nodes.mesh_4.geometry} material={materials.Beige} />
          <mesh name="mesh_4_1" castShadow receiveShadow geometry={nodes.mesh_4_1.geometry} material={materials.BrownDark} />
        </group>
        <mesh name="crate-item" castShadow receiveShadow geometry={nodes['crate-item'].geometry} material={materials.colormap3} position={[-4.708, 0, -0.514]} rotation={[0, -0.262, 0]} scale={2} />
        <mesh name="trophy" castShadow receiveShadow geometry={nodes.trophy.geometry} material={materials.colormap4} position={[6.6, 0, 3.3]} rotation={[-0.262, 0, 0]} scale={1.5} />
        <mesh name="Collectible_Diamond_01" castShadow receiveShadow geometry={nodes.Collectible_Diamond_01.geometry} material={materials.Color_Palette_01} position={[-1.9, 1.6, -1.1]} rotation={[-0.857, -0.361, -0.388]} scale={0.75} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/projectPreviews/SnipingBotPreview-transformed.glb')
