/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 SpacePiratesPreview.glb --transform -o C:\Users\emanu\next-portfolio\public\SpacePiratesPreview.jsx --shadows 
Files: SpacePiratesPreview.glb [341.39KB] > C:\Users\emanu\next-portfolio\public\SpacePiratesPreview-transformed.glb [33.64KB] (90%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function SpacePiratesPreview(props) {
  const { nodes, materials } = useGLTF('/SpacePiratesPreview-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes['ship-pirate-medium'].geometry} material={materials.colormap} position={[2.62, 3, 3.375]} rotation={[-0.454, Math.PI / 3, 0.401]} scale={0.75} />
      <mesh castShadow receiveShadow geometry={nodes.meteor_detailed.geometry} material={materials.PaletteMaterial001} position={[-4.6, 1.8, 3.9]} rotation={[-0.172, 0.307, 0.356]} scale={5} />
      <mesh castShadow receiveShadow geometry={nodes.chest_uncommon.geometry} material={materials.PaletteMaterial002} position={[-5.812, 5.237, 3.692]} rotation={[-0.572, 0.947, 0.605]} scale={0.5} />
      <mesh castShadow receiveShadow geometry={nodes.skull.geometry} material={materials.HalloweenBits} position={[6.631, 5.186, -1.015]} rotation={[-0.467, -0.553, -0.067]} scale={0.45} />
    </group>
  )
}

useGLTF.preload('/SpacePiratesPreview-transformed.glb')
