/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 WalletTrackerPreview.glb --transform -o C:\Users\emanu\next-portfolio\public\WalletTrackerPreview.jsx --shadows 
Files: WalletTrackerPreview.glb [1.1MB] > C:\Users\emanu\next-portfolio\public\WalletTrackerPreview-transformed.glb [58.63KB] (95%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function WalletTrackerPreview(props) {
  const { nodes, materials } = useGLTF('/WalletTrackerPreview-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.MeshInstance3D3.geometry} material={materials.PaletteMaterial001} position={[-2.865, 2.784, -1.273]} scale={3} />
      <mesh castShadow receiveShadow geometry={nodes['avalanche-avax-logo_svg'].geometry} material={materials.PaletteMaterial001} position={[-2.865, 2.784, -0.403]} scale={0.33} />
      <mesh castShadow receiveShadow geometry={nodes.Lighthouse2.geometry} material={materials.PaletteMaterial002} rotation={[Math.PI / 2, 0, -Math.PI]} scale={[-86.169, 86.169, 48.018]} />
    </group>
  )
}

useGLTF.preload('/WalletTrackerPreview-transformed.glb')
