/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\Wolf.glb --transform -o C:\Users\emanu\next-portfolio\public\Wolf.jsx --shadows -f png 
Files: .\Wolf.glb [263.7KB] > C:\Users\emanu\next-portfolio\public\Wolf-transformed.glb [67.63KB] (74%)
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('/Wolf-transformed.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="AnimalArmature">
          <primitive object={nodes.All} />
          <primitive object={nodes.Root} />
        </group>
        <skinnedMesh name="Wolf" geometry={nodes.Wolf.geometry} material={materials.Atlas} skeleton={nodes.Wolf.skeleton} />
      </group>
    </group>
  )
}

useGLTF.preload('/Wolf-transformed.glb')
