import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={"min-h-full w-full flex flex-col items-center antialiased"}
      >
        {children}
      </body>
    </html>
  );
}
