/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\model.gltf --transform -o C:\Users\emanu\next-portfolio\public\model.jsx --shadows 
Files: .\model.gltf [34.97KB] > C:\Users\emanu\next-portfolio\public\model-transformed.glb [8.22KB] (76%)
*/

import React from "react";
import { useGraph } from "@react-three/fiber";
import { PivotControls, useGLTF } from "@react-three/drei";
import { SkeletonUtils } from "three-stdlib";

export function Model(props) {
  const { scene } = useGLTF(
    "/models/aboutCards/minecraft/model-transformed.glb"
  );
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);
  const { nodes } = useGraph(clone);
  return (
    <group
      {...props}
      dispose={null}
      rotation={[0, -2, 0]}
      scale={[1.25, 1.25, 1.25]}
      position={[-1, 2, 3]}
    >
      <primitive
        object={nodes.Waist_1}
        position={[0, 0.75, 0]}
        castShadow
        receiveShadow
      >
        <PivotControls
          lineWidth={1.75}
          disableAxes
          disableScaling
          disableSliders
          offset={[0, 1, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          annotations
        >
          <primitive
            object={nodes.Head}
            position={[0, 0.75, 0]}
            rotation={[-0.035, 0, 0]}
          />
        </PivotControls>
        <primitive
          object={nodes.Body}
          position={[0, 0.75, 0]}
          castShadow
          receiveShadow
        />
        <primitive
          object={nodes.Right_Arm}
          position={[0.313, 0.625, 0]}
          rotation={[-0.611, 0, 0]}
          castShadow
          receiveShadow
        />
        <primitive
          object={nodes.Left_Arm}
          position={[-0.313, 0.625, 0]}
          rotation={[0.611, 0, 0]}
          castShadow
          receiveShadow
        />
      </primitive>
      <primitive
        object={nodes.Right_Leg_1}
        position={[0.119, 0.75, 0]}
        rotation={[1.466, 0.058, 0.03]}
        castShadow
        receiveShadow
      />
      <primitive
        object={nodes.Left_Leg_1}
        position={[-0.119, 0.75, 0]}
        rotation={[-1.466, 0.058, -0.03]}
        castShadow
        receiveShadow
      />
      <skinnedMesh
        geometry={nodes.Waist.geometry}
        material={nodes.Waist.material}
        skeleton={nodes.Waist.skeleton}
        position={[0, 0.75, 0]}
        castShadow
        receiveShadow
      />
      <skinnedMesh
        geometry={nodes.Right_Leg.geometry}
        material={nodes.Right_Leg.material}
        skeleton={nodes.Right_Leg.skeleton}
        position={[0.119, 0.75, 0]}
        rotation={[0.733, 0.023, 0.026]}
        castShadow
        receiveShadow
      />
      <skinnedMesh
        geometry={nodes.Left_Leg.geometry}
        material={nodes.Left_Leg.material}
        skeleton={nodes.Left_Leg.skeleton}
        position={[-0.119, 0.75, 0]}
        rotation={[-0.733, 0.023, -0.026]}
        castShadow
        receiveShadow
      />
    </group>
  );
}

useGLTF.preload("/models/aboutCards/minecraft/model-transformed.glb");
