/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\Tree.glb --transform -o C:\Users\emanu\next-portfolio\public\Tree.jsx --shadows 
Files: .\Tree.glb [83.66KB] > C:\Users\emanu\next-portfolio\public\Tree-transformed.glb [7.36KB] (91%)
*/

import React from "react";
import { useGLTF, Wireframe } from "@react-three/drei";

const wireFrameOptions = {
  fillMix: 0.3,
  dash: false,
  squeeze: false,
  thickness: 0.1,
  fill: "#000000",
  stroke: "#00FFFF",
  colorBackfaces: false,
};

export function Tree(props) {
  const { nodes, materials } = useGLTF(
    "/models/aboutCards/minecraft/Tree-transformed.glb"
  );
  return (
    <group {...props} dispose={null}>
      <group position={[6, 2, -3]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Portfolio__102_-61_34_to_106_319_38_1"].geometry}
          material={materials.oak_log}
        >
          <Wireframe {...wireFrameOptions} />
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Portfolio__102_-61_34_to_106_319_38_2"].geometry}
          material={materials.oak_log_top}
        >
          <Wireframe {...wireFrameOptions} />
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Portfolio__102_-61_34_to_106_319_38_3"].geometry}
          material={materials.oak_leaves}
        >
          <Wireframe {...wireFrameOptions} />
        </mesh>
      </group>
    </group>
  );
}

useGLTF.preload("/models/aboutCards/minecraft/Tree-transformed.glb");
