/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\ambulance.glb --transform -o C:\Users\emanu\next-portfolio\public\ambulance.jsx --shadows 
Files: .\ambulance.glb [233.62KB] > C:\Users\emanu\next-portfolio\public\ambulance-transformed.glb [15.78KB] (93%)
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function Ambulance(props) {
  const { nodes, materials } = useGLTF(
    "/models/vehicles/city/ambulance-transformed.glb",
  );
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.body.geometry}
        material={materials.colormap}
        position={[0, 0.2, -0.025]}
      />
    </group>
  );
}

useGLTF.preload("/models/vehicles/city/ambulance-transformed.glb");
