/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\delivery.glb --transform -o C:\Users\emanu\next-portfolio\public\delivery.jsx --shadows 
Files: .\delivery.glb [240.3KB] > C:\Users\emanu\next-portfolio\public\delivery-transformed.glb [14.27KB] (94%)
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function Delivery(props) {
  const { nodes, materials } = useGLTF(
    "/models/vehicles/city/delivery-transformed.glb",
  );
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.body.geometry}
        material={materials.colormap}
        position={[0, 0.15, -0.025]}
      />
    </group>
  );
}

useGLTF.preload("/models/vehicles/city/delivery-transformed.glb");
