/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\firetruck.glb --transform -o C:\Users\emanu\next-portfolio\public\firetruck.jsx --shadows 
Files: .\firetruck.glb [232.47KB] > C:\Users\emanu\next-portfolio\public\firetruck-transformed.glb [15.32KB] (93%)
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function Firetruck(props) {
  const { nodes, materials } = useGLTF(
    "/models/vehicles/city/firetruck-transformed.glb",
  );
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.body.geometry}
        material={materials.colormap}
        position={[0, 0.2, 0]}
      />
    </group>
  );
}

useGLTF.preload("/models/vehicles/city/firetruck-transformed.glb");
