/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\garbage-truck.glb --transform -o C:\Users\emanu\next-portfolio\public\garbage-truck.jsx --shadows 
Files: .\garbage-truck.glb [268.24KB] > C:\Users\emanu\next-portfolio\public\garbage-truck-transformed.glb [17.08KB] (94%)
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function GarbageTruck(props) {
  const { nodes, materials } = useGLTF(
    "/models/vehicles/city/garbage-truck-transformed.glb",
  );
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.arm.geometry}
        material={materials.colormap}
        position={[0, 0.482, 0.325]}
      />
    </group>
  );
}

useGLTF.preload("/models/vehicles/city/garbage-truck-transformed.glb");
