/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\hatchback-sports.glb --transform -o C:\Users\emanu\next-portfolio\public\hatchback-sports.jsx --shadows 
Files: .\hatchback-sports.glb [197.82KB] > C:\Users\emanu\next-portfolio\public\hatchback-sports-transformed.glb [13.27KB] (93%)
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function HatchbackSports(props) {
  const { nodes, materials } = useGLTF(
    "/models/vehicles/city/hatchback-sports-transformed.glb",
  );
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["wheel-front-left"].geometry}
        material={materials.colormap}
        position={[0.3, 0.3, 0.81]}
      />
    </group>
  );
}

useGLTF.preload("/models/vehicles/city/hatchback-sports-transformed.glb");
