/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\police.glb --transform -o C:\Users\emanu\next-portfolio\public\police.jsx --shadows 
Files: .\police.glb [195.36KB] > C:\Users\emanu\next-portfolio\public\police-transformed.glb [13.94KB] (93%)
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function Police(props) {
  const { nodes, materials } = useGLTF(
    "/models/vehicles/city/police-transformed.glb",
  );
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["wheel-front-left"].geometry}
        material={materials.colormap}
        position={[0.3, 0.3, 0.81]}
      />
    </group>
  );
}

useGLTF.preload("/models/vehicles/city/police-transformed.glb");
