/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\sedan.glb --transform -o C:\Users\emanu\next-portfolio\public\sedan.jsx --shadows 
Files: .\sedan.glb [172.24KB] > C:\Users\emanu\next-portfolio\public\sedan-transformed.glb [12.91KB] (93%)
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function Sedan(props) {
  const { nodes, materials } = useGLTF(
    "/models/vehicles/city/sedan-transformed.glb",
  );
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.body.geometry}
        material={materials.colormap}
        position={[0, 0.15, -0.025]}
      />
    </group>
  );
}

useGLTF.preload("/models/vehicles/city/sedan-transformed.glb");
