/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\sedan-sports.glb --transform -o C:\Users\emanu\next-portfolio\public\sedan-sports.jsx --shadows 
Files: .\sedan-sports.glb [177.69KB] > C:\Users\emanu\next-portfolio\public\sedan-sports-transformed.glb [13.1KB] (93%)
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function SedanSports(props) {
  const { nodes, materials } = useGLTF(
    "/models/vehicles/city/sedan-sports-transformed.glb",
  );
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.body.geometry}
        material={materials.colormap}
        position={[0, 0.15, -0.025]}
      />
    </group>
  );
}

useGLTF.preload("/models/vehicles/city/sedan-sports-transformed.glb");
