/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\suv-luxury.glb --transform -o C:\Users\emanu\next-portfolio\public\suv-luxury.jsx --shadows 
Files: .\suv-luxury.glb [175.93KB] > C:\Users\emanu\next-portfolio\public\suv-luxury-transformed.glb [13.17KB] (93%)
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function SuvLuxury(props) {
  const { nodes, materials } = useGLTF(
    "/models/vehicles/city/suv-luxury-transformed.glb",
  );
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["wheel-back-right"].geometry}
        material={materials.colormap}
        position={[-0.3, 0.3, -0.71]}
      />
    </group>
  );
}

useGLTF.preload("/models/vehicles/city/suv-luxury-transformed.glb");
