/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\suv.glb --transform -o C:\Users\emanu\next-portfolio\public\suv.jsx --shadows 
Files: .\suv.glb [207.59KB] > C:\Users\emanu\next-portfolio\public\suv-transformed.glb [14.64KB] (93%)
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function Suv(props) {
  const { nodes, materials } = useGLTF(
    "/models/vehicles/city/suv-transformed.glb",
  );
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.body.geometry}
        material={materials.colormap}
        position={[0, 0.2, 0]}
      />
    </group>
  );
}

useGLTF.preload("/models/vehicles/city/suv-transformed.glb");
