/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\taxi.glb --transform -o C:\Users\emanu\next-portfolio\public\taxi.jsx --shadows 
Files: .\taxi.glb [175.6KB] > C:\Users\emanu\next-portfolio\public\taxi-transformed.glb [12.85KB] (93%)
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function Taxi(props) {
  const { nodes, materials } = useGLTF(
    "/models/vehicles/city/taxi-transformed.glb",
  );
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["wheel-front-right"].geometry}
        material={materials.colormap}
        position={[-0.3, 0.3, 0.76]}
      />
    </group>
  );
}

useGLTF.preload("/models/vehicles/city/taxi-transformed.glb");
