/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\truck.glb --transform -o C:\Users\emanu\next-portfolio\public\truck.jsx --shadows 
Files: .\truck.glb [176.38KB] > C:\Users\emanu\next-portfolio\public\truck-transformed.glb [13.13KB] (93%)
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function Truck(props) {
  const { nodes, materials } = useGLTF(
    "/models/vehicles/city/truck-transformed.glb",
  );
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["wheel-front-left"].geometry}
        material={materials.colormap}
        position={[0.3, 0.3, 0.86]}
      />
    </group>
  );
}

useGLTF.preload("/models/vehicles/city/truck-transformed.glb");
