/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\van.glb --transform -o C:\Users\emanu\next-portfolio\public\van.jsx --shadows 
Files: .\van.glb [175.69KB] > C:\Users\emanu\next-portfolio\public\van-transformed.glb [13.12KB] (93%)
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function Van(props) {
  const { nodes, materials } = useGLTF(
    "/models/vehicles/city/van-transformed.glb",
  );
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.body.geometry}
        material={materials.colormap}
        position={[0, 0.2, 0.1]}
      />
    </group>
  );
}

useGLTF.preload("/models/vehicles/city/van-transformed.glb");
