/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\Cat.glb --transform -o C:\Users\emanu\next-portfolio\public\cat.jsx --shadows -f png 
Files: .\Cat.glb [272.78KB] > C:\Users\emanu\next-portfolio\public\Cat-transformed.glb [68.7KB] (75%)
*/

import React from "react";
import { useGraph } from "@react-three/fiber";
import { useGLTF, useAnimations } from "@react-three/drei";
import { SkeletonUtils } from "three-stdlib";
import { useAnimalAnimation } from "@/components/3D/entities/useAnimalAnimations";

export function Cat(props) {
  const group = React.useRef();
  const { scene, animations } = useGLTF("/models/animals/Cat-transformed.glb");
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);
  const { nodes, materials } = useGraph(clone);
  const { actions } = useAnimations(animations, group);

  useAnimalAnimation(actions);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="AnimalArmature">
          <primitive object={nodes.All} />
          <primitive object={nodes.Root} />
        </group>
        <skinnedMesh
          name="Cat"
          geometry={nodes.Cat.geometry}
          material={materials.Atlas}
          skeleton={nodes.Cat.skeleton}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/models/animals/Cat-transformed.glb");
