/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\Chick.glb --transform -o C:\Users\emanu\next-portfolio\public\chick.jsx --shadows -f png 
Files: .\Chick.glb [147.02KB] > C:\Users\emanu\next-portfolio\public\Chick-transformed.glb [26.51KB] (82%)
*/

import React from "react";
import { useGraph } from "@react-three/fiber";
import { useGLTF, useAnimations } from "@react-three/drei";
import { SkeletonUtils } from "three-stdlib";
import { useAnimalAnimation } from "@/components/3D/entities/useAnimalAnimations";

export function Chick(props) {
  const group = React.useRef();
  const { scene, animations } = useGLTF(
    "/models/animals/Chick-transformed.glb",
  );
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);
  const { nodes, materials } = useGraph(clone);
  const { actions } = useAnimations(animations, group);

  useAnimalAnimation(actions, ["Idle", "Idle_Peck"]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="AnimalArmature">
          <primitive object={nodes.Root} />
          <primitive object={nodes.Body} />
        </group>
        <skinnedMesh
          name="Chicken"
          geometry={nodes.Chicken.geometry}
          material={materials.Atlas}
          skeleton={nodes.Chicken.skeleton}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/models/animals/Chick-transformed.glb");
