/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\Chicken.glb --transform -o C:\Users\emanu\next-portfolio\public\chicken.jsx --shadows -f png 
Files: .\Chicken.glb [160.6KB] > C:\Users\emanu\next-portfolio\public\Chicken-transformed.glb [27.41KB] (83%)
*/

import React from "react";
import { useGraph } from "@react-three/fiber";
import { useGLTF, useAnimations } from "@react-three/drei";
import { SkeletonUtils } from "three-stdlib";
import { useAnimalAnimation } from "@/components/3D/entities/useAnimalAnimations";

export function Chicken(props) {
  const group = React.useRef();
  const { scene, animations } = useGLTF(
    "/models/animals/Chicken-transformed.glb",
  );
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);
  const { nodes, materials } = useGraph(clone);
  const { actions } = useAnimations(animations, group);

  useAnimalAnimation(actions, ["Idle", "Idle_Peck"]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="AnimalArmature">
          <primitive object={nodes.Root} />
          <primitive object={nodes.Body} />
        </group>
        <skinnedMesh
          name="Chicken"
          geometry={nodes.Chicken.geometry}
          material={materials.Atlas}
          skeleton={nodes.Chicken.skeleton}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/models/animals/Chicken-transformed.glb");
