/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\Dog.glb --transform -o C:\Users\emanu\next-portfolio\public\dog.jsx --shadows -f png 
Files: .\Dog.glb [303.29KB] > C:\Users\emanu\next-portfolio\public\Dog-transformed.glb [70.06KB] (77%)
*/

import React from "react";
import { useGraph } from "@react-three/fiber";
import { useGLTF, useAnimations } from "@react-three/drei";
import { SkeletonUtils } from "three-stdlib";
import { useAnimalAnimation } from "@/components/3D/entities/useAnimalAnimations";

export function Dog(props) {
  const group = React.useRef();
  const { scene, animations } = useGLTF("/models/animals/Dog-transformed.glb");
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);
  const { nodes, materials } = useGraph(clone);
  const { actions } = useAnimations(animations, group);

  useAnimalAnimation(actions);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="AnimalArmature">
          <primitive object={nodes.All} />
          <primitive object={nodes.Root} />
        </group>
        <skinnedMesh
          name="Dog"
          geometry={nodes.Dog.geometry}
          material={materials.Atlas}
          skeleton={nodes.Dog.skeleton}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/models/animals/Dog-transformed.glb");
