/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\Horse.glb --transform -o C:\Users\emanu\next-portfolio\public\horse.jsx --shadows -f png 
Files: .\Horse.glb [254.24KB] > C:\Users\emanu\next-portfolio\public\Horse-transformed.glb [76.25KB] (70%)
*/

import React from "react";
import { useGraph } from "@react-three/fiber";
import { useGLTF, useAnimations } from "@react-three/drei";
import { SkeletonUtils } from "three-stdlib";
import { useAnimalAnimation } from "@/components/3D/entities/useAnimalAnimations";

export function Horse(props) {
  const group = React.useRef();
  const { scene, animations } = useGLTF(
    "/models/animals/Horse-transformed.glb",
  );
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);
  const { nodes, materials } = useGraph(clone);
  const { actions } = useAnimations(animations, group);

  useAnimalAnimation(actions);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="AnimalArmature">
          <primitive object={nodes.All} />
          <primitive object={nodes.Root} />
        </group>
        <skinnedMesh
          name="Horse"
          geometry={nodes.Horse.geometry}
          material={materials.Atlas}
          skeleton={nodes.Horse.skeleton}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/models/animals/Horse-transformed.glb");
