/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\Raccoon.glb --transform -o C:\Users\emanu\next-portfolio\public\Raccoon.jsx --shadows -f png 
Files: .\Raccoon.glb [251.38KB] > C:\Users\emanu\next-portfolio\public\Raccoon-transformed.glb [68.62KB] (73%)
*/

import React from "react";
import { useGraph } from "@react-three/fiber";
import { useGLTF, useAnimations } from "@react-three/drei";
import { SkeletonUtils } from "three-stdlib";
import { useAnimalAnimation } from "@/components/3D/entities/useAnimalAnimations";

export function Raccoon(props) {
  const group = React.useRef();
  const { scene, animations } = useGLTF(
    "/models/animals/Raccoon-transformed.glb",
  );
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);
  const { nodes, materials } = useGraph(clone);
  const { actions } = useAnimations(animations, group);

  useAnimalAnimation(actions);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="AnimalArmature">
          <primitive object={nodes.All} />
          <primitive object={nodes.Root} />
        </group>
        <skinnedMesh
          name="Raccoon"
          geometry={nodes.Raccoon.geometry}
          material={materials["Atlas.002"]}
          skeleton={nodes.Raccoon.skeleton}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/models/animals/Raccoon-transformed.glb");
