/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\Sheep.glb --transform -o C:\Users\emanu\next-portfolio\public\sheep --shadows -f png 
Files: .\Sheep.glb [254.26KB] > C:\Users\emanu\next-portfolio\public\Sheep-transformed.glb [67.25KB] (74%)
*/

import React from "react";
import { useGraph } from "@react-three/fiber";
import { useGLTF, useAnimations } from "@react-three/drei";
import { SkeletonUtils } from "three-stdlib";
import { useAnimalAnimation } from "@/components/3D/entities/useAnimalAnimations";

export function Sheep(props) {
  const group = React.useRef();
  const { scene, animations } = useGLTF(
    "/models/animals/Sheep-transformed.glb",
  );
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);
  const { nodes, materials } = useGraph(clone);
  const { actions } = useAnimations(animations, group);

  useAnimalAnimation(actions);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="AnimalArmature">
          <primitive object={nodes.All} />
          <primitive object={nodes.Root} />
        </group>
        <skinnedMesh
          name="Sheep"
          geometry={nodes.Sheep.geometry}
          material={materials.Atlas}
          skeleton={nodes.Sheep.skeleton}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/models/animals/Sheep-transformed.glb");
