/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\Wolf.glb --transform -o C:\Users\emanu\next-portfolio\public\wolf.jsx --shadows -f png 
Files: .\Wolf.glb [263.7KB] > C:\Users\emanu\next-portfolio\public\Wolf-transformed.glb [67.63KB] (74%)
*/

import React from "react";
import { useGraph } from "@react-three/fiber";
import { useGLTF, useAnimations } from "@react-three/drei";
import { SkeletonUtils } from "three-stdlib";
import { useAnimalAnimation } from "@/components/3D/entities/useAnimalAnimations";

export function Wolf(props) {
  const group = React.useRef();
  const { scene, animations } = useGLTF("/models/animals/Wolf-transformed.glb");
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);
  const { nodes, materials } = useGraph(clone);
  const { actions } = useAnimations(animations, group);

  useAnimalAnimation(actions);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="AnimalArmature">
          <primitive object={nodes.All} />
          <primitive object={nodes.Root} />
        </group>
        <skinnedMesh
          name="Wolf"
          geometry={nodes.Wolf.geometry}
          material={materials.Atlas}
          skeleton={nodes.Wolf.skeleton}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/models/animals/Wolf-transformed.glb");
