/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./World/03Badlands.glb --transform -o C:\Users\emanu\next-portfolio\public\03Badlands.jsx --shadows 
Files: ./World/03Badlands.glb [3.44MB] > C:\Users\emanu\next-portfolio\public\03Badlands-transformed.glb [209.89KB] (94%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Badlands(props) {
  const { nodes, materials } = useGLTF('/models/world/Badlands-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes['floor-old'].geometry} material={materials.colormap} position={[-3, 0, 24]} rotation={[0, -Math.PI / 2, 0]} scale={4} />
      <mesh castShadow receiveShadow geometry={nodes.Props_Broken_Rope_Bridge_01.geometry} material={materials.Color_Palette_01} position={[13, -2, 27]} />
      <mesh castShadow receiveShadow geometry={nodes.RocksPackCube101.geometry} material={materials.arena_atlas} position={[-1, 0, 42]} rotation={[0, -Math.PI / 2, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.MedievalVillagePackMesh004.geometry} material={materials.atlas_asia_pack} position={[13, 0, 37]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh castShadow receiveShadow geometry={nodes.MedievalVillagePackMesh006.geometry} material={materials.village_atlas} position={[14.5, 0.25, 40.25]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.MedievalVillagePackCube002.geometry} material={materials.arena_atlas} position={[9.75, 0, 35.75]} rotation={[0, 0.262, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.Tree_Bare_2_A_Color1.geometry} material={materials.forest} position={[-11.75, 0, 20]} rotation={[0, Math.PI / 4, 0]} scale={0.75} />
      <mesh castShadow receiveShadow geometry={nodes.square_ground2.geometry} material={materials.BrownDark_011} position={[-47, -2, 17]} />
      <mesh castShadow receiveShadow geometry={nodes.square_plain10.geometry} material={materials.Material_0_001} position={[-43, -1, 5]} />
      <mesh castShadow receiveShadow geometry={nodes.square_plainToRock_corner_A10.geometry} material={materials.Material_8_001} position={[43, -1, 5]} rotation={[0, Math.PI / 2, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.square_plainToRock_detail10.geometry} material={materials.BrownDark_0012} position={[-25, -1, 3]} rotation={[0, -Math.PI / 2, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.square_rock10.geometry} material={materials.Brown_001} position={[-47, -1, 35]} />
      <mesh castShadow receiveShadow geometry={nodes.square_rockToSand2.geometry} material={materials.Material_9_001} position={[-47, -1, 47]} rotation={[0, Math.PI / 2, 0]} />
    </group>
  )
}

useGLTF.preload('/models/world/Badlands-transformed.glb')
