/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\Badlands.glb --transform -o C:\Users\emanu\next-portfolio\public\Badlands.jsx --shadows -j 
Files: .\Badlands.glb [3.18MB] > C:\Users\emanu\next-portfolio\public\Badlands-transformed.glb [176.68KB] (94%)
*/

import React from "react";
import { useGLTF } from "@react-three/drei";
import { snapVerticesToGrid } from "@/lib/geometryUtility";

export function Badlands(props) {
  const { nodes, materials } = useGLTF(
    "/models/World/Badlands-transformed.glb",
  );
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["floor-old"].geometry}
        material={materials.colormap}
        position={[-3, 0, 24]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={4}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["floor-old4"].geometry}
        material={materials.colormap}
        position={[-3, 0, 26]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={4}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["floor-old5"].geometry}
        material={materials.colormap}
        position={[-3, 0, 28]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={4}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Props_Broken_Rope_Bridge_01.geometry}
        material={materials.Color_Palette_01}
        position={[13, -2, 27]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Props_Broken_Rope_Bridge_02.geometry}
        material={materials.Color_Palette_01}
        position={[13, -2, 29]}
        rotation={[-Math.PI, 0, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["rock-sand-a"].geometry}
        material={materials.colormap}
        position={[-26.25, 0, 8.25]}
        scale={5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["rock-sand-a4"].geometry}
        material={materials.colormap}
        position={[-14, 0, 17]}
        scale={4}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["rock-sand-c"].geometry}
        material={materials.colormap}
        position={[-34, 0, 41.25]}
        scale={10}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["rock-sand-c4"].geometry}
        material={materials.colormap}
        position={[10, 0, 42]}
        rotation={[-Math.PI, -Math.PI / 6, -Math.PI]}
        scale={5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.RocksPackCube101.geometry}
        material={materials.arena_atlas}
        position={[-1, 0, 42]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.RocksPackCube102.geometry}
        material={materials.arena_atlas}
        position={[-31, 0, 30]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.RocksPackCube103.geometry}
        material={materials.arena_atlas}
        position={[-22, 0, 15.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.RocksPackCube105.geometry}
        material={materials.arena_atlas}
        position={[33.75, 0, 18.75]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.RocksPackCube100.geometry}
        material={materials.arena_atlas}
        position={[-4, 0, 13]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.RocksPackCube104.geometry}
        material={materials.arena_atlas}
        position={[21, 0, 43]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.RocksPackCube099.geometry}
        material={materials.arena_atlas}
        position={[7, 0, 34]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["rock-sand-b"].geometry}
        material={materials.colormap}
        position={[-22, 0, 27]}
        scale={5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["resource-stone"].geometry}
        material={materials.colormap}
        position={[-1, 0, 20]}
        scale={5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["resource-stone-large"].geometry}
        material={materials.colormap}
        position={[-4, 0, 35.5]}
        scale={5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["resource-stone-large4"].geometry}
        material={materials.colormap}
        position={[30.5, 0, 7.5]}
        scale={10}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.RocksPackCube095.geometry}
        material={materials.arena_atlas}
        position={[-35.5, 0, 12.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["campfire-pit"].geometry}
        material={materials.colormap}
        position={[-13.75, 0, 12.25]}
        scale={3}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.wood.geometry}
        material={materials.colormap}
        position={[-13.753, 0.047, 12.289]}
        scale={3}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["campfire-stand"].geometry}
        material={materials.colormap}
        position={[-13.75, 0, 12.25]}
        rotation={[0, Math.PI / 6, 0]}
        scale={3}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["resource-planks"].geometry}
        material={materials.colormap}
        position={[-13.5, 0, 9.25]}
        rotation={[0, Math.PI / 3, 0]}
        scale={3}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["workbench-grind"].geometry}
        material={materials.colormap}
        position={[-15.25, 0, 13.75]}
        rotation={[0, -Math.PI / 3, 0]}
        scale={3}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.wheel.geometry}
        material={materials.colormap}
        position={[-15.25, 0.579, 13.75]}
        rotation={[0, -Math.PI / 3, 0]}
        scale={3}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["tent-canvas"].geometry}
        material={materials.colormap}
        position={[-16, 0, 10.5]}
        rotation={[0, Math.PI / 4, 0]}
        scale={4}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["tool-pickaxe-upgraded"].geometry}
        material={materials.colormap}
        position={[-15.75, 0, 12.2]}
        rotation={[-0.708, 0.633, 0.282]}
        scale={3}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.bucket.geometry}
        material={materials.colormap}
        position={[-14.25, 0, 10.75]}
        scale={3}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.MedievalVillagePackCube190.geometry}
        material={materials.arena_atlas}
        position={[20.75, 0, 37.48]}
        rotation={[0, Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.MedievalVillagePackCube189.geometry}
        material={materials.arena_atlas}
        position={[17, 0, 37]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.MedievalVillagePackCube193.geometry}
        material={materials.arena_atlas}
        position={[19, 0, 37]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.MedievalVillagePackCube194.geometry}
        material={materials.arena_atlas}
        position={[21.05, 0, 39.5]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.MedievalVillagePackCube191.geometry}
        material={materials.arena_atlas}
        position={[15, 0, 37]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.MedievalVillagePackCube192.geometry}
        material={materials.arena_atlas}
        position={[13, 0, 37]}
      />
      <group position={[13, 0, 37]} rotation={[Math.PI / 2, 0, Math.PI / 2]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_22.geometry}
          material={materials.arena_atlas}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_22_1.geometry}
          material={materials.atlas_asia_pack}
        />
      </group>
      <group position={[14.5, 0.25, 40.25]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_23.geometry}
          material={materials.village_atlas}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_23_1.geometry}
          material={materials.atlas_asia_pack}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.MedievalVillagePackMesh020.geometry}
        material={materials.village_atlas}
        position={[14.75, 0, 38.75]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.MedievalVillagePackCube002.geometry}
        material={materials.arena_atlas}
        position={[9.75, 0, 35.75]}
        rotation={[0, 0.262, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.MedievalVillagePackCube003.geometry}
        material={materials.arena_atlas}
        position={[10.75, 0, 35]}
        rotation={[0, -Math.PI / 6, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.MedievalVillagePackCube004.geometry}
        material={materials.arena_atlas}
        position={[10, 0, 34]}
        rotation={[0, 0.262, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["structure-floor"].geometry}
        material={materials.colormap}
        position={[21, 0, 38.5]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Group.geometry}
        material={materials.colormap}
        position={[21.5, 1, 38]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree_Bare_2_A_Color1.geometry}
        material={materials.forest}
        position={[-11.75, 0, 20]}
        rotation={[0, Math.PI / 4, 0]}
        scale={0.75}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree_Bare_2_A_Color14.geometry}
        material={materials.forest}
        position={[1.25, 0, 8.25]}
        rotation={[0, -Math.PI / 6, 0]}
        scale={0.75}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree_Bare_2_A_Color15.geometry}
        material={materials.forest}
        position={[14.75, 0, 32.75]}
        scale={0.75}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree_Bare_2_A_Color16.geometry}
        material={materials.forest}
        position={[38.25, 0, 40.75]}
        rotation={[0, 0.262, 0]}
        scale={0.75}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree_Bare_2_A_Color19.geometry}
        material={materials.forest}
        position={[12.5, 0, 45.5]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.75}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree_Bare_2_A_Color110.geometry}
        material={materials.forest}
        position={[28.5, 0, 21.25]}
        rotation={[0, -Math.PI / 4, 0]}
        scale={0.75}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree_Bare_2_A_Color111.geometry}
        material={materials.forest}
        position={[37, 0, 7]}
        rotation={[0, -1.309, 0]}
        scale={0.75}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree_Bare_2_A_Color112.geometry}
        material={materials.forest}
        position={[17.5, 0, 2.75]}
        rotation={[-Math.PI, -Math.PI / 6, -Math.PI]}
        scale={0.75}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree_Bare_2_A_Color113.geometry}
        material={materials.forest}
        position={[-29.25, 0, 14]}
        rotation={[-Math.PI, 0.262, -Math.PI]}
        scale={0.75}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree_Bare_2_A_Color114.geometry}
        material={materials.forest}
        position={[-40.25, 0, 29]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={0.75}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree_Bare_2_A_Color115.geometry}
        material={materials.forest}
        position={[-42.5, 0, 41.25]}
        rotation={[-Math.PI, 0.262, -Math.PI]}
        scale={0.75}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree_Bare_2_A_Color116.geometry}
        material={materials.forest}
        position={[-4.75, 0, 17.75]}
        scale={0.75}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree_Bare_2_A_Color117.geometry}
        material={materials.forest}
        position={[-27.75, 0, 36]}
        rotation={[0, -Math.PI / 6, 0]}
        scale={0.75}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree_Bare_2_A_Color118.geometry}
        material={materials.forest}
        position={[-26.75, 0, 45]}
        rotation={[0, -Math.PI / 4, 0]}
        scale={0.75}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree_Bare_2_A_Color119.geometry}
        material={materials.forest}
        position={[-4.75, 0, 45]}
        rotation={[0, Math.PI / 6, 0]}
        scale={0.75}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree_Bare_2_A_Color120.geometry}
        material={materials.forest}
        position={[2.5, 0, 32.5]}
        rotation={[0, -0.262, 0]}
        scale={0.75}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree_Bare_2_B_Color1.geometry}
        material={materials.forest}
        position={[-34.75, 0, 32.5]}
        scale={0.75}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree_Bare_2_B_Color14.geometry}
        material={materials.forest}
        position={[-17.75, 0, 16.5]}
        rotation={[0, -Math.PI / 6, 0]}
        scale={0.75}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree_Bare_2_B_Color15.geometry}
        material={materials.forest}
        position={[-21.5, 0, 7.75]}
        scale={0.75}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree_Bare_2_B_Color16.geometry}
        material={materials.forest}
        position={[-43.25, 0, 12.75]}
        rotation={[0, Math.PI / 6, 0]}
        scale={0.75}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree_Bare_2_B_Color17.geometry}
        material={materials.forest}
        position={[3.75, 0, 15]}
        rotation={[0, 0.262, 0]}
        scale={0.75}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree_Bare_2_B_Color18.geometry}
        material={materials.forest}
        position={[42, 0, 19.5]}
        scale={0.75}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree_Bare_2_B_Color19.geometry}
        material={materials.forest}
        position={[31, 0, 37.25]}
        rotation={[0, Math.PI / 6, 0]}
        scale={0.75}
      />
      <group position={[-47, -1, 47]} rotation={[0, Math.PI / 2, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={snapVerticesToGrid(nodes.mesh_32.geometry)}
          material={materials.Material_9_001}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={snapVerticesToGrid(nodes.mesh_32_1.geometry)}
          material={materials.Material_0_001}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={snapVerticesToGrid(nodes.mesh_32_2.geometry)}
          material={materials.Brown_001}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={snapVerticesToGrid(nodes.mesh_32_3.geometry)}
          material={materials.BrownDark_001}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={snapVerticesToGrid(nodes.mesh_32_4.geometry)}
          material={materials.Material_8_001}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/models/World/Badlands-transformed.glb");
