/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./World/07City.glb --transform -o C:\Users\emanu\next-portfolio\public\07City.jsx --shadows 
Files: ./World/07City.glb [7.83KB] > C:\Users\emanu\next-portfolio\public\07City-transformed.glb [2.71KB] (65%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function City(props) {
  const { nodes, materials } = useGLTF('/models/world/City-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.square_city10.geometry} material={materials.BrownDark2} position={[-47, -1, 37]} />
      <group position={[-47, -1, 17]}>
        <mesh castShadow receiveShadow geometry={nodes.mesh_1.geometry} material={materials.BrownDark_001} />
        <mesh castShadow receiveShadow geometry={nodes.mesh_1_1.geometry} material={materials.Water_001} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/world/City-transformed.glb')
