/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\City.glb --transform -o C:\Users\emanu\next-portfolio\public\City.jsx --shadows -j 
Files: .\City.glb [15.79MB] > C:\Users\emanu\next-portfolio\public\City-transformed.glb [1.06MB] (93%)
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function City(props) {
  const { nodes, materials } = useGLTF("/models/World/City-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.square_water_detail2.geometry}
        material={materials.Water}
        position={[-47, -1, 1]}
        rotation={[0, 1.571, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.square_city2.geometry}
        material={materials.BrownDark2}
        position={[-47, -1, 21]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["railroad-straight12"].geometry}
        material={materials.colormap}
        position={[0, 0.12, 35]}
        rotation={[0, -1.571, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["tile-low108"].geometry}
        material={materials.colormap2}
        position={[15, 0, 29]}
        scale={6}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["bridge-pillar"].geometry}
        material={materials.colormap2}
        position={[18.25, 0, 62.25]}
        scale={6}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["sign-highway-detailed"].geometry}
        material={materials.colormap2}
        position={[-17, 0, 89]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={6}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["sign-highway-detailed4"].geometry}
        material={materials.colormap2}
        position={[20.75, 0, 95]}
        scale={6}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["construction-cone4"].geometry}
        material={materials.colormap2}
        position={[31.75, 0, 74.25]}
        scale={6}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["construction-barrier"].geometry}
        material={materials.colormap2}
        position={[-8, 0, 49.5]}
        rotation={[0, 1.571, 0]}
        scale={6}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.trafficlight_B.geometry}
        material={materials.citybits_texture}
        position={[-1.75, 0.12, 68.25]}
        rotation={[0, 1.571, 0]}
        scale={4}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.trafficlight_B4.geometry}
        material={materials.citybits_texture}
        position={[-4.25, 0.12, 73.75]}
        rotation={[0, -1.571, 0]}
        scale={4}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.trafficlight_B5.geometry}
        material={materials.citybits_texture}
        position={[-25.75, 0.12, 74.25]}
        rotation={[0, 1.571, 0]}
        scale={4}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.trafficlight_B6.geometry}
        material={materials.citybits_texture}
        position={[-28.25, 0.12, 79.75]}
        rotation={[0, -1.571, 0]}
        scale={4}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.trafficlight_B7.geometry}
        material={materials.citybits_texture}
        position={[10.25, 0.12, 74.25]}
        rotation={[0, 1.571, 0]}
        scale={4}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.trafficlight_B8.geometry}
        material={materials.citybits_texture}
        position={[7.75, 0.12, 79.75]}
        rotation={[0, -1.571, 0]}
        scale={4}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.trafficlight_B9.geometry}
        material={materials.citybits_texture}
        position={[4.25, 0.12, 50.25]}
        rotation={[0, 1.571, 0]}
        scale={4}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.trafficlight_B12.geometry}
        material={materials.citybits_texture}
        position={[1.75, 0.12, 55.75]}
        rotation={[0, -1.571, 0]}
        scale={4}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.trafficlight_B13.geometry}
        material={materials.citybits_texture}
        position={[-42.25, 0.12, 48.25]}
        scale={4}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.trafficlight_B14.geometry}
        material={materials.citybits_texture}
        position={[-47.75, 0.12, 45.75]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={4}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["sign-highway-wide"].geometry}
        material={materials.colormap2}
        position={[21, 3, 62]}
        rotation={[0, 1.571, 0]}
        scale={6}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.streetlight.geometry}
        material={materials.citybits_texture}
        position={[33, 0, 79.75]}
        rotation={[0, -1.571, 0]}
        scale={4}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.streetlight4.geometry}
        material={materials.citybits_texture}
        position={[21.25, 0, 38.25]}
        rotation={[0, 1.571, 0]}
        scale={4}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.streetlight5.geometry}
        material={materials.citybits_texture}
        position={[41.5, 0, 38.25]}
        rotation={[0, 1.571, 0]}
        scale={4}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.streetlight6.geometry}
        material={materials.citybits_texture}
        position={[-18, 0, 55.75]}
        rotation={[0, -1.571, 0]}
        scale={4}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.streetlight8.geometry}
        material={materials.citybits_texture}
        position={[0, 0, 92]}
        rotation={[0, -1.571, 0]}
        scale={4}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.streetlight9.geometry}
        material={materials.citybits_texture}
        position={[0, 0, 92]}
        rotation={[0, 1.571, 0]}
        scale={4}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.streetlight10.geometry}
        material={materials.citybits_texture}
        position={[-24, 0, 92]}
        rotation={[0, -1.571, 0]}
        scale={4}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.streetlight11.geometry}
        material={materials.citybits_texture}
        position={[-24, 0, 92]}
        rotation={[0, 1.571, 0]}
        scale={4}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.streetlight12.geometry}
        material={materials.citybits_texture}
        position={[24, 0, 92]}
        rotation={[0, -1.571, 0]}
        scale={4}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.streetlight13.geometry}
        material={materials.citybits_texture}
        position={[24, 0, 92]}
        rotation={[0, 1.571, 0]}
        scale={4}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.streetlight14.geometry}
        material={materials.citybits_texture}
        position={[-36.25, 0, 55.75]}
        rotation={[0, -1.571, 0]}
        scale={4}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["building-b"].geometry}
        material={materials.colormap51}
        position={[29.75, 0.12, 83]}
        rotation={[0, -1.571, 0]}
        scale={5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["building-b4"].geometry}
        material={materials.colormap51}
        position={[14.75, 0.12, 46.75]}
        rotation={[0, 1.571, 0]}
        scale={5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["building-n"].geometry}
        material={materials.colormap51}
        position={[-25, 0.24, 68.75]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={4.5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["building-n4"].geometry}
        material={materials.colormap51}
        position={[42, 0.24, 49.5]}
        scale={4.5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["building-skyscraper-c"].geometry}
        material={materials.colormap51}
        position={[-27, 0.24, 41.5]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={4.5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["building-j"].geometry}
        material={materials.colormap51}
        position={[-36.25, 0.12, 42.25]}
        scale={5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["building-j4"].geometry}
        material={materials.colormap51}
        position={[30, 0.12, 48]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["building-k"].geometry}
        material={materials.colormap51}
        position={[-33.5, 0.12, 68.75]}
        rotation={[0, 1.571, 0]}
        scale={5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["building-skyscraper-d"].geometry}
        material={materials.colormap51}
        position={[-44.25, 0.12, 76.75]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={4.5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["building-skyscraper-a"].geometry}
        material={materials.colormap51}
        position={[-45, 0.12, 65]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={4.5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["building-e"].geometry}
        material={materials.colormap51}
        position={[-5.25, 0.12, 65.25]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["building-e4"].geometry}
        material={materials.colormap51}
        position={[-34.75, 0.12, 82.75]}
        scale={5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["building-d"].geometry}
        material={materials.colormap51}
        position={[23.75, 0.12, 83]}
        scale={5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["building-k4"].geometry}
        material={materials.colormap51}
        position={[11.5, 0.12, 71]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["building-a"].geometry}
        material={materials.colormap51}
        position={[-20.75, 0.12, 41.25]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["building-h"].geometry}
        material={materials.colormap51}
        position={[21.25, 0.12, 71.25]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["building-g"].geometry}
        material={materials.colormap51}
        position={[27.75, 0.12, 71]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["building-type-q"].geometry}
        material={materials.colormap51}
        position={[2.75, 0.12, 47.25]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["building-type-k"].geometry}
        material={materials.colormap51}
        position={[-3.75, 0.12, 47.5]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["building-f"].geometry}
        material={materials.colormap51}
        position={[27.75, 0.12, 65.75]}
        rotation={[0, -1.571, 0]}
        scale={5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["building-type-p"].geometry}
        material={materials.colormap51}
        position={[40.75, 0.12, 71.5]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["building-k5"].geometry}
        material={materials.colormap51}
        position={[-24, 0.12, 83]}
        scale={5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["building-k6"].geometry}
        material={materials.colormap51}
        position={[39, 0.12, 83]}
        scale={5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["building-skyscraper-b"].geometry}
        material={materials.colormap51}
        position={[-44.5, 0.12, 82.75]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={4.5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["detail-parasol-a"].geometry}
        material={materials.colormap51}
        position={[-39.5, 0, 48.5]}
        scale={5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["detail-parasol-a4"].geometry}
        material={materials.colormap51}
        position={[26.5, 0, 53.75]}
        scale={5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["detail-parasol-a5"].geometry}
        material={materials.colormap51}
        position={[33.75, 0, 53.75]}
        scale={5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.trash.geometry}
        material={materials.colormap49}
        position={[-31, 0.12, 49.502]}
        rotation={[Math.PI, -Math.PI / 6, Math.PI]}
        scale={1.5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.trash4.geometry}
        material={materials.colormap49}
        position={[-22.5, 0.12, 45.25]}
        rotation={[Math.PI, -Math.PI / 4, Math.PI]}
        scale={1.5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.trash5.geometry}
        material={materials.colormap49}
        position={[-10.5, 0.12, 78]}
        rotation={[Math.PI, -Math.PI / 3, Math.PI]}
        scale={1.25}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.trash6.geometry}
        material={materials.colormap49}
        position={[8.25, 0.12, 84.75]}
        rotation={[0, Math.PI / 4, 0]}
        scale={1.25}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["fountain-round-detail"].geometry}
        material={materials.colormap50}
        position={[-18, 0.12, 47]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["(_ignore)"].geometry}
        material={materials.Water2}
        position={[-18, 0.26, 47]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["tree-small"].geometry}
        material={materials.colormap51}
        position={[-32.25, 0, 48.25]}
        scale={5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["tree-small4"].geometry}
        material={materials.colormap51}
        position={[-13.5, 0, 45.5]}
        scale={5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["tree-small5"].geometry}
        material={materials.colormap51}
        position={[-22.5, 0, 48.5]}
        scale={5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.bench.geometry}
        material={materials.colormap}
        position={[-15, 0.12, 47]}
        rotation={[0, -1.571, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.dumpster.geometry}
        material={materials.citybits_texture}
        position={[20.75, 0.12, 84.25]}
        rotation={[0, -1.571, 0]}
        scale={3}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.dumpster4.geometry}
        material={materials.citybits_texture}
        position={[20.75, 0.12, 81.75]}
        rotation={[0, -1.571, 0]}
        scale={3}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.dumpster5.geometry}
        material={materials.citybits_texture}
        position={[-26, 0.12, 63.5]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={3}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.dumpster8.geometry}
        material={materials.citybits_texture}
        position={[-23.5, 0.12, 63.5]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={3}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.firehydrant.geometry}
        material={materials.citybits_texture}
        position={[0.75, 0.12, 79.25]}
        scale={3}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.firehydrant3.geometry}
        material={materials.citybits_texture}
        position={[1.25, 0.12, 63.25]}
        scale={3}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.firehydrant6.geometry}
        material={materials.citybits_texture}
        position={[10.75, 0.12, 54.75]}
        scale={3}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.firehydrant7.geometry}
        material={materials.citybits_texture}
        position={[-10.75, 0.12, 39.25]}
        scale={3}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.firehydrant8.geometry}
        material={materials.citybits_texture}
        position={[-42, 0.12, 46]}
        scale={3}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.firehydrant9.geometry}
        material={materials.citybits_texture}
        position={[-40.75, 0.12, 78.75]}
        scale={3}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.firehydrant10.geometry}
        material={materials.citybits_texture}
        position={[31.25, 0.12, 63.25]}
        scale={3}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.firehydrant11.geometry}
        material={materials.citybits_texture}
        position={[24.5, 0.12, 44.5]}
        scale={3}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.firehydrant12.geometry}
        material={materials.citybits_texture}
        position={[-12.75, 0.12, 79.25]}
        scale={3}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_A.geometry}
        material={materials.citybits_texture}
        position={[14, 0.12, 47]}
        rotation={[0, -Math.PI / 4, 0]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.box_A4.geometry}
        material={materials.citybits_texture}
        position={[2, 0.12, 49.5]}
        rotation={[0, -1.571, 0]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["fountain-center"].geometry}
        material={materials.colormap50}
        position={[-6, 0.2, 80.75]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={1.5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["(_ignore)2"].geometry}
        material={materials.Water2}
        position={[-6, 0.41, 80.75]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={1.5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["tile-low146"].geometry}
        material={materials.colormap2}
        position={[3, 0, 83]}
        scale={6}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.bench5.geometry}
        material={materials.colormap}
        position={[1, 0.12, 81.25]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Group.geometry}
        material={materials.colormap49}
        position={[-16.5, 0.929, 84.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["flowers-tall"].geometry}
        material={materials.colormap49}
        position={[2.5, 0.12, 85]}
        rotation={[0, 0.262, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["flowers-tall4"].geometry}
        material={materials.colormap49}
        position={[5.25, 0.12, 85.25]}
        rotation={[0, -Math.PI / 3, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["flowers-tall5"].geometry}
        material={materials.colormap49}
        position={[4, 0.12, 81.25]}
        rotation={[0, -Math.PI / 6, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Group21.geometry}
        material={materials.colormap49}
        position={[14.064, 0.12, 80.845]}
        rotation={[0, -0.262, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["lightpost-all"].geometry}
        material={materials.colormap60}
        position={[-16.75, 0.12, 81.25]}
        scale={1.5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.bench29.geometry}
        material={materials.colormap}
        position={[33, 0.12, 22]}
        rotation={[-Math.PI, 0, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.bench30.geometry}
        material={materials.colormap}
        position={[39, 0.12, 22]}
        rotation={[-Math.PI, 0, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.bench31.geometry}
        material={materials.colormap}
        position={[45, 0.12, 22]}
        rotation={[-Math.PI, 0, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.bench38.geometry}
        material={materials.colormap}
        position={[-45, 0.12, 22]}
        rotation={[-Math.PI, 0, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.bench39.geometry}
        material={materials.colormap}
        position={[-39, 0.12, 22]}
        rotation={[-Math.PI, 0, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.bench40.geometry}
        material={materials.colormap}
        position={[-33, 0.12, 22]}
        rotation={[-Math.PI, 0, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["floor-stone265"].geometry}
        material={materials.colormap}
        position={[-8, 0.12, 23]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.bench35.geometry}
        material={materials.colormap}
        position={[-3, 0.12, 22]}
        rotation={[-Math.PI, 0, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["tree-small31"].geometry}
        material={materials.colormap51}
        position={[-3, 0.12, 31]}
        scale={4}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.barrierMedium19.geometry}
        material={materials.Metal}
        position={[-1.5, 0.12, 20.1]}
        scale={0.75}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["driveway-long30"].geometry}
        material={materials.colormap51}
        position={[4.5, 0.12, 28.5]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={7.5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["floor-stone265001"].geometry}
        material={materials.colormap}
        position={[-8, 0.12, 23]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["tile-low108001"].geometry}
        material={materials.colormap2}
        position={[15, 0, 29]}
        scale={6}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["tile-low108002"].geometry}
        material={materials.colormap2}
        position={[15, 0, 29]}
        scale={6}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["tile-low108003"].geometry}
        material={materials.colormap2}
        position={[15, 0, 29]}
        scale={6}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["tile-low108004"].geometry}
        material={materials.colormap2}
        position={[15, 0, 29]}
        scale={6}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["tile-low108005"].geometry}
        material={materials.colormap2}
        position={[15, 0, 29]}
        scale={6}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["road-driveway-single002"].geometry}
        material={materials.colormap2}
        position={[-3, 0, 53]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={6}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["road-driveway-single003"].geometry}
        material={materials.colormap2}
        position={[-3, 0, 53]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={6}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["iron-fence-border-column8001"].geometry}
        material={materials.colormap60}
        position={[-18.75, 0.12, 60.75]}
        scale={1.5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["iron-fence-border-column8002"].geometry}
        material={materials.colormap60}
        position={[-18.75, 0.12, 60.75]}
        scale={1.5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["iron-fence-border-column8003"].geometry}
        material={materials.colormap60}
        position={[-18.75, 0.12, 60.75]}
        scale={1.5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["iron-fence-border-column8004"].geometry}
        material={materials.colormap60}
        position={[-18.75, 0.12, 60.75]}
        scale={1.5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["iron-fence-border-column8005"].geometry}
        material={materials.colormap60}
        position={[-18.75, 0.12, 60.75]}
        scale={1.5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["iron-fence-border-column8006"].geometry}
        material={materials.colormap60}
        position={[-18.75, 0.12, 60.75]}
        scale={1.5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["iron-fence-border-column8007"].geometry}
        material={materials.colormap60}
        position={[-18.75, 0.12, 60.75]}
        scale={1.5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["iron-fence-border-column8008"].geometry}
        material={materials.colormap60}
        position={[-18.75, 0.12, 60.75]}
        scale={1.5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["railroad-straight12001"].geometry}
        material={materials.colormap}
        position={[0, 0.12, 35]}
        rotation={[0, -1.571, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["path-stones-long78001"].geometry}
        material={materials.colormap51}
        position={[-1, 0.12, 32.5]}
        rotation={[0, -1.571, 0]}
        scale={5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["path-stones-long78002"].geometry}
        material={materials.colormap51}
        position={[-1, 0.12, 32.5]}
        rotation={[0, -1.571, 0]}
        scale={5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["path-stones-long78003"].geometry}
        material={materials.colormap51}
        position={[-1, 0.12, 32.5]}
        rotation={[0, -1.571, 0]}
        scale={5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["path-stones-long78004"].geometry}
        material={materials.colormap51}
        position={[-1, 0.12, 32.5]}
        rotation={[0, -1.571, 0]}
        scale={5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["path-stones-long78005"].geometry}
        material={materials.colormap51}
        position={[-1, 0.12, 32.5]}
        rotation={[0, -1.571, 0]}
        scale={5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["path-stones-long78006"].geometry}
        material={materials.colormap51}
        position={[-1, 0.12, 32.5]}
        rotation={[0, -1.571, 0]}
        scale={5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["path-stones-long78007"].geometry}
        material={materials.colormap51}
        position={[-1, 0.12, 32.5]}
        rotation={[0, -1.571, 0]}
        scale={5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["path-stones-long78008"].geometry}
        material={materials.colormap51}
        position={[-1, 0.12, 32.5]}
        rotation={[0, -1.571, 0]}
        scale={5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.planter132001.geometry}
        material={materials.colormap51}
        position={[-0.5, 0.12, 33.25]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.planter132002.geometry}
        material={materials.colormap51}
        position={[-0.5, 0.12, 33.25]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.planter132003.geometry}
        material={materials.colormap51}
        position={[-0.5, 0.12, 33.25]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.planter132004.geometry}
        material={materials.colormap51}
        position={[-0.5, 0.12, 33.25]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.planter132005.geometry}
        material={materials.colormap51}
        position={[-0.5, 0.12, 33.25]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.planter132006.geometry}
        material={materials.colormap51}
        position={[-0.5, 0.12, 33.25]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.planter132007.geometry}
        material={materials.colormap51}
        position={[-0.5, 0.12, 33.25]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.planter132008.geometry}
        material={materials.colormap51}
        position={[-0.5, 0.12, 33.25]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.planter132009.geometry}
        material={materials.colormap51}
        position={[-0.5, 0.12, 33.25]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.planter132010.geometry}
        material={materials.colormap51}
        position={[-0.5, 0.12, 33.25]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.hedge001.geometry}
        material={materials.colormap49}
        position={[-19.5, 0.12, 49]}
        scale={1.5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.hedge002.geometry}
        material={materials.colormap49}
        position={[-19.5, 0.12, 49]}
        scale={1.5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.hedge003.geometry}
        material={materials.colormap49}
        position={[-19.5, 0.12, 49]}
        scale={1.5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["lightpost-all001"].geometry}
        material={materials.colormap60}
        position={[-16.75, 0.12, 81.25]}
        scale={1.5}
      />
    </group>
  );
}

useGLTF.preload("/models/World/City-transformed.glb");
