/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\Desert.glb --transform -o C:\Users\emanu\next-portfolio\public\Desert.jsx --shadows -j 
Files: .\Desert.glb [2.97MB] > C:\Users\emanu\next-portfolio\public\Desert-transformed.glb [175.94KB] (94%)
*/

import React from "react";
import { useGLTF } from "@react-three/drei";
import { snapVerticesToGrid } from "@/lib/geometryUtility";

export function Desert(props) {
  const { nodes, materials } = useGLTF("/models/World/Desert-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Parts_Pile_Small.geometry}
        material={materials.resource}
        position={[10.75, 0, 40.25]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Parts_Pile_Medium.geometry}
        material={materials.resource}
        position={[9.75, 0, 40]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Parts_Cog.geometry}
        material={materials.resource}
        position={[9.5, 0, 40.75]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Parts_Cog4.geometry}
        material={materials.resource}
        position={[10, 0.1, 40.5]}
        rotation={[-Math.PI / 3, 0, 0]}
        scale={0.75}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Textiles_Stack_Small.geometry}
        material={materials.resource}
        position={[13.25, 0, 40]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Textiles_Stack_Large_Colored.geometry}
        material={materials.resource}
        position={[15, 0, 40.25]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Fuel_A_Barrels.geometry}
        material={materials.resource}
        position={[15.5, 0.25, 35.75]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Fuel_A_Jerrycan.geometry}
        material={materials.resource}
        position={[14.25, 0, 36.75]}
        rotation={[0, Math.PI / 4, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Pallet_Wood_Covered_B.geometry}
        material={materials.resource}
        position={[15.5, 0, 35.75]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Fuel_A_Barrel.geometry}
        material={materials.resource}
        position={[13.75, 0, 35.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["fence-curved"].geometry}
        material={materials.colormap}
        position={[15.5, 0, 45.25]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["fence-curved4"].geometry}
        material={materials.colormap}
        position={[15.5, 0, 39.25]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["fence-curved5"].geometry}
        material={materials.colormap}
        position={[9.5, 0, 39.25]}
        rotation={[0, Math.PI / 2, 0]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["fence-broken"].geometry}
        material={materials.colormap}
        position={[15.5, 0, 41.25]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["fence-broken3"].geometry}
        material={materials.colormap}
        position={[9.5, 0, 45.25]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["fence-broken5"].geometry}
        material={materials.colormap}
        position={[11.5, 0, 39.25]}
        rotation={[0, Math.PI / 2, 0]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.fence.geometry}
        material={materials.colormap}
        position={[15.5, 0, 43.25]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.fence4.geometry}
        material={materials.colormap}
        position={[13.5, 0, 45.25]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.fence5.geometry}
        material={materials.colormap}
        position={[11.5, 0, 45.25]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.fence6.geometry}
        material={materials.colormap}
        position={[13.5, 0, 39.25]}
        rotation={[0, Math.PI / 2, 0]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.arrows2.geometry}
        material={materials.colormap4}
        position={[7.5, 0, 39.5]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["palm-bend"].geometry}
        material={materials.colormap5}
        position={[-32.377, 0, 42.659]}
        rotation={[0, -Math.PI / 6, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["palm-detailed-bend"].geometry}
        material={materials.colormap5}
        position={[22.75, 0, 44.25]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["palm-detailed-bend4"].geometry}
        material={materials.colormap5}
        position={[-21.5, 0, 13.75]}
        rotation={[0, -Math.PI / 6, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["palm-detailed-straight"].geometry}
        material={materials.colormap5}
        position={[0.25, 0.25, 41.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["palm-detailed-straight3"].geometry}
        material={materials.colormap5}
        position={[4.5, 0.25, 18.5]}
        rotation={[0, Math.PI / 6, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["palm-detailed-straight5"].geometry}
        material={materials.colormap5}
        position={[-27.5, 0, 27]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["palm-straight"].geometry}
        material={materials.colormap5}
        position={[31.75, 0, 33.25]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["palm-straight3"].geometry}
        material={materials.colormap5}
        position={[42.5, 0, 22]}
        rotation={[0, -Math.PI / 4, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["palm-straight4"].geometry}
        material={materials.colormap5}
        position={[-39.75, 0, 24.25]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["palm-straight6"].geometry}
        material={materials.colormap5}
        position={[1.75, 0, 28]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.hole.geometry}
        material={materials.colormap5}
        position={[-38.75, 0, 34]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.hole4.geometry}
        material={materials.colormap5}
        position={[19.326, 0, 29.646]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.hole5.geometry}
        material={materials.colormap5}
        position={[-15.174, 0, 26.646]}
        rotation={[0, Math.PI / 4, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["rocks-sand-b"].geometry}
        material={materials.colormap5}
        position={[-6.25, 0, 20]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["rocks-sand-b4"].geometry}
        material={materials.colormap5}
        position={[26.5, 0, 36.25]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["rocks-sand-b5"].geometry}
        material={materials.colormap5}
        position={[38.25, 0, 15.75]}
        rotation={[0, -Math.PI / 4, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["patch-sand-foliage"].geometry}
        material={materials.colormap5}
        position={[-27.5, 0, 26.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["patch-sand-foliage4"].geometry}
        material={materials.colormap5}
        position={[1.5, 0, 27.5]}
        rotation={[0, -Math.PI / 4, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["rocks-sand-a"].geometry}
        material={materials.colormap5}
        position={[-13.25, 0, 9.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["rocks-sand-a4"].geometry}
        material={materials.colormap5}
        position={[-33.75, 0, 21.75]}
        rotation={[0, Math.PI / 4, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["rocks-sand-a5"].geometry}
        material={materials.colormap5}
        position={[39.75, 0, 30]}
        rotation={[0, -Math.PI / 4, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["rock-flat"].geometry}
        material={materials.colormap13}
        position={[-0.5, 0, 42]}
        scale={4}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["rock-flat4"].geometry}
        material={materials.colormap13}
        position={[-29.75, 0, 13]}
        scale={4}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["rock-flat5"].geometry}
        material={materials.colormap13}
        position={[-2.5, 0, 6.75]}
        rotation={[-Math.PI, -0.262, -Math.PI]}
        scale={4}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["rock-flat6"].geometry}
        material={materials.colormap13}
        position={[30.5, 0, 21.5]}
        rotation={[-Math.PI, -Math.PI / 3, -Math.PI]}
        scale={4}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["rock-flat7"].geometry}
        material={materials.colormap13}
        position={[39.75, 0, 41.25]}
        rotation={[-Math.PI, -Math.PI / 6, -Math.PI]}
        scale={4}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["resource-stone-large"].geometry}
        material={materials.colormap13}
        position={[0, 0, 17.25]}
        scale={5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["resource-stone-large4"].geometry}
        material={materials.colormap13}
        position={[-4.5, 0, 34.25]}
        rotation={[0, -Math.PI / 3, 0]}
        scale={5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["resource-stone-large5"].geometry}
        material={materials.colormap13}
        position={[10.75, 0, 29.25]}
        rotation={[0, -0.262, 0]}
        scale={5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["resource-stone-large6"].geometry}
        material={materials.colormap13}
        position={[29.5, 0, 11.5]}
        rotation={[0, -Math.PI / 3, 0]}
        scale={5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["resource-stone-large7"].geometry}
        material={materials.colormap13}
        position={[13.5, 0, 3.25]}
        rotation={[0, -Math.PI / 6, 0]}
        scale={5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["resource-stone-large8"].geometry}
        material={materials.colormap13}
        position={[-7.75, 0, 11]}
        rotation={[0, -Math.PI / 4, 0]}
        scale={5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["resource-stone-large10"].geometry}
        material={materials.colormap13}
        position={[-28.75, 0, 35.75]}
        scale={5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["resource-stone-large11"].geometry}
        material={materials.colormap13}
        position={[-27.25, 0, 44.5]}
        rotation={[0, -Math.PI / 6, 0]}
        scale={5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["resource-stone-large12"].geometry}
        material={materials.colormap13}
        position={[-39.75, 0, 43.75]}
        rotation={[0, -Math.PI / 3, 0]}
        scale={5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["resource-stone-large13"].geometry}
        material={materials.colormap13}
        position={[-33.75, 0, 29.75]}
        rotation={[0, -Math.PI / 3, 0]}
        scale={5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["resource-stone-large14"].geometry}
        material={materials.colormap13}
        position={[-43, 0, 9]}
        rotation={[0, -0.262, 0]}
        scale={5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["resource-stone-large15"].geometry}
        material={materials.colormap13}
        position={[-37, 0, 14.75]}
        rotation={[0, -Math.PI / 4, 0]}
        scale={5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["resource-stone-large16"].geometry}
        material={materials.colormap13}
        position={[-44.25, 0, 30.75]}
        rotation={[0, -Math.PI / 4, 0]}
        scale={5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["resource-stone-large17"].geometry}
        material={materials.colormap13}
        position={[-24.75, 0, 18.25]}
        rotation={[0, -Math.PI / 4, 0]}
        scale={5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["resource-stone-large18"].geometry}
        material={materials.colormap13}
        position={[-22.5, 0, 7]}
        rotation={[0, 0.262, 0]}
        scale={5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.tower.geometry}
        material={materials.colormap15}
        position={[-18, 0, 22]}
        rotation={[0, Math.PI / 6, 0]}
      />
      <group position={[-39, -1, 1]} rotation={[0, Math.PI / 2, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={snapVerticesToGrid(nodes.mesh_24.geometry)}
          material={materials.Brown}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={snapVerticesToGrid(nodes.mesh_24_1.geometry)}
          material={materials.Beige}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={snapVerticesToGrid(nodes.mesh_24_2.geometry)}
          material={materials.Material_9_001}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={snapVerticesToGrid(nodes.mesh_24_3.geometry)}
          material={materials.Water}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/models/World/Desert-transformed.glb");
