/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./World/04Desert.glb --transform -o C:\Users\emanu\next-portfolio\public\04Desert.jsx --shadows 
Files: ./World/04Desert.glb [3.37MB] > C:\Users\emanu\next-portfolio\public\04Desert-transformed.glb [189.38KB] (94%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Desert(props) {
  const { nodes, materials } = useGLTF('/models/world/Desert-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.arrows2.geometry} material={materials.colormap} position={[7.5, 0, 39.5]} scale={2} />
      <mesh castShadow receiveShadow geometry={nodes['fence-curved'].geometry} material={materials.colormap2} position={[15.5, 0, 45.25]} rotation={[0, -Math.PI / 2, 0]} scale={2} />
      <mesh castShadow receiveShadow geometry={nodes.Parts_Pile_Small.geometry} material={materials.resource} position={[10.75, 0, 40.25]} />
      <mesh castShadow receiveShadow geometry={nodes['palm-bend'].geometry} material={materials.colormap5} position={[-32.377, 0, 42.659]} rotation={[0, -Math.PI / 6, 0]} />
      <mesh castShadow receiveShadow geometry={nodes['rock-flat'].geometry} material={materials.colormap13} position={[-0.5, 0, 42]} scale={4} />
      <mesh castShadow receiveShadow geometry={nodes.square_rock10.geometry} material={materials.Brown_002} position={[-27, -1, 1]} rotation={[0, Math.PI / 2, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.square_rockToSand10.geometry} material={materials.Material_9_001} position={[-23, -1, 5]} rotation={[0, Math.PI / 2, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.square_sand10.geometry} material={materials.Beige} position={[-47, -1, 17]} />
      <group position={[27, -1, 47]} rotation={[0, Math.PI / 2, 0]}>
        <mesh castShadow receiveShadow geometry={nodes.mesh_8.geometry} material={materials.BrownDark_012} />
        <mesh castShadow receiveShadow geometry={nodes.mesh_8_1.geometry} material={materials.Water_011} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/world/Desert-transformed.glb')
