/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./World/01Forest.glb --transform -o C:\Users\emanu\next-portfolio\public\01Forest.jsx --shadows 
Files: ./World/01Forest.glb [16.38MB] > C:\Users\emanu\next-portfolio\public\01Forest-transformed.glb [898.68KB] (95%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Forest(props) {
  const { nodes, materials } = useGLTF('/models/world/Forest-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.bridge_side_stoneRound.geometry} material={materials.PaletteMaterial001} position={[-2.5, -0.1, 37]} rotation={[0, Math.PI / 2, 0]} scale={2} />
      <mesh castShadow receiveShadow geometry={nodes.waterlily_A.geometry} material={materials.hexagons_medieval} position={[-24, 0, 78]} scale={5} />
      <mesh castShadow receiveShadow geometry={nodes['patch-grass-foliage'].geometry} material={materials.colormap} position={[1.5, 0, 54]} rotation={[0, -Math.PI / 6, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.Tree_2_A_Color1.geometry} material={materials.forest} position={[32.5, 0, 57.5]} />
      <mesh castShadow receiveShadow geometry={nodes['rock-a'].geometry} material={materials.colormap2} position={[-32, 0, 60.5]} scale={5} />
      <mesh castShadow receiveShadow geometry={nodes['flowers-tall'].geometry} material={materials.colormap8} position={[-30.5, 0, 65]} scale={2} />
      <mesh castShadow receiveShadow geometry={nodes.Wood_Log_B.geometry} material={materials.resource} position={[10.85, 0.1, 55.9]} rotation={[0, -Math.PI / 4, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.square_forestToPlain2.geometry} material={materials.Material_7_001} position={[-47, -1, 109]} rotation={[0, Math.PI / 2, 0]} />
    </group>
  )
}

useGLTF.preload('/models/world/Forest-transformed.glb')
