/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\Forest.glb --transform -o C:\Users\emanu\next-portfolio\public\Forest.jsx --shadows -j 
Files: .\Forest.glb [14.65MB] > C:\Users\emanu\next-portfolio\public\Forest-transformed.glb [499.36KB] (97%)
*/

import React from "react";
import { useGLTF } from "@react-three/drei";
import { snapVerticesToGrid } from "@/lib/geometryUtility";

export function Forest(props) {
  const { nodes, materials } = useGLTF("/models/World/Forest-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.waterlily_A.geometry}
        material={materials.hexagons_medieval}
        position={[-24, 0, 78]}
        scale={5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.waterlily_A4.geometry}
        material={materials.hexagons_medieval}
        position={[-20, 0, 73]}
        rotation={[0, -Math.PI / 3, 0]}
        scale={5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.waterlily_A5.geometry}
        material={materials.hexagons_medieval}
        position={[-15, 0, 80]}
        rotation={[0, 0.262, 0]}
        scale={5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.waterlily_A6.geometry}
        material={materials.hexagons_medieval}
        position={[-20, 0, 82]}
        rotation={[-Math.PI, 1.309, -Math.PI]}
        scale={5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.waterlily_A7.geometry}
        material={materials.hexagons_medieval}
        position={[16, 0, 47.5]}
        scale={5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.waterlily_A8.geometry}
        material={materials.hexagons_medieval}
        position={[32.5, 0, 48.5]}
        rotation={[0, -Math.PI / 3, 0]}
        scale={5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.waterlily_A9.geometry}
        material={materials.hexagons_medieval}
        position={[6, 0, 41]}
        rotation={[0, -1.309, 0]}
        scale={5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.waterlily_A10.geometry}
        material={materials.hexagons_medieval}
        position={[-10, 0, 33.5]}
        rotation={[0, -0.262, 0]}
        scale={5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.waterlily_A11.geometry}
        material={materials.hexagons_medieval}
        position={[-18, 0, 19.5]}
        rotation={[0, Math.PI / 4, 0]}
        scale={5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.waterlily_A12.geometry}
        material={materials.hexagons_medieval}
        position={[-12, 0, 10.5]}
        rotation={[0, -0.262, 0]}
        scale={5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.waterlily_B.geometry}
        material={materials.hexagons_medieval}
        position={[-19, 0, 77.5]}
        rotation={[0, -0.262, 0]}
        scale={5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.waterlily_B4.geometry}
        material={materials.hexagons_medieval}
        position={[-15, 0, 74]}
        rotation={[0, -Math.PI / 3, 0]}
        scale={5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.waterlily_B5.geometry}
        material={materials.hexagons_medieval}
        position={[-25, 0, 74]}
        rotation={[-Math.PI, -Math.PI / 4, -Math.PI]}
        scale={5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.waterlily_B6.geometry}
        material={materials.hexagons_medieval}
        position={[-14, 0, 29]}
        rotation={[0, 1.309, 0]}
        scale={5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.waterlily_B7.geometry}
        material={materials.hexagons_medieval}
        position={[-14, 0, 5]}
        rotation={[0, -0.262, 0]}
        scale={5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.waterlily_B8.geometry}
        material={materials.hexagons_medieval}
        position={[2, 0, 37.5]}
        rotation={[0, -0.262, 0]}
        scale={5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.waterlily_B9.geometry}
        material={materials.hexagons_medieval}
        position={[32, 0, 44.5]}
        rotation={[0, -Math.PI / 3, 0]}
        scale={5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.waterplant_A.geometry}
        material={materials.hexagons_medieval}
        position={[-11.5, 0, 75.5]}
        scale={5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.waterplant_C.geometry}
        material={materials.hexagons_medieval}
        position={[-25, 0, 74]}
        scale={5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.waterplant_C4.geometry}
        material={materials.hexagons_medieval}
        position={[-15, 0, 74]}
        scale={5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.waterplant_B.geometry}
        material={materials.hexagons_medieval}
        position={[-19, 0, 77.5]}
        scale={5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["patch-grass-foliage"].geometry}
        material={materials.colormap}
        position={[1.5, 0, 54]}
        rotation={[0, -Math.PI / 6, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["patch-grass-foliage4"].geometry}
        material={materials.colormap}
        position={[-33, 0, 99.5]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["patch-grass-foliage5"].geometry}
        material={materials.colormap}
        position={[26, 0, 93]}
        rotation={[-Math.PI, Math.PI / 4, -Math.PI]}
        scale={1.5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["patch-grass-foliage6"].geometry}
        material={materials.colormap}
        position={[23, 0, 60.5]}
        rotation={[-Math.PI, -Math.PI / 4, -Math.PI]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["patch-grass-foliage8"].geometry}
        material={materials.colormap}
        position={[41, 0, 85]}
        rotation={[-Math.PI, -0.262, -Math.PI]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["patch-grass-foliage10"].geometry}
        material={materials.colormap}
        position={[-15, 0, 38.5]}
        rotation={[0, -0.262, 0]}
        scale={1.75}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["patch-grass-foliage11"].geometry}
        material={materials.colormap}
        position={[-34, 0, 35]}
        rotation={[0, Math.PI / 6, 0]}
        scale={2.25}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["patch-grass-foliage14"].geometry}
        material={materials.colormap}
        position={[-39.5, 0, 67]}
        rotation={[0, Math.PI / 6, 0]}
        scale={2.25}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["patch-grass-foliage15"].geometry}
        material={materials.colormap}
        position={[-34, 0, 35]}
        rotation={[0, Math.PI / 6, 0]}
        scale={2.25}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["patch-grass-foliage16"].geometry}
        material={materials.colormap}
        position={[33.5, 0, 36]}
        rotation={[0, -Math.PI / 6, 0]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["patch-grass-foliage17"].geometry}
        material={materials.colormap}
        position={[-10.5, 0, 67.5]}
        rotation={[0, Math.PI / 4, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["patch-grass-foliage18"].geometry}
        material={materials.colormap}
        position={[-2.5, 0, 89.048]}
        rotation={[0, 0.262, 0]}
        scale={1.5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree_2_A_Color1.geometry}
        material={materials.forest}
        position={[32.5, 0, 57.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree_4_C_Color1.geometry}
        material={materials.forest}
        position={[-5.5, 0, 30.5]}
        rotation={[0, Math.PI / 4, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree_4_C_Color14.geometry}
        material={materials.forest}
        position={[-1, 0, 8]}
        rotation={[-Math.PI, 0, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree_4_C_Color15.geometry}
        material={materials.forest}
        position={[-22.5, 0, 32]}
        rotation={[0, -Math.PI / 6, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree_4_C_Color16.geometry}
        material={materials.forest}
        position={[28, 0, 12]}
        rotation={[0, Math.PI / 6, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree_4_C_Color17.geometry}
        material={materials.forest}
        position={[-41, 0, 22]}
        rotation={[0, Math.PI / 6, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree_4_A_Color1.geometry}
        material={materials.forest}
        position={[-14, 0, 22]}
        rotation={[0, -Math.PI / 4, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree_4_A_Color14.geometry}
        material={materials.forest}
        position={[-17, 0, 11]}
        rotation={[-Math.PI, Math.PI / 6, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree_4_B_Color1.geometry}
        material={materials.forest}
        position={[3, 0, 32.5]}
        rotation={[0, -Math.PI / 4, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree_4_B_Color14.geometry}
        material={materials.forest}
        position={[-7, 0, 41.5]}
        rotation={[0, -Math.PI / 6, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree_4_B_Color15.geometry}
        material={materials.forest}
        position={[6, 0, 8]}
        rotation={[-Math.PI, -Math.PI / 6, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree_4_B_Color16.geometry}
        material={materials.forest}
        position={[-30, 0, 14]}
        rotation={[0, Math.PI / 6, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree_4_B_Color17.geometry}
        material={materials.forest}
        position={[16.5, 0, 9.5]}
        rotation={[0, -Math.PI / 4, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree_1_C_Color1.geometry}
        material={materials.forest}
        position={[1.5, 0, 106]}
        rotation={[0, 0.262, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree_1_C_Color14.geometry}
        material={materials.forest}
        position={[25, 0, 107.5]}
        rotation={[-Math.PI, 0, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree_1_C_Color15.geometry}
        material={materials.forest}
        position={[35.5, 0, 102]}
        rotation={[0, Math.PI / 4, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree_1_C_Color16.geometry}
        material={materials.forest}
        position={[4, 0, 71]}
        rotation={[-Math.PI, -Math.PI / 3, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree_1_C_Color17.geometry}
        material={materials.forest}
        position={[38.5, 0, 77]}
        rotation={[0, 0.262, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree_1_B_Color1.geometry}
        material={materials.forest}
        position={[20.5, 0, 92.5]}
        rotation={[0, -Math.PI / 3, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree_1_B_Color14.geometry}
        material={materials.forest}
        position={[-0.5, 0, 79.5]}
        rotation={[0, -Math.PI / 6, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree_1_B_Color15.geometry}
        material={materials.forest}
        position={[31, 0, 85]}
        rotation={[0, Math.PI / 6, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree_2_D_Color1.geometry}
        material={materials.forest}
        position={[19.5, 0, 45.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree_2_D_Color14.geometry}
        material={materials.forest}
        position={[40, 0, 62]}
        rotation={[0, Math.PI / 6, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree_2_D_Color15.geometry}
        material={materials.forest}
        position={[-4, 0, 61]}
        rotation={[0, -0.262, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree_2_C_Color1.geometry}
        material={materials.forest}
        position={[29.5, 0, 47.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree_2_C_Color14.geometry}
        material={materials.forest}
        position={[30, 0, 26.5]}
        rotation={[0, Math.PI / 4, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree_2_C_Color15.geometry}
        material={materials.forest}
        position={[17, 0, 59.5]}
        rotation={[0, 0.262, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree_2_B_Color1.geometry}
        material={materials.forest}
        position={[24, 0, 46.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree_2_B_Color14.geometry}
        material={materials.forest}
        position={[9, 0, 66]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree_2_B_Color15.geometry}
        material={materials.forest}
        position={[42.5, 0, 41]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree_3_C_Color1.geometry}
        material={materials.forest}
        position={[-10, 0, 90]}
        rotation={[0, -1.309, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree_3_C_Color14.geometry}
        material={materials.forest}
        position={[-29, 0, 86.5]}
        rotation={[0, 0.262, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree_3_C_Color15.geometry}
        material={materials.forest}
        position={[-28, 0, 70]}
        rotation={[-Math.PI, Math.PI / 3, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree_3_C_Color16.geometry}
        material={materials.forest}
        position={[-32, 0, 50.5]}
        rotation={[0, Math.PI / 6, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree_3_C_Color17.geometry}
        material={materials.forest}
        position={[-42.5, 0, 103]}
        rotation={[0, -0.262, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree_3_B_Color1.geometry}
        material={materials.forest}
        position={[-22.5, 0, 89.5]}
        rotation={[0, 0.262, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree_3_B_Color14.geometry}
        material={materials.forest}
        position={[-15, 0, 69]}
        rotation={[0, Math.PI / 6, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree_3_B_Color15.geometry}
        material={materials.forest}
        position={[-34.5, 0, 77.5]}
        rotation={[0, 0.262, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree_3_B_Color16.geometry}
        material={materials.forest}
        position={[-39, 0, 88.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree_1_A_Color1.geometry}
        material={materials.forest}
        position={[7, 0, 91]}
        rotation={[0, -Math.PI / 6, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree_3_A_Color1.geometry}
        material={materials.forest}
        position={[-27.5, 0, 94.5]}
        rotation={[0, -Math.PI / 3, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree_3_A_Color14.geometry}
        material={materials.forest}
        position={[-40, 0, 56.5]}
        rotation={[0, Math.PI / 6, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree_2_E_Color1.geometry}
        material={materials.forest}
        position={[31, 0, 74.5]}
        rotation={[0, 0.262, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree_2_E_Color14.geometry}
        material={materials.forest}
        position={[9.5, 0, 51]}
        rotation={[0, Math.PI / 6, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree_2_E_Color15.geometry}
        material={materials.forest}
        position={[37, 0, 26.5]}
        rotation={[0, Math.PI / 6, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["rock-a"].geometry}
        material={materials.colormap2}
        position={[-32, 0, 60.5]}
        scale={5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["rock-a4"].geometry}
        material={materials.colormap2}
        position={[-25, 0, 33.5]}
        rotation={[0, -Math.PI / 6, 0]}
        scale={5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["rock-a6"].geometry}
        material={materials.colormap2}
        position={[15.5, 0, 17]}
        scale={5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["rock-a7"].geometry}
        material={materials.colormap2}
        position={[28.5, 0, 76.5]}
        rotation={[-Math.PI, 0.262, -Math.PI]}
        scale={5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["rock-a8"].geometry}
        material={materials.colormap2}
        position={[7.5, 0, 106.5]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["rock-a9"].geometry}
        material={materials.colormap2}
        position={[-13.5, 0, 89]}
        rotation={[0, Math.PI / 4, 0]}
        scale={5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["rock-a10"].geometry}
        material={materials.colormap2}
        position={[-28, 0, 106]}
        rotation={[0, Math.PI / 2, 0]}
        scale={5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["rock-a11"].geometry}
        material={materials.colormap2}
        position={[30, 0, 59.5]}
        rotation={[-Math.PI, Math.PI / 4, -Math.PI]}
        scale={5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["rock-a12"].geometry}
        material={materials.colormap2}
        position={[-10, 0, 24.5]}
        rotation={[-Math.PI, -Math.PI / 6, -Math.PI]}
        scale={5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["rock-b"].geometry}
        material={materials.colormap2}
        position={[-32, 0, 23]}
        rotation={[0, -Math.PI / 4, 0]}
        scale={5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["rock-b4"].geometry}
        material={materials.colormap2}
        position={[37, 0, 9]}
        rotation={[-Math.PI, -Math.PI / 6, -Math.PI]}
        scale={5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["rock-b5"].geometry}
        material={materials.colormap2}
        position={[34, 0, 29]}
        rotation={[-Math.PI, -Math.PI / 6, -Math.PI]}
        scale={5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["rock-b6"].geometry}
        material={materials.colormap2}
        position={[33, 0, 90.5]}
        rotation={[-Math.PI, 0.262, -Math.PI]}
        scale={5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["rock-b7"].geometry}
        material={materials.colormap2}
        position={[4, 0, 80.5]}
        rotation={[-Math.PI, 0.262, -Math.PI]}
        scale={5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["rock-c"].geometry}
        material={materials.colormap2}
        position={[0, 0, 72.5]}
        scale={5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["rock-c4"].geometry}
        material={materials.colormap2}
        position={[-3.5, 0, 48.5]}
        rotation={[0, 0.262, 0]}
        scale={5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["rock-c5"].geometry}
        material={materials.colormap2}
        position={[-34, 0, 91.5]}
        rotation={[-Math.PI, -0.262, -Math.PI]}
        scale={5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["rock-c6"].geometry}
        material={materials.colormap2}
        position={[-28.5, 0, 55]}
        rotation={[-Math.PI, -Math.PI / 4, -Math.PI]}
        scale={5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["rock-c7"].geometry}
        material={materials.colormap2}
        position={[-40, 0, 46]}
        rotation={[0, Math.PI / 2, 0]}
        scale={5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["rock-c8"].geometry}
        material={materials.colormap2}
        position={[-23.5, 0, 12.5]}
        rotation={[-Math.PI, Math.PI / 4, -Math.PI]}
        scale={5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["rock-c9"].geometry}
        material={materials.colormap2}
        position={[-7.5, 0, 13.5]}
        rotation={[0, -Math.PI / 6, 0]}
        scale={5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["rock-c10"].geometry}
        material={materials.colormap2}
        position={[4, 0, 23]}
        scale={5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["rock-c11"].geometry}
        material={materials.colormap2}
        position={[44, 0, 102.5]}
        rotation={[0, Math.PI / 6, 0]}
        scale={5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["rock-c12"].geometry}
        material={materials.colormap2}
        position={[44.5, 0, 69.5]}
        rotation={[0, -Math.PI / 3, 0]}
        scale={5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["rock-c13"].geometry}
        material={materials.colormap2}
        position={[44.5, 0, 23.5]}
        rotation={[0, -Math.PI / 4, 0]}
        scale={5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["grass-large"].geometry}
        material={materials.colormap2}
        position={[-6.5, 0, 64.5]}
        scale={3}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["grass-large4"].geometry}
        material={materials.colormap2}
        position={[4, 0, 75]}
        scale={3}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["grass-large5"].geometry}
        material={materials.colormap2}
        position={[5, 0, 95]}
        scale={3}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["grass-large6"].geometry}
        material={materials.colormap2}
        position={[17, 0, 89]}
        scale={3}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["grass-large7"].geometry}
        material={materials.colormap2}
        position={[10.5, 0, 89]}
        scale={3}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["grass-large8"].geometry}
        material={materials.colormap2}
        position={[16, 0, 107.5]}
        scale={3}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["grass-large9"].geometry}
        material={materials.colormap2}
        position={[27.5, 0, 86.5]}
        scale={3}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["grass-large10"].geometry}
        material={materials.colormap2}
        position={[30, 0, 104]}
        scale={3}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["grass-large11"].geometry}
        material={materials.colormap2}
        position={[32.5, 0, 106.5]}
        scale={3}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["grass-large12"].geometry}
        material={materials.colormap2}
        position={[32.5, 0, 103.5]}
        scale={3}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["grass-large13"].geometry}
        material={materials.colormap2}
        position={[39.5, 0, 96.5]}
        scale={3}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["grass-large14"].geometry}
        material={materials.colormap2}
        position={[38.5, 0, 102]}
        scale={3}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["grass-large15"].geometry}
        material={materials.colormap2}
        position={[40.5, 0, 106.5]}
        scale={3}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["grass-large16"].geometry}
        material={materials.colormap2}
        position={[35, 0, 80]}
        scale={3}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["grass-large17"].geometry}
        material={materials.colormap2}
        position={[34, 0, 76.5]}
        scale={3}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["grass-large18"].geometry}
        material={materials.colormap2}
        position={[36, 0, 67.5]}
        scale={3}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["grass-large19"].geometry}
        material={materials.colormap2}
        position={[36, 0, 58]}
        scale={3}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["grass-large20"].geometry}
        material={materials.colormap2}
        position={[38, 0, 61.5]}
        scale={3}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["grass-large21"].geometry}
        material={materials.colormap2}
        position={[33.5, 0, 64]}
        scale={3}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["grass-large22"].geometry}
        material={materials.colormap2}
        position={[27.5, 0, 70]}
        scale={3}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["grass-large23"].geometry}
        material={materials.colormap2}
        position={[26.5, 0, 74]}
        scale={3}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["grass-large24"].geometry}
        material={materials.colormap2}
        position={[16.5, 0, 63.5]}
        scale={3}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["grass-large25"].geometry}
        material={materials.colormap2}
        position={[14, 0, 65]}
        scale={3}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["grass-large26"].geometry}
        material={materials.colormap2}
        position={[19.5, 0, 54.5]}
        scale={3}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["grass-large27"].geometry}
        material={materials.colormap2}
        position={[13, 0, 50]}
        scale={3}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["grass-large28"].geometry}
        material={materials.colormap2}
        position={[6, 0, 46.5]}
        scale={3}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["grass-large29"].geometry}
        material={materials.colormap2}
        position={[2.5, 0, 43]}
        scale={3}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["grass-large30"].geometry}
        material={materials.colormap2}
        position={[-4.5, 0, 42.5]}
        scale={3}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["grass-large31"].geometry}
        material={materials.colormap2}
        position={[-21, 0, 41.5]}
        scale={3}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["grass-large32"].geometry}
        material={materials.colormap2}
        position={[-18, 0, 32]}
        scale={3}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["grass-large33"].geometry}
        material={materials.colormap2}
        position={[-21.5, 0, 36.5]}
        scale={3}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["grass-large34"].geometry}
        material={materials.colormap2}
        position={[-36.5, 0, 50]}
        scale={3}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["grass-large35"].geometry}
        material={materials.colormap2}
        position={[-35, 0, 56]}
        scale={3}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["grass-large36"].geometry}
        material={materials.colormap2}
        position={[-30.5, 0, 68.5]}
        scale={3}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["grass-large37"].geometry}
        material={materials.colormap2}
        position={[-30.5, 0, 75.5]}
        scale={3}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["grass-large38"].geometry}
        material={materials.colormap2}
        position={[-34, 0, 84]}
        scale={3}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["grass-large39"].geometry}
        material={materials.colormap2}
        position={[-39, 0, 78]}
        scale={3}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["grass-large40"].geometry}
        material={materials.colormap2}
        position={[-44.5, 0, 90.5]}
        scale={3}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["grass-large41"].geometry}
        material={materials.colormap2}
        position={[-45, 0, 79]}
        scale={3}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["grass-large43"].geometry}
        material={materials.colormap2}
        position={[-43.5, 0, 59.5]}
        scale={3}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["grass-large44"].geometry}
        material={materials.colormap2}
        position={[-45, 0, 46.5]}
        scale={3}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["grass-large45"].geometry}
        material={materials.colormap2}
        position={[-42, 0, 41]}
        scale={3}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["grass-large46"].geometry}
        material={materials.colormap2}
        position={[-43.5, 0, 30.5]}
        scale={3}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["grass-large47"].geometry}
        material={materials.colormap2}
        position={[-38, 0, 26.5]}
        scale={3}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["grass-large48"].geometry}
        material={materials.colormap2}
        position={[-35, 0, 16]}
        scale={3}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["grass-large49"].geometry}
        material={materials.colormap2}
        position={[-38, 0, 9]}
        scale={3}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["grass-large50"].geometry}
        material={materials.colormap2}
        position={[-27, 0, 22]}
        scale={3}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["grass-large51"].geometry}
        material={materials.colormap2}
        position={[-10, 0, 19]}
        scale={3}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["grass-large53"].geometry}
        material={materials.colormap2}
        position={[-4, 0, 4.5]}
        scale={3}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["grass-large54"].geometry}
        material={materials.colormap2}
        position={[1, 0, 26.5]}
        scale={3}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["grass-large55"].geometry}
        material={materials.colormap2}
        position={[4.5, 0, 16.5]}
        scale={3}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["grass-large56"].geometry}
        material={materials.colormap2}
        position={[6.5, 0, 13]}
        scale={3}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["grass-large57"].geometry}
        material={materials.colormap2}
        position={[11, 0, 5]}
        scale={3}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["grass-large58"].geometry}
        material={materials.colormap2}
        position={[14, 0, 9.5]}
        scale={3}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["grass-large59"].geometry}
        material={materials.colormap2}
        position={[20.5, 0, 5]}
        scale={3}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["grass-large60"].geometry}
        material={materials.colormap2}
        position={[22.5, 0, 9]}
        scale={3}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["grass-large61"].geometry}
        material={materials.colormap2}
        position={[26, 0, 16]}
        scale={3}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["grass-large63"].geometry}
        material={materials.colormap2}
        position={[30.5, 0, 12]}
        scale={3}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["grass-large64"].geometry}
        material={materials.colormap2}
        position={[33, 0, 6]}
        scale={3}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["grass-large65"].geometry}
        material={materials.colormap2}
        position={[33.5, 0, 15]}
        scale={3}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["grass-large66"].geometry}
        material={materials.colormap2}
        position={[40.5, 0, 4.5]}
        scale={3}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["grass-large67"].geometry}
        material={materials.colormap2}
        position={[44, 0, 12]}
        scale={3}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["grass-large68"].geometry}
        material={materials.colormap2}
        position={[41, 0, 28]}
        scale={3}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["grass-large69"].geometry}
        material={materials.colormap2}
        position={[36, 0, 43.5]}
        scale={3}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["grass-large70"].geometry}
        material={materials.colormap2}
        position={[40, 0, 44.5]}
        scale={3}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["grass-large71"].geometry}
        material={materials.colormap2}
        position={[46, 0, 43]}
        scale={3}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["grass-large73"].geometry}
        material={materials.colormap2}
        position={[44.5, 0, 60]}
        scale={3}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["grass-large74"].geometry}
        material={materials.colormap2}
        position={[-24, 0, 64.5]}
        scale={3}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["grass-large75"].geometry}
        material={materials.colormap2}
        position={[-24, 0, 64.5]}
        scale={3}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["grass-large76"].geometry}
        material={materials.colormap2}
        position={[-19.5, 0, 66]}
        scale={3}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["grass-large77"].geometry}
        material={materials.colormap2}
        position={[-19.5, 0, 66]}
        scale={3}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["grass-large78"].geometry}
        material={materials.colormap2}
        position={[-27, 0, 47]}
        scale={3}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["grass-large79"].geometry}
        material={materials.colormap2}
        position={[-27, 0, 47]}
        scale={3}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["grass-large80"].geometry}
        material={materials.colormap2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["tree-trunk"].geometry}
        material={materials.colormap2}
        position={[-7.5, 0, 86]}
        scale={4}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["tree-trunk4"].geometry}
        material={materials.colormap2}
        position={[-5.5, 0, 97]}
        scale={4}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["tree-trunk5"].geometry}
        material={materials.colormap2}
        position={[30, 0, 99]}
        scale={4}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["tree-trunk6"].geometry}
        material={materials.colormap2}
        position={[27.5, 0, 81.5]}
        scale={4}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["tree-trunk7"].geometry}
        material={materials.colormap2}
        position={[27, 0, 54]}
        scale={4}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["tree-trunk8"].geometry}
        material={materials.colormap2}
        position={[27.5, 0, 30.5]}
        scale={4}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["tree-trunk10"].geometry}
        material={materials.colormap2}
        position={[25, 0, 7]}
        scale={4}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["tree-trunk11"].geometry}
        material={materials.colormap2}
        position={[-19.5, 0, 12.5]}
        scale={4}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["tree-trunk12"].geometry}
        material={materials.colormap2}
        position={[-27.5, 0, 28]}
        scale={4}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["tree-trunk13"].geometry}
        material={materials.colormap2}
        position={[-33, 0, 68.5]}
        scale={4}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["tree-trunk14"].geometry}
        material={materials.colormap2}
        position={[-0.5, 0, 59]}
        scale={4}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["tree-trunk15"].geometry}
        material={materials.colormap2}
        position={[-44.5, 0, 23.5]}
        scale={4}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["tree-trunk16"].geometry}
        material={materials.colormap2}
        position={[15, 0, 16.5]}
        scale={4}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["tree-log-small"].geometry}
        material={materials.colormap2}
        position={[-26.5, 0, 99.5]}
        rotation={[0, Math.PI / 6, 0]}
        scale={4}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["tree-log-small4"].geometry}
        material={materials.colormap2}
        position={[12.5, 0, 108.5]}
        rotation={[0, Math.PI / 3, 0]}
        scale={4}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["tree-log-small5"].geometry}
        material={materials.colormap2}
        position={[36.5, 0, 107]}
        rotation={[0, -Math.PI / 4, 0]}
        scale={4}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["tree-log-small6"].geometry}
        material={materials.colormap2}
        position={[26.5, 0, 66.5]}
        rotation={[0, -Math.PI / 4, 0]}
        scale={4}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["tree-log-small7"].geometry}
        material={materials.colormap2}
        position={[27, 0, 25]}
        rotation={[-Math.PI, -Math.PI / 4, -Math.PI]}
        scale={4}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["tree-log-small8"].geometry}
        material={materials.colormap2}
        position={[-24, 0, 20]}
        rotation={[-Math.PI, -Math.PI / 4, -Math.PI]}
        scale={4}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["tree-log-small9"].geometry}
        material={materials.colormap2}
        position={[-37, 0, 86]}
        rotation={[-Math.PI, -Math.PI / 3, -Math.PI]}
        scale={4}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["tree-log-small10"].geometry}
        material={materials.colormap2}
        position={[-36.5, 0, 46]}
        rotation={[0, -1.309, 0]}
        scale={4}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["tree-log-small11"].geometry}
        material={materials.colormap2}
        position={[-37.5, 0, 21.5]}
        rotation={[0, -1.309, 0]}
        scale={4}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Grass_2_D_Color1.geometry}
        material={materials.forest}
        position={[-4.5, 0, 108]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Grass_2_D_Color14.geometry}
        material={materials.forest}
        position={[-33, 0, 107]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Grass_2_D_Color15.geometry}
        material={materials.forest}
        position={[29.5, 0, 55]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Grass_2_D_Color16.geometry}
        material={materials.forest}
        position={[26.5, 0, 34.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Grass_2_D_Color17.geometry}
        material={materials.forest}
        position={[13.5, 0, 4.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Grass_2_D_Color18.geometry}
        material={materials.forest}
        position={[-11.5, 0, 22]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Grass_2_D_Color19.geometry}
        material={materials.forest}
        position={[-9, 0, 42.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Grass_2_D_Color110.geometry}
        material={materials.forest}
        position={[-29, 0, 38.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Grass_2_D_Color111.geometry}
        material={materials.forest}
        position={[-27.5, 0, 17.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Grass_2_D_Color112.geometry}
        material={materials.forest}
        position={[-43.5, 0, 54]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Grass_2_D_Color113.geometry}
        material={materials.forest}
        position={[-46, 0, 75]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Grass_2_D_Color114.geometry}
        material={materials.forest}
        position={[-42, 0, 78]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Grass_2_D_Color115.geometry}
        material={materials.forest}
        position={[-42.5, 0, 86.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Grass_2_D_Color116.geometry}
        material={materials.forest}
        position={[-39, 0, 107]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Grass_2_D_Singlesided_Color1.geometry}
        material={materials.forest}
        position={[-3.5, 0, 95]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Grass_2_D_Singlesided_Color14.geometry}
        material={materials.forest}
        position={[-35.575, 0, 106.72]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Grass_2_D_Singlesided_Color15.geometry}
        material={materials.forest}
        position={[-31.575, 0, 86.22]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Grass_2_D_Singlesided_Color16.geometry}
        material={materials.forest}
        position={[-27.575, 0, 59.72]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Grass_2_D_Singlesided_Color17.geometry}
        material={materials.forest}
        position={[0.425, 0, 67.22]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Grass_2_D_Singlesided_Color18.geometry}
        material={materials.forest}
        position={[20.425, 0, 107.72]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Grass_2_D_Singlesided_Color19.geometry}
        material={materials.forest}
        position={[43.925, 0, 95.22]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Grass_2_D_Singlesided_Color110.geometry}
        material={materials.forest}
        position={[43.925, 0, 75.22]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Grass_2_D_Singlesided_Color111.geometry}
        material={materials.forest}
        position={[41.925, 0, 65.22]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Grass_2_D_Singlesided_Color112.geometry}
        material={materials.forest}
        position={[44.425, 0, 30.72]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Grass_2_D_Singlesided_Color113.geometry}
        material={materials.forest}
        position={[19.425, 0, 17.72]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Grass_2_D_Singlesided_Color114.geometry}
        material={materials.forest}
        position={[-21.075, 0, 7.22]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Grass_2_D_Singlesided_Color115.geometry}
        material={materials.forest}
        position={[-32.575, 0, 4.22]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Grass_2_D_Singlesided_Color116.geometry}
        material={materials.forest}
        position={[-33.575, 0, 11.72]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Grass_2_D_Singlesided_Color117.geometry}
        material={materials.forest}
        position={[-45.075, 0, 37.72]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Grass_2_D_Singlesided_Color118.geometry}
        material={materials.forest}
        position={[-0.575, 0, 49.72]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Grass_2_D_Singlesided_Color119.geometry}
        material={materials.forest}
        position={[0.425, 0, 31.22]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Grass_2_D_Singlesided_Color120.geometry}
        material={materials.forest}
        position={[5.425, 0, 27.72]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Grass_1_C_Color1.geometry}
        material={materials.forest}
        position={[-9.5, 0, 73]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Grass_1_C_Color14.geometry}
        material={materials.forest}
        position={[-20.5, 0, 22]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Grass_1_C_Color15.geometry}
        material={materials.forest}
        position={[-18.5, 0, 7]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Grass_1_C_Color16.geometry}
        material={materials.forest}
        position={[-12.5, 0, 43]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Grass_1_C_Color17.geometry}
        material={materials.forest}
        position={[9, 0, 55]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Grass_1_C_Color18.geometry}
        material={materials.forest}
        position={[21.5, 0, 47]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Grass_1_C_Color19.geometry}
        material={materials.forest}
        position={[23, 0, 45]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Grass_1_C_Color110.geometry}
        material={materials.forest}
        position={[26.5, 0, 48]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Grass_1_C_Color111.geometry}
        material={materials.forest}
        position={[35, 0, 61.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Grass_1_C_Color112.geometry}
        material={materials.forest}
        position={[14, 0, 88.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Grass_1_C_Color113.geometry}
        material={materials.forest}
        position={[-9.5, 0, 63.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Grass_1_C_Singlesided_Color1.geometry}
        material={materials.forest}
        position={[-3, 0, 79.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Grass_1_C_Singlesided_Color14.geometry}
        material={materials.forest}
        position={[-30.5, 0, 92]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Grass_1_D_Color1.geometry}
        material={materials.forest}
        position={[-20, 0, 89]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Grass_1_D_Singlesided_Color1.geometry}
        material={materials.forest}
        position={[-26, 0, 87]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Grass_1_A_Color1.geometry}
        material={materials.forest}
        position={[-30.5, 0, 105.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Grass_2_C_Color1.geometry}
        material={materials.forest}
        position={[-7.703, 0, 29.727]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Grass_2_C_Color14.geometry}
        material={materials.forest}
        position={[-3.703, 0, 22.727]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Grass_2_C_Color15.geometry}
        material={materials.forest}
        position={[-22.703, 0, 67.227]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Grass_2_C_Color16.geometry}
        material={materials.forest}
        position={[-17.203, 0, 90.227]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Grass_2_C_Color17.geometry}
        material={materials.forest}
        position={[-2.203, 0, 101.227]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Grass_2_C_Color18.geometry}
        material={materials.forest}
        position={[18.297, 0, 106.727]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Grass_2_C_Color19.geometry}
        material={materials.forest}
        position={[39.797, 0, 92.227]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Grass_2_C_Color110.geometry}
        material={materials.forest}
        position={[29.797, 0, 88.727]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Grass_2_C_Color111.geometry}
        material={materials.forest}
        position={[36.297, 0, 52.227]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Grass_2_C_Color112.geometry}
        material={materials.forest}
        position={[39.797, 0, 33.727]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Grass_2_C_Color113.geometry}
        material={materials.forest}
        position={[40.797, 0, 13.727]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Grass_2_C_Color114.geometry}
        material={materials.forest}
        position={[40.797, 0, 13.727]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["flowers-tall"].geometry}
        material={materials.colormap8}
        position={[-30.5, 0, 65]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["flowers-tall4"].geometry}
        material={materials.colormap8}
        position={[-26, 0, 57]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["flowers-tall5"].geometry}
        material={materials.colormap8}
        position={[-8, 0, 90]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["flowers-tall6"].geometry}
        material={materials.colormap8}
        position={[6, 0, 72.5]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["flowers-tall7"].geometry}
        material={materials.colormap8}
        position={[5.5, 0, 104.5]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["flowers-tall8"].geometry}
        material={materials.colormap8}
        position={[30, 0, 108]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["flowers-tall9"].geometry}
        material={materials.colormap8}
        position={[34, 0, 85.5]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["flowers-tall10"].geometry}
        material={materials.colormap8}
        position={[35, 0, 54.5]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["flowers-tall11"].geometry}
        material={materials.colormap8}
        position={[37.5, 0, 31.5]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["flowers-tall12"].geometry}
        material={materials.colormap8}
        position={[23.5, 0, 18]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["flowers-tall13"].geometry}
        material={materials.colormap8}
        position={[3, 0, 8.5]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["flowers-tall14"].geometry}
        material={materials.colormap8}
        position={[-7.5, 0, 18.5]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["flowers-tall15"].geometry}
        material={materials.colormap8}
        position={[-20.5, 0, 17]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["flowers-tall16"].geometry}
        material={materials.colormap8}
        position={[-26, 0, 8.5]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["flowers-tall17"].geometry}
        material={materials.colormap8}
        position={[-30, 0, 18]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["flowers-tall18"].geometry}
        material={materials.colormap8}
        position={[-40.5, 0, 34]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["flowers-tall19"].geometry}
        material={materials.colormap8}
        position={[-45.5, 0, 57]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["flowers-tall20"].geometry}
        material={materials.colormap8}
        position={[-44, 0, 17]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["flowers-tall21"].geometry}
        material={materials.colormap8}
        position={[-37, 0, 60]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["flowers-tall22"].geometry}
        material={materials.colormap8}
        position={[-39, 0, 94]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["flowers-tall23"].geometry}
        material={materials.colormap8}
        position={[-32.5, 0, 80.5]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["flowers-tall24"].geometry}
        material={materials.colormap8}
        position={[-4, 0, 71.5]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Group.geometry}
        material={materials.colormap8}
        position={[-25.44, 0, 89.796]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Group4.geometry}
        material={materials.colormap8}
        position={[-31.94, 0, 54.796]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Group5.geometry}
        material={materials.colormap8}
        position={[-30.44, 0, 27.796]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Group6.geometry}
        material={materials.colormap8}
        position={[5.06, 0, 33.796]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Group7.geometry}
        material={materials.colormap8}
        position={[21.06, 0, 44.796]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Group8.geometry}
        material={materials.colormap8}
        position={[25.06, 0, 45.296]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Group9.geometry}
        material={materials.colormap8}
        position={[22.604, 0, 48.28]}
        rotation={[0, Math.PI / 3, 0]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Group10.geometry}
        material={materials.colormap8}
        position={[18.104, 0, 66.28]}
        rotation={[0, Math.PI / 3, 0]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Group11.geometry}
        material={materials.colormap8}
        position={[29.604, 0, 30.28]}
        rotation={[0, Math.PI / 3, 0]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Group12.geometry}
        material={materials.colormap8}
        position={[12.104, 0, 13.28]}
        rotation={[0, Math.PI / 3, 0]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Group13.geometry}
        material={materials.colormap8}
        position={[-17.896, 0, 13.78]}
        rotation={[0, Math.PI / 3, 0]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Group14.geometry}
        material={materials.colormap8}
        position={[-35.396, 0, 27.78]}
        rotation={[0, Math.PI / 3, 0]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Group15.geometry}
        material={materials.colormap8}
        position={[-40.896, 0, 60.28]}
        rotation={[0, Math.PI / 3, 0]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Group16.geometry}
        material={materials.colormap8}
        position={[-36.396, 0, 81.28]}
        rotation={[0, Math.PI / 3, 0]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Group2.geometry}
        material={materials.colormap8}
        position={[-24.819, 0, 90.429]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Group22.geometry}
        material={materials.colormap8}
        position={[-31.319, 0, 55.429]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Group23.geometry}
        material={materials.colormap8}
        position={[-29.819, 0, 28.429]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Group24.geometry}
        material={materials.colormap8}
        position={[5.681, 0, 34.429]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Group25.geometry}
        material={materials.colormap8}
        position={[21.681, 0, 45.429]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Group26.geometry}
        material={materials.colormap8}
        position={[25.681, 0, 45.929]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Group27.geometry}
        material={materials.colormap8}
        position={[23.462, 0, 48.057]}
        rotation={[0, Math.PI / 3, 0]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Group28.geometry}
        material={materials.colormap8}
        position={[18.962, 0, 66.057]}
        rotation={[0, Math.PI / 3, 0]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Group29.geometry}
        material={materials.colormap8}
        position={[30.462, 0, 30.057]}
        rotation={[0, Math.PI / 3, 0]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Group210.geometry}
        material={materials.colormap8}
        position={[12.962, 0, 13.057]}
        rotation={[0, Math.PI / 3, 0]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Group211.geometry}
        material={materials.colormap8}
        position={[-17.038, 0, 13.557]}
        rotation={[0, Math.PI / 3, 0]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Group212.geometry}
        material={materials.colormap8}
        position={[-34.538, 0, 27.557]}
        rotation={[0, Math.PI / 3, 0]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Group213.geometry}
        material={materials.colormap8}
        position={[-40.038, 0, 60.057]}
        rotation={[0, Math.PI / 3, 0]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Group214.geometry}
        material={materials.colormap8}
        position={[-35.538, 0, 81.057]}
        rotation={[0, Math.PI / 3, 0]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Group3.geometry}
        material={materials.colormap8}
        position={[-24.582, 0, 89.574]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Group32.geometry}
        material={materials.colormap8}
        position={[-31.082, 0, 54.574]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Group33.geometry}
        material={materials.colormap8}
        position={[-29.582, 0, 27.574]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Group34.geometry}
        material={materials.colormap8}
        position={[5.918, 0, 33.574]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Group35.geometry}
        material={materials.colormap8}
        position={[21.918, 0, 44.574]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Group36.geometry}
        material={materials.colormap8}
        position={[25.918, 0, 45.074]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Group37.geometry}
        material={materials.colormap8}
        position={[22.84, 0, 47.425]}
        rotation={[0, Math.PI / 3, 0]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Group38.geometry}
        material={materials.colormap8}
        position={[18.34, 0, 65.425]}
        rotation={[0, Math.PI / 3, 0]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Group39.geometry}
        material={materials.colormap8}
        position={[29.84, 0, 29.425]}
        rotation={[0, Math.PI / 3, 0]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Group310.geometry}
        material={materials.colormap8}
        position={[12.34, 0, 12.425]}
        rotation={[0, Math.PI / 3, 0]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Group311.geometry}
        material={materials.colormap8}
        position={[-17.66, 0, 12.925]}
        rotation={[0, Math.PI / 3, 0]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Group312.geometry}
        material={materials.colormap8}
        position={[-35.16, 0, 26.925]}
        rotation={[0, Math.PI / 3, 0]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Group313.geometry}
        material={materials.colormap8}
        position={[-40.66, 0, 59.425]}
        rotation={[0, Math.PI / 3, 0]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Group314.geometry}
        material={materials.colormap8}
        position={[-36.16, 0, 80.425]}
        rotation={[0, Math.PI / 3, 0]}
        scale={2}
      />
      <group position={[-27, -1, 75]} rotation={[0, Math.PI / 2, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={snapVerticesToGrid(nodes.mesh_38.geometry)}
          material={materials.Water_001}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={snapVerticesToGrid(nodes.mesh_38_1.geometry)}
          material={materials.Green_001}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={snapVerticesToGrid(nodes.mesh_38_2.geometry)}
          material={materials.Material_7_001}
        />
      </group>
      <group
        position={[-2.5, -0.1, 37]}
        rotation={[0, Math.PI / 2, 0]}
        scale={2}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_39.geometry}
          material={materials.stoneDark}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_39_1.geometry}
          material={materials.stone}
        />
      </group>
      <group position={[10, 2, 16]} rotation={[0, 0.262, 0]} scale={4}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_40.geometry}
          material={materials.colormap16}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_40_1.geometry}
          material={materials.colormap17}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Group18.geometry}
        material={materials.colormap17}
        position={[8.66, 0, 94.297]}
        scale={2}
      />
      <group position={[12.6, 0, 57.65]} scale={4}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_42.geometry}
          material={materials.colormap16}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_42_1.geometry}
          material={materials.resource}
        />
      </group>
      <group position={[-5, 0, 77.75]} rotation={[0, -0.262, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_43.geometry}
          material={materials.colormap17}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_43_1.geometry}
          material={materials.colormap16}
        />
      </group>
      <group position={[-27, 0, 40.75]} rotation={[0, -Math.PI / 3, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_43.geometry}
          material={materials.colormap17}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_43_1.geometry}
          material={materials.colormap16}
        />
      </group>
      <group position={[22.125, 0, 14.25]} rotation={[0, Math.PI / 2, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_43.geometry}
          material={materials.colormap17}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_43_1.geometry}
          material={materials.colormap16}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/models/World/Forest-transformed.glb");
