/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\Ocean.glb --transform -o C:\Users\emanu\next-portfolio\public\Ocean.jsx --shadows -j 
Files: .\Ocean.glb [2.82MB] > C:\Users\emanu\next-portfolio\public\Ocean-transformed.glb [100.53KB] (96%)
*/

import React from "react";
import { useGLTF } from "@react-three/drei";
import { snapVerticesToGrid } from "@/lib/geometryUtility";

export function Ocean(props) {
  const { nodes, materials } = useGLTF("/models/World/Ocean-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["cargo-pile-b"].geometry}
        material={materials.colormap}
        position={[-11.5, 0, 89.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["cargo-pile-b4"].geometry}
        material={materials.colormap}
        position={[19, 0, 57.5]}
        rotation={[0, -Math.PI / 3, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["cargo-pile-b5"].geometry}
        material={materials.colormap}
        position={[-25, 0, 36.5]}
        rotation={[0, -Math.PI / 6, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["cargo-pile-b6"].geometry}
        material={materials.colormap}
        position={[-34.5, 0, 16.5]}
        rotation={[0, -Math.PI / 3, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["cargo-pile-b7"].geometry}
        material={materials.colormap}
        position={[-38.5, 0, 69.5]}
        rotation={[0, -Math.PI / 4, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["cargo-pile-b8"].geometry}
        material={materials.colormap}
        position={[-38.5, 0, 142]}
        rotation={[0, -0.262, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["cargo-pile-b9"].geometry}
        material={materials.colormap}
        position={[40, 0, 87]}
        rotation={[0, -Math.PI / 6, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["cargo-pile-a"].geometry}
        material={materials.colormap}
        position={[-3.324, 0, 24.326]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["cargo-pile-a4"].geometry}
        material={materials.colormap}
        position={[38.676, 0, 15.826]}
        rotation={[0, 0.262, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["cargo-pile-a5"].geometry}
        material={materials.colormap}
        position={[35.676, 0, 44.326]}
        rotation={[0, Math.PI / 6, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["cargo-pile-a6"].geometry}
        material={materials.colormap}
        position={[28.676, 0, 113.327]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["cargo-pile-a7"].geometry}
        material={materials.colormap}
        position={[38.176, 0, 139.327]}
        rotation={[0, Math.PI / 6, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["cargo-pile-a8"].geometry}
        material={materials.colormap}
        position={[-41.324, 0, 116.827]}
        rotation={[0, Math.PI / 6, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["rocks-b"].geometry}
        material={materials.colormap3}
        position={[6.5, 0, 60]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["rocks-b4"].geometry}
        material={materials.colormap3}
        position={[-38, 0, 41]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["rocks-c"].geometry}
        material={materials.colormap3}
        position={[25, 0, 11]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["rocks-c2"].geometry}
        material={materials.colormap3}
        position={[15, 0, 112.5]}
        rotation={[0, -1.309, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["rocks-c5"].geometry}
        material={materials.colormap3}
        position={[37, 0, 120]}
        rotation={[0, Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["rocks-c8"].geometry}
        material={materials.colormap3}
        position={[-31.5, 0, 90]}
        rotation={[0, -Math.PI / 6, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["rocks-c9"].geometry}
        material={materials.colormap3}
        position={[-20.5, 0, 141.5]}
        rotation={[-Math.PI, -Math.PI / 6, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["rocks-c10"].geometry}
        material={materials.colormap3}
        position={[-20.5, 0, 21]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["rocks-a"].geometry}
        material={materials.colormap3}
        position={[37, 0, 58]}
        rotation={[0, Math.PI / 3, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["rocks-a4"].geometry}
        material={materials.colormap3}
        position={[42.5, 0, 29.5]}
        rotation={[0, Math.PI / 4, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["palm-detailed-bend"].geometry}
        material={materials.colormap3}
        position={[-27.5, 0, 58.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["palm-detailed-bend4"].geometry}
        material={materials.colormap3}
        position={[20.5, 0, 41]}
        rotation={[0, Math.PI / 4, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["palm-detailed-bend5"].geometry}
        material={materials.colormap3}
        position={[25.5, 0, 73.5]}
        rotation={[0, -Math.PI / 3, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["palm-detailed-bend6"].geometry}
        material={materials.colormap3}
        position={[5, 0, 86.5]}
        rotation={[0, Math.PI / 6, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["palm-detailed-bend7"].geometry}
        material={materials.colormap3}
        position={[12.5, 0, 128.5]}
        rotation={[0, -Math.PI / 6, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["palm-detailed-bend9"].geometry}
        material={materials.colormap3}
        position={[-4.5, 0, 148.5]}
        rotation={[0, -Math.PI / 6, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["palm-detailed-bend10"].geometry}
        material={materials.colormap3}
        position={[-20, 0, 101.5]}
        rotation={[-Math.PI, -Math.PI / 3, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["palm-straight"].geometry}
        material={materials.colormap3}
        position={[-11.5, 0, 45.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["palm-straight3"].geometry}
        material={materials.colormap3}
        position={[28, 0, 93.5]}
        rotation={[0, -0.262, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["palm-straight6"].geometry}
        material={materials.colormap3}
        position={[-28, 0, 116]}
        rotation={[0, -0.262, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["palm-straight7"].geometry}
        material={materials.colormap3}
        position={[5, 0, 30]}
        rotation={[0, Math.PI / 6, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["palm-detailed-straight"].geometry}
        material={materials.colormap3}
        position={[-12.5, 0, 73]}
        rotation={[0, 0.262, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["palm-detailed-straight2"].geometry}
        material={materials.colormap3}
        position={[28.5, 0, 24.5]}
        rotation={[0, -Math.PI / 3, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["palm-detailed-straight5"].geometry}
        material={materials.colormap3}
        position={[-17, 0, 5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["structure-floor3"].geometry}
        material={materials.colormap9}
        position={[-8.5, -1.685, 9.1]}
        rotation={[-0.262, Math.PI / 2, 0]}
        scale={4}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.buoy.geometry}
        material={materials.colormap}
        position={[-29, 0, 27]}
        rotation={[0, Math.PI / 6, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.buoy4.geometry}
        material={materials.colormap}
        position={[-13.5, 0, 34.5]}
        rotation={[0, Math.PI / 6, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.buoy5.geometry}
        material={materials.colormap}
        position={[12, 0, 68.5]}
        rotation={[0, Math.PI / 6, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.buoy6.geometry}
        material={materials.colormap}
        position={[-23, 0, 82]}
        rotation={[0, -Math.PI / 6, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.buoy8.geometry}
        material={materials.colormap}
        position={[11, 0, 102]}
        rotation={[0, -Math.PI / 6, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.buoy9.geometry}
        material={materials.colormap}
        position={[-13, 0, 136.5]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.buoy10.geometry}
        material={materials.colormap}
        position={[-4.5, 0, 99]}
        rotation={[0, -Math.PI / 6, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["boat-row-small"].geometry}
        material={materials.colormap3}
        position={[6.916, 0, 5.541]}
        rotation={[0, 0.541, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["boat-row-small4"].geometry}
        material={materials.colormap3}
        position={[-15.5, 0, 128]}
        rotation={[0, Math.PI / 6, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.paddles.geometry}
        material={materials.colormap3}
        position={[6.826, 0.056, 5.391]}
        rotation={[0, 0.541, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.paddles2.geometry}
        material={materials.colormap3}
        position={[-15.588, 0.056, 127.848]}
        rotation={[0, Math.PI / 6, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["boat-speed-b"].geometry}
        material={materials.colormap}
        position={[20, 0, 102]}
        rotation={[0, -Math.PI / 6, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["boat-speed-c"].geometry}
        material={materials.colormap}
        position={[-28, 0, 140.5]}
        rotation={[-Math.PI, Math.PI / 3, -Math.PI]}
      />
      <group position={[-39, -1, 1]}>
        <mesh
          castShadow
          receiveShadow
          geometry={snapVerticesToGrid(nodes.mesh_14.geometry)}
          material={materials.Beige}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={snapVerticesToGrid(nodes.mesh_14_1.geometry)}
          material={materials.Water}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={snapVerticesToGrid(nodes.mesh_14_2.geometry, 0)}
          material={materials.Material_9_001}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={snapVerticesToGrid(nodes.mesh_14_3.geometry, 0)}
          material={materials.Material_4}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/models/World/Ocean-transformed.glb");
