/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./World/05Ocean.glb --transform -o C:\Users\emanu\next-portfolio\public\05Ocean.jsx --shadows 
Files: ./World/05Ocean.glb [6.02MB] > C:\Users\emanu\next-portfolio\public\05Ocean-transformed.glb [230.36KB] (96%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Ocean(props) {
  const { nodes, materials } = useGLTF('/models/world/Ocean-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes['cargo-pile-b'].geometry} material={materials.colormap} position={[-11.5, 0, 89.5]} />
      <mesh castShadow receiveShadow geometry={nodes['rocks-b'].geometry} material={materials.colormap3} position={[6.5, 0, 60]} />
      <mesh castShadow receiveShadow geometry={nodes['structure-floor'].geometry} material={materials.colormap9} position={[-8.5, -1.5, 10.5]} rotation={[0, Math.PI / 2, 0]} scale={4} />
      <mesh castShadow receiveShadow geometry={nodes.square_plain10.geometry} material={materials.Material_4} position={[-27, -1, 119]} />
      <mesh castShadow receiveShadow geometry={nodes.square_sand10.geometry} material={materials.Beige_001} position={[-23, -1, 3]} />
      <group position={[-29, -1, 3]} rotation={[0, Math.PI / 2, 0]}>
        <mesh castShadow receiveShadow geometry={nodes.mesh_2.geometry} material={materials.BrownDark_013} />
        <mesh castShadow receiveShadow geometry={nodes.mesh_2_1.geometry} material={materials.Water_012} />
      </group>
      <mesh castShadow receiveShadow geometry={nodes.square_sandToPlain10.geometry} material={materials.Material_9_001} position={[-25, -1, 103]} rotation={[-Math.PI, 0, -Math.PI]} />
    </group>
  )
}

useGLTF.preload('/models/world/Ocean-transformed.glb')
