/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\Plains.glb --transform -o C:\Users\emanu\next-portfolio\public\Plains.jsx --shadows -j 
Files: .\Plains.glb [18.5MB] > C:\Users\emanu\next-portfolio\public\Plains-transformed.glb [1.44MB] (92%)
*/

import React from "react";
import { useGLTF } from "@react-three/drei";
import { snapVerticesToGrid } from "@/lib/geometryUtility";

export function Plains(props) {
  const { nodes, materials } = useGLTF("/models/World/Plains-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <group position={[12, -1.75, 84]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_123.geometry}
          material={materials.Color_Palette_015}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_123_1.geometry}
          material={materials.colormap5}
        />
      </group>
      <group position={[-13, 0.25, 72]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_124.geometry}
          material={materials.Color_Palette_015}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_124_1.geometry}
          material={materials.colormap5}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Farm_House_Barn_01.geometry}
        material={materials.Color_Palette_01}
        position={[-23, 0, 22]}
        rotation={[0, Math.PI / 6, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.House_Farm_Barn_01_Door_A.geometry}
        material={materials.Color_Palette_01}
        position={[-23.1, 1.307, 25.7]}
        rotation={[0, Math.PI / 6, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.House_Farm_Barn_01_Door_B.geometry}
        material={materials.Color_Palette_01}
        position={[-19.723, 1.307, 23.75]}
        rotation={[0, Math.PI / 6, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Farm_House_Silo_01.geometry}
        material={materials.Color_Palette_01}
        position={[-19, 0, 11.9]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Props_Bucket_01.geometry}
        material={materials.Color_Palette_01}
        position={[-19, 0, 24]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Props_Bucket_013.geometry}
        material={materials.Color_Palette_01}
        position={[-10.5, 0, 73]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Props_Bucket_014.geometry}
        material={materials.Color_Palette_01}
        position={[4.5, 0, 90.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Props_Bucket_015.geometry}
        material={materials.Color_Palette_01}
        position={[2.5, 0, 36]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Props_Crate_01.geometry}
        material={materials.Color_Palette_01}
        position={[-19.5, 0, 14.9]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Props_Mailbox_01.geometry}
        material={materials.Color_Palette_01}
        position={[-15.5, 0, 23]}
        rotation={[-Math.PI, 0, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Props_Tree_Stump_01.geometry}
        material={materials.Color_Palette_01}
        position={[-17, 0, 26]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Props_Wooden_Barrel_01.geometry}
        material={materials.Color_Palette_01}
        position={[-25.5, 0, 26.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Props_Wooden_Barrel_014.geometry}
        material={materials.Color_Palette_01}
        position={[-26, 0, 25]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Props_Wooden_Barrel_015.geometry}
        material={materials.Color_Palette_01}
        position={[5, 0, 47]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Props_Wooden_Barrel_016.geometry}
        material={materials.Color_Palette_01}
        position={[-10, 0, 63]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Props_Wooden_Barrel_017.geometry}
        material={materials.Color_Palette_01}
        position={[4, 0, 81]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["grass-patch11"].geometry}
        material={materials.colormap7}
        position={[-19.939, 0, 27.913]}
        rotation={[0, -Math.PI / 4, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["grass-patch12"].geometry}
        material={materials.colormap7}
        position={[-6.439, 0, 27.913]}
        rotation={[Math.PI, -1.309, Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["grass-patch13"].geometry}
        material={materials.colormap7}
        position={[-4.439, 0, 11.913]}
        rotation={[0, -1.309, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["grass-patch14"].geometry}
        material={materials.colormap7}
        position={[4.061, 0, 5.913]}
        rotation={[-Math.PI, -Math.PI / 6, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["grass-patch15"].geometry}
        material={materials.colormap7}
        position={[17.061, 0, 3.413]}
        rotation={[-Math.PI, -Math.PI / 3, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["grass-patch16"].geometry}
        material={materials.colormap7}
        position={[26.061, 0, 3.413]}
        rotation={[-Math.PI, 0, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["grass-patch17"].geometry}
        material={materials.colormap7}
        position={[36.061, 0, 6.413]}
        rotation={[-Math.PI, 1.309, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["grass-patch18"].geometry}
        material={materials.colormap7}
        position={[40.061, 0, 19.413]}
        rotation={[0, 0.262, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["grass-patch19"].geometry}
        material={materials.colormap7}
        position={[28.561, 0, 16.913]}
        rotation={[0, -Math.PI / 4, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["grass-patch20"].geometry}
        material={materials.colormap7}
        position={[31.561, 0, 31.913]}
        rotation={[Math.PI, -1.309, Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["grass-patch"].geometry}
        material={materials.colormap7}
        position={[-35.439, 0, 91.913]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["grass-patch22"].geometry}
        material={materials.colormap7}
        position={[25.061, 0, 41.913]}
        rotation={[-Math.PI, -Math.PI / 6, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["grass-patch23"].geometry}
        material={materials.colormap7}
        position={[8.561, 0, 50.913]}
        rotation={[-Math.PI, -0.262, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["grass-patch24"].geometry}
        material={materials.colormap7}
        position={[27.561, 0, 56.413]}
        rotation={[-Math.PI, Math.PI / 4, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["grass-patch25"].geometry}
        material={materials.colormap7}
        position={[36.061, 0, 62.413]}
        rotation={[0, 1.309, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["grass-patch26"].geometry}
        material={materials.colormap7}
        position={[39.561, 0, 42.913]}
        rotation={[0, Math.PI / 6, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["grass-patch27"].geometry}
        material={materials.colormap7}
        position={[45.061, 0, 35.913]}
        rotation={[0, -Math.PI / 6, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["grass-patch28"].geometry}
        material={materials.colormap7}
        position={[44.561, 0, 52.413]}
        rotation={[0, -1.309, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["grass-patch29"].geometry}
        material={materials.colormap7}
        position={[35.561, 0, 77.913]}
        rotation={[Math.PI, -1.309, Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["grass-patch30"].geometry}
        material={materials.colormap7}
        position={[28.061, 0, 74.913]}
        rotation={[-Math.PI, -Math.PI / 6, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["grass-patch31"].geometry}
        material={materials.colormap7}
        position={[17.561, 0, 75.413]}
        rotation={[Math.PI, -1.309, Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["grass-patch4"].geometry}
        material={materials.colormap7}
        position={[-30.439, 0, 71.913]}
        rotation={[0, -Math.PI / 6, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["grass-patch32"].geometry}
        material={materials.colormap7}
        position={[9.061, 0, 75.413]}
        rotation={[-Math.PI, -Math.PI / 4, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["grass-patch33"].geometry}
        material={materials.colormap7}
        position={[4.561, 0, 63.413]}
        rotation={[Math.PI, -1.309, Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["grass-patch34"].geometry}
        material={materials.colormap7}
        position={[-6.439, 0, 60.413]}
        rotation={[0, -Math.PI / 3, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["grass-patch35"].geometry}
        material={materials.colormap7}
        position={[-18.939, 0, 56.413]}
        rotation={[0, -Math.PI / 4, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["grass-patch36"].geometry}
        material={materials.colormap7}
        position={[-22.939, 0, 75.913]}
        rotation={[0, -Math.PI / 4, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["grass-patch38"].geometry}
        material={materials.colormap7}
        position={[27.561, 0, 88.913]}
        rotation={[0, -0.262, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["grass-patch39"].geometry}
        material={materials.colormap7}
        position={[36.061, 0, 91.413]}
        rotation={[0, 0.262, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["grass-patch21"].geometry}
        material={materials.colormap7}
        position={[21.061, 0, 27.413]}
        rotation={[Math.PI, -1.309, Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["grass-patch5"].geometry}
        material={materials.colormap7}
        position={[-37.939, 0, 73.413]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["grass-patch6"].geometry}
        material={materials.colormap7}
        position={[-37.939, 0, 58.913]}
        rotation={[0, Math.PI / 3, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["grass-patch7"].geometry}
        material={materials.colormap7}
        position={[-34.439, 0, 46.413]}
        rotation={[0, -0.262, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["grass-patch8"].geometry}
        material={materials.colormap7}
        position={[-37.439, 0, 32.913]}
        rotation={[0, -Math.PI / 3, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["grass-patch9"].geometry}
        material={materials.colormap7}
        position={[-43.439, 0, 28.913]}
        rotation={[0, -0.262, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["grass-patch10"].geometry}
        material={materials.colormap7}
        position={[-42.939, 0, 6.913]}
        rotation={[0, -1.309, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["grass-plant11"].geometry}
        material={materials.colormap7}
        position={[38, 0, 69.5]}
        rotation={[0, -Math.PI / 4, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["grass-plant12"].geometry}
        material={materials.colormap7}
        position={[44, 0, 67]}
        rotation={[0, -Math.PI / 4, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["grass-plant13"].geometry}
        material={materials.colormap7}
        position={[44, 0, 45]}
        rotation={[0, -0.262, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["grass-plant14"].geometry}
        material={materials.colormap7}
        position={[34, 0, 43.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["grass-plant15"].geometry}
        material={materials.colormap7}
        position={[45, 0, 26]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["grass-plant16"].geometry}
        material={materials.colormap7}
        position={[40.5, 0, 36]}
        rotation={[0, -Math.PI / 6, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["grass-plant17"].geometry}
        material={materials.colormap7}
        position={[27.5, 0, 33]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["grass-plant18"].geometry}
        material={materials.colormap7}
        position={[32, 0, 13.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["grass-plant19"].geometry}
        material={materials.colormap7}
        position={[-27.5, 0, 30]}
        rotation={[0, 0.262, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["grass-plant"].geometry}
        material={materials.colormap7}
        position={[-24.5, 0, 56.5]}
        rotation={[0, 0.262, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["grass-plant4"].geometry}
        material={materials.colormap7}
        position={[-30, 0, 39.5]}
        rotation={[0, -0.262, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["grass-plant5"].geometry}
        material={materials.colormap7}
        position={[-45, 0, 46.5]}
        rotation={[0, -0.262, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["grass-plant6"].geometry}
        material={materials.colormap7}
        position={[-44.5, 0, 60.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["grass-plant7"].geometry}
        material={materials.colormap7}
        position={[-43, 0, 73]}
        rotation={[0, -Math.PI / 6, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["grass-plant8"].geometry}
        material={materials.colormap7}
        position={[-43.5, 0, 91.5]}
        rotation={[0, -Math.PI / 6, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["grass-plant9"].geometry}
        material={materials.colormap7}
        position={[4.5, 0, 94.5]}
        rotation={[0, -Math.PI / 6, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["grass-plant10"].geometry}
        material={materials.colormap7}
        position={[32.5, 0, 88.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Farm_Crop_Tree_029.geometry}
        material={materials.Color_Palette_015}
        position={[32.5, 0, 22]}
        rotation={[-Math.PI, 1.309, -Math.PI]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Farm_Crop_Tree_0214.geometry}
        material={materials.Color_Palette_015}
        position={[41.5, 0, 11.5]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Farm_Crop_Tree_0210.geometry}
        material={materials.Color_Palette_015}
        position={[35, 0, 38]}
        rotation={[0, -Math.PI / 3, 0]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Farm_Crop_Tree_0212.geometry}
        material={materials.Color_Palette_015}
        position={[-34.5, 0, 40]}
        rotation={[-Math.PI, -0.262, -Math.PI]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Farm_Crop_Tree_026.geometry}
        material={materials.Color_Palette_015}
        position={[-39.5, 0, 15]}
        rotation={[0, -0.262, 0]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Farm_Crop_Tree_0211.geometry}
        material={materials.Color_Palette_015}
        position={[22.5, 0, 35]}
        rotation={[-Math.PI, -Math.PI / 3, -Math.PI]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Farm_Crop_Tree_0213.geometry}
        material={materials.Color_Palette_015}
        position={[-41, 0, 53.5]}
        rotation={[Math.PI, -1.309, Math.PI]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Farm_Crop_Tree_02.geometry}
        material={materials.Color_Palette_015}
        position={[-9, 0, 17.5]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Farm_Crop_Tree_022.geometry}
        material={materials.Color_Palette_015}
        position={[-0.5, 0, 12.5]}
        rotation={[-Math.PI, -0.262, -Math.PI]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Farm_Crop_Tree_023.geometry}
        material={materials.Color_Palette_015}
        position={[2.5, 0, 23.5]}
        rotation={[-Math.PI, -Math.PI / 6, -Math.PI]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Farm_Crop_Tree_0215.geometry}
        material={materials.Color_Palette_015}
        position={[-29.5, 0, 9.5]}
        rotation={[0, Math.PI / 2, 0]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Farm_Crop_Tree_024.geometry}
        material={materials.Color_Palette_015}
        position={[0, 0, 46.5]}
        rotation={[-Math.PI, -Math.PI / 6, -Math.PI]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Farm_Crop_Tree_025.geometry}
        material={materials.Color_Palette_015}
        position={[-32, 0, 26]}
        rotation={[Math.PI, -1.309, Math.PI]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Farm_Crop_Tree_027.geometry}
        material={materials.Color_Palette_015}
        position={[29.5, 0, 8]}
        rotation={[-Math.PI, Math.PI / 3, -Math.PI]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Farm_Crop_Tree_028.geometry}
        material={materials.Color_Palette_015}
        position={[9.5, 0, 2.5]}
        rotation={[-Math.PI, -Math.PI / 3, -Math.PI]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Group.geometry}
        material={materials.colormap2}
        position={[-5.44, 0, 81.297]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Group15.geometry}
        material={materials.colormap2}
        position={[10.517, 0, 28.044]}
        rotation={[0, Math.PI / 6, 0]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Group11.geometry}
        material={materials.colormap2}
        position={[-5.978, 0, 32.917]}
        rotation={[0, 0.262, 0]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Group12.geometry}
        material={materials.colormap2}
        position={[-27.956, 0, 44.983]}
        rotation={[-Math.PI, Math.PI / 3, -Math.PI]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Group13.geometry}
        material={materials.colormap2}
        position={[-11.583, 0, 7.478]}
        rotation={[-Math.PI, 1.309, -Math.PI]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Group4.geometry}
        material={materials.colormap2}
        position={[-3.455, 0, 92.668]}
        rotation={[0, Math.PI / 4, 0]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Group5.geometry}
        material={materials.colormap2}
        position={[4.517, 0, 70.044]}
        rotation={[0, Math.PI / 6, 0]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Group6.geometry}
        material={materials.colormap2}
        position={[5.017, 0, 56.544]}
        rotation={[0, Math.PI / 6, 0]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Group7.geometry}
        material={materials.colormap2}
        position={[15.545, 0, 51.168]}
        rotation={[0, Math.PI / 4, 0]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Group8.geometry}
        material={materials.colormap2}
        position={[17.045, 0, 52.168]}
        rotation={[0, Math.PI / 4, 0]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Group9.geometry}
        material={materials.colormap2}
        position={[17.017, 0, 50.044]}
        rotation={[0, Math.PI / 6, 0]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Group10.geometry}
        material={materials.colormap2}
        position={[8.517, 0, 28.044]}
        rotation={[0, Math.PI / 6, 0]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Group14.geometry}
        material={materials.colormap2}
        position={[9.517, 0, 29.544]}
        rotation={[0, Math.PI / 6, 0]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Group2.geometry}
        material={materials.colormap2}
        position={[-4.819, 0, 81.929]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Group213.geometry}
        material={materials.colormap2}
        position={[11.371, 0, 28.281]}
        rotation={[0, Math.PI / 6, 0]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Group29.geometry}
        material={materials.colormap2}
        position={[-5.214, 0, 33.367]}
        rotation={[0, 0.262, 0]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Group210.geometry}
        material={materials.colormap2}
        position={[-27.719, 0, 44.129]}
        rotation={[-Math.PI, Math.PI / 3, -Math.PI]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Group211.geometry}
        material={materials.colormap2}
        position={[-11.133, 0, 6.714]}
        rotation={[-Math.PI, 1.309, -Math.PI]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Group22.geometry}
        material={materials.colormap2}
        position={[-2.569, 0, 92.675]}
        rotation={[0, Math.PI / 4, 0]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Group23.geometry}
        material={materials.colormap2}
        position={[5.371, 0, 70.281]}
        rotation={[0, Math.PI / 6, 0]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Group24.geometry}
        material={materials.colormap2}
        position={[5.871, 0, 56.781]}
        rotation={[0, Math.PI / 6, 0]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Group25.geometry}
        material={materials.colormap2}
        position={[16.431, 0, 51.175]}
        rotation={[0, Math.PI / 4, 0]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Group26.geometry}
        material={materials.colormap2}
        position={[17.931, 0, 52.175]}
        rotation={[0, Math.PI / 4, 0]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Group27.geometry}
        material={materials.colormap2}
        position={[17.871, 0, 50.281]}
        rotation={[0, Math.PI / 6, 0]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Group28.geometry}
        material={materials.colormap2}
        position={[9.371, 0, 28.281]}
        rotation={[0, Math.PI / 6, 0]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Group212.geometry}
        material={materials.colormap2}
        position={[10.371, 0, 29.781]}
        rotation={[0, Math.PI / 6, 0]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Group3.geometry}
        material={materials.colormap2}
        position={[-4.582, 0, 81.074]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Group313.geometry}
        material={materials.colormap2}
        position={[11.149, 0, 27.422]}
        rotation={[0, Math.PI / 6, 0]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Group39.geometry}
        material={materials.colormap2}
        position={[-5.206, 0, 32.481]}
        rotation={[0, 0.262, 0]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Group310.geometry}
        material={materials.colormap2}
        position={[-28.578, 0, 44.351]}
        rotation={[-Math.PI, Math.PI / 3, -Math.PI]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Group311.geometry}
        material={materials.colormap2}
        position={[-12.019, 0, 6.706]}
        rotation={[-Math.PI, 1.309, -Math.PI]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Group32.geometry}
        material={materials.colormap2}
        position={[-3.005, 0, 91.903]}
        rotation={[0, Math.PI / 4, 0]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Group33.geometry}
        material={materials.colormap2}
        position={[5.149, 0, 69.422]}
        rotation={[0, Math.PI / 6, 0]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Group34.geometry}
        material={materials.colormap2}
        position={[5.649, 0, 55.922]}
        rotation={[0, Math.PI / 6, 0]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Group35.geometry}
        material={materials.colormap2}
        position={[15.995, 0, 50.403]}
        rotation={[0, Math.PI / 4, 0]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Group36.geometry}
        material={materials.colormap2}
        position={[17.495, 0, 51.403]}
        rotation={[0, Math.PI / 4, 0]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Group37.geometry}
        material={materials.colormap2}
        position={[17.649, 0, 49.422]}
        rotation={[0, Math.PI / 6, 0]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Group38.geometry}
        material={materials.colormap2}
        position={[9.149, 0, 27.422]}
        rotation={[0, Math.PI / 6, 0]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Group312.geometry}
        material={materials.colormap2}
        position={[10.149, 0, 28.922]}
        rotation={[0, Math.PI / 6, 0]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["flowers-tall21"].geometry}
        material={materials.colormap2}
        position={[-27.5, 0, 58]}
        rotation={[0, Math.PI / 6, 0]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["flowers-tall22"].geometry}
        material={materials.colormap2}
        position={[-28, 0, 76]}
        rotation={[0, -Math.PI / 3, 0]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["flowers-tall23"].geometry}
        material={materials.colormap2}
        position={[-39.5, 0, 67]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["flowers-tall24"].geometry}
        material={materials.colormap2}
        position={[-38.5, 0, 65.5]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["flowers-tall35"].geometry}
        material={materials.colormap2}
        position={[-38, 0, 67.5]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["flowers-tall36"].geometry}
        material={materials.colormap2}
        position={[-34.5, 0, 55.5]}
        rotation={[0, -1.309, 0]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["flowers-tall37"].geometry}
        material={materials.colormap2}
        position={[-41.5, 0, 39]}
        rotation={[0, Math.PI / 3, 0]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["flowers-tall38"].geometry}
        material={materials.colormap2}
        position={[-38.5, 0, 25.5]}
        rotation={[-Math.PI, -Math.PI / 3, -Math.PI]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["flowers-tall39"].geometry}
        material={materials.colormap2}
        position={[-28.5, 0, 35]}
        rotation={[-Math.PI, 0.262, -Math.PI]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["flowers-tall40"].geometry}
        material={materials.colormap2}
        position={[-27.5, 0, 38]}
        rotation={[-Math.PI, -Math.PI / 3, -Math.PI]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["flowers-tall"].geometry}
        material={materials.colormap2}
        position={[1, 0, 69]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["flowers-tall41"].geometry}
        material={materials.colormap2}
        position={[-32.5, 0, 15.5]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["flowers-tall43"].geometry}
        material={materials.colormap2}
        position={[-10.5, 0, 27.5]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["flowers-tall44"].geometry}
        material={materials.colormap2}
        position={[3.5, 0, 11.5]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["flowers-tall45"].geometry}
        material={materials.colormap2}
        position={[4, 0, 29]}
        rotation={[0, -Math.PI / 4, 0]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["flowers-tall46"].geometry}
        material={materials.colormap2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["flowers-tall8"].geometry}
        material={materials.colormap2}
        position={[28.5, 0, 38.5]}
        rotation={[0, -0.262, 0]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["flowers-tall14"].geometry}
        material={materials.colormap2}
        position={[28, 0, 27.5]}
        rotation={[0, Math.PI / 4, 0]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["flowers-tall15"].geometry}
        material={materials.colormap2}
        position={[39, 0, 26]}
        rotation={[0, Math.PI / 4, 0]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["flowers-tall16"].geometry}
        material={materials.colormap2}
        position={[39.5, 0, 27.5]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["flowers-tall17"].geometry}
        material={materials.colormap2}
        position={[35.5, 0, 12]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["flowers-tall4"].geometry}
        material={materials.colormap2}
        position={[1.5, 0, 67.5]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["flowers-tall9"].geometry}
        material={materials.colormap2}
        position={[37.5, 0, 50]}
        rotation={[0, -0.262, 0]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["flowers-tall10"].geometry}
        material={materials.colormap2}
        position={[38.5, 0, 50.5]}
        rotation={[0, -0.262, 0]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["flowers-tall11"].geometry}
        material={materials.colormap2}
        position={[30.5, 0, 60.5]}
        rotation={[0, Math.PI / 6, 0]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["flowers-tall12"].geometry}
        material={materials.colormap2}
        position={[40.5, 0, 75]}
        rotation={[0, -1.309, 0]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["flowers-tall13"].geometry}
        material={materials.colormap2}
        position={[32, 0, 83]}
        rotation={[0, -Math.PI / 6, 0]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["flowers-tall5"].geometry}
        material={materials.colormap2}
        position={[4, 0, 75]}
        rotation={[0, 0.262, 0]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["flowers-tall6"].geometry}
        material={materials.colormap2}
        position={[13, 0, 75]}
        rotation={[0, Math.PI / 6, 0]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["flowers-tall7"].geometry}
        material={materials.colormap2}
        position={[20, 0, 46]}
        rotation={[0, -Math.PI / 6, 0]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["flowers-tall18"].geometry}
        material={materials.colormap2}
        position={[12, 0, 50.5]}
        rotation={[0, Math.PI / 6, 0]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["flowers-tall19"].geometry}
        material={materials.colormap2}
        position={[-9.5, 0, 76.5]}
        rotation={[0, -Math.PI / 4, 0]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["flowers-tall20"].geometry}
        material={materials.colormap2}
        position={[-25, 0, 51.5]}
        rotation={[0, Math.PI / 3, 0]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Farm_Crop_Tree_0216.geometry}
        material={materials.Color_Palette_015}
        position={[-3.5, 0, 56]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Farm_Crop_Tree_0222.geometry}
        material={materials.Color_Palette_015}
        position={[26, 0, 83.5]}
        rotation={[-Math.PI, Math.PI / 3, -Math.PI]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Farm_Crop_Tree_0225.geometry}
        material={materials.Color_Palette_015}
        position={[39.5, 0, 86]}
        rotation={[-Math.PI, -Math.PI / 4, -Math.PI]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Farm_Crop_Tree_0218.geometry}
        material={materials.Color_Palette_015}
        position={[-32, 0, 66]}
        rotation={[0, -Math.PI / 3, 0]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Farm_Crop_Tree_0220.geometry}
        material={materials.Color_Palette_015}
        position={[-15, 0, 54.5]}
        rotation={[-Math.PI, -0.262, -Math.PI]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Farm_Crop_Tree_0219.geometry}
        material={materials.Color_Palette_015}
        position={[-40.5, 0, 81]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Farm_Crop_Tree_0223.geometry}
        material={materials.Color_Palette_015}
        position={[29.5, 0, 50]}
        rotation={[-Math.PI, -Math.PI / 3, -Math.PI]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Farm_Crop_Tree_0226.geometry}
        material={materials.Color_Palette_015}
        position={[32, 0, 70]}
        rotation={[-Math.PI, 0.262, -Math.PI]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Farm_Crop_Tree_0224.geometry}
        material={materials.Color_Palette_015}
        position={[40.5, 0, 61]}
        rotation={[-Math.PI, 0.262, -Math.PI]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Farm_Crop_Tree_0217.geometry}
        material={materials.Color_Palette_015}
        position={[-2, 0, 88]}
        rotation={[0, -Math.PI / 3, 0]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Farm_Crop_Tree_0221.geometry}
        material={materials.Color_Palette_015}
        position={[-30, 0, 87]}
        rotation={[0, 1.309, 0]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.plant11.geometry}
        material={materials.colormap2}
        position={[19.5, 0, 39]}
        rotation={[-Math.PI, 1.309, -Math.PI]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.plant12.geometry}
        material={materials.colormap2}
        position={[17, 0, 28]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.plant13.geometry}
        material={materials.colormap2}
        position={[0, 0, 27.5]}
        rotation={[-Math.PI, -Math.PI / 6, -Math.PI]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.plant14.geometry}
        material={materials.colormap2}
        position={[-3.5, 0, 17]}
        rotation={[-Math.PI, -Math.PI / 3, -Math.PI]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.plant15.geometry}
        material={materials.colormap2}
        position={[4.5, 0, 15.5]}
        rotation={[0, -Math.PI / 3, 0]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.plant16.geometry}
        material={materials.colormap2}
        position={[-7, 0, 2.5]}
        rotation={[0, -Math.PI / 6, 0]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.plant.geometry}
        material={materials.colormap2}
        position={[-26.5, 0, 80.5]}
        rotation={[0, Math.PI / 6, 0]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.plant17.geometry}
        material={materials.colormap2}
        position={[-27, 0, 67.5]}
        rotation={[0, -Math.PI / 3, 0]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.plant18.geometry}
        material={materials.colormap2}
        position={[-33.5, 0, 77.5]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.plant19.geometry}
        material={materials.colormap2}
        position={[-15, 0, 76.5]}
        rotation={[0, Math.PI / 4, 0]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.plant3.geometry}
        material={materials.colormap2}
        position={[-5, 0, 89.5]}
        rotation={[0, 0.262, 0]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.plant4.geometry}
        material={materials.colormap2}
        position={[22, 0, 77]}
        rotation={[0, -0.262, 0]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.plant5.geometry}
        material={materials.colormap2}
        position={[27, 0, 65]}
        rotation={[0, 0.262, 0]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.plant10.geometry}
        material={materials.colormap2}
        position={[23, 0, 50.5]}
        rotation={[0, Math.PI / 3, 0]}
        scale={2}
      />
      <group position={[9, -1.75, 38]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_122.geometry}
          material={materials.Color_Palette_015}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_122_1.geometry}
          material={materials.colormap5}
        />
      </group>
      <group position={[23, -1, 95]}>
        <mesh
          castShadow
          receiveShadow
          geometry={snapVerticesToGrid(nodes.Mesh_184.geometry)}
          material={materials.Brown}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={snapVerticesToGrid(nodes.Mesh_184_1.geometry)}
          material={materials.Material_0}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={snapVerticesToGrid(nodes.Mesh_184_2.geometry)}
          material={materials.Material_7_001}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={snapVerticesToGrid(nodes.Mesh_184_3.geometry)}
          material={materials.Green}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={snapVerticesToGrid(nodes.Mesh_184_4.geometry)}
          material={materials.Material_8_001}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/models/World/Plains-transformed.glb");
