/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./World/02Plains.glb --transform -o C:\Users\emanu\next-portfolio\public\02Plains.jsx --shadows 
Files: ./World/02Plains.glb [40.54MB] > C:\Users\emanu\next-portfolio\public\02Plains-transformed.glb [2.99MB] (93%)
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Plains(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('/models/world/Plains-transformed.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group>
        <group name="AnimalArmature" position={[22, 0, 87.5]} rotation={[0, -Math.PI / 4, 0]}>
          <primitive object={nodes.All} />
        </group>
        <primitive object={nodes.Root} />
        <group name="AnimalArmature2" position={[-13.5, 0, 27]} rotation={[0, Math.PI / 4, 0]}>
          <primitive object={nodes.All2} />
        </group>
        <primitive object={nodes.Root2} />
        <group name="AnimalArmature3" position={[-8, 0, 58]} rotation={[0, Math.PI / 4, 0]}>
          <primitive object={nodes.Body3} />
        </group>
        <primitive object={nodes.Root3} />
        <group name="AnimalArmature4" position={[-21, 0, 55]} rotation={[0, Math.PI / 3, 0]}>
          <primitive object={nodes.All3} />
        </group>
        <primitive object={nodes.Root4} />
        <group name="AnimalArmature5" position={[-9.5, 0, 54]} rotation={[0, -Math.PI / 3, 0]}>
          <primitive object={nodes.All4} />
        </group>
        <primitive object={nodes.Root5} />
        <group name="AnimalArmature6" position={[-3.5, 0, 71]} rotation={[0, -Math.PI / 3, 0]}>
          <primitive object={nodes.All5} />
        </group>
        <primitive object={nodes.Root6} />
        <group name="AnimalArmature7" position={[-1, 0, 66.5]} rotation={[0, -Math.PI / 6, 0]}>
          <primitive object={nodes.All6} />
        </group>
        <primitive object={nodes.Root7} />
        <group name="AnimalArmature8" position={[-29.5, 0, 50.5]} rotation={[0, Math.PI / 4, 0]}>
          <primitive object={nodes.All7} />
        </group>
        <primitive object={nodes.Root8} />
        <group name="AnimalArmature9" position={[-0.5, 0, 74]} rotation={[-Math.PI, -Math.PI / 4, -Math.PI]}>
          <primitive object={nodes.All8} />
        </group>
        <primitive object={nodes.Root9} />
        <group name="AnimalArmature10" position={[-4.5, 0, 36.5]} rotation={[0, Math.PI / 4, 0]}>
          <primitive object={nodes.All9} />
        </group>
        <group name="AnimalArmature11" position={[5.5, 0, 53]} rotation={[0, -Math.PI / 4, 0]}>
          <primitive object={nodes.Body11} />
        </group>
        <primitive object={nodes.Root10} />
        <group name="AnimalArmature12" position={[-2.5, 0, 20.5]} rotation={[0, -Math.PI / 4, 0]}>
          <primitive object={nodes.All10} />
        </group>
        <primitive object={nodes.Root11} />
        <mesh name="Farm_House_Barn_01" castShadow receiveShadow geometry={nodes.Farm_House_Barn_01.geometry} material={materials.Color_Palette_01} position={[-23, 0, 22]} rotation={[0, Math.PI / 6, 0]} />
        <mesh name="flowers-tall" castShadow receiveShadow geometry={nodes['flowers-tall'].geometry} material={materials.colormap} position={[1, 0, 69]} scale={2} />
        <mesh name="Farm_Crop_Sunflower_Step_01" castShadow receiveShadow geometry={nodes.Farm_Crop_Sunflower_Step_01.geometry} material={materials.Color_Palette_01} position={[7, 0.25, 36]} />
        <mesh name="road" castShadow receiveShadow geometry={nodes.road.geometry} material={materials.colormap4} position={[10, 0, 46.5]} scale={2} />
        <mesh name="grass-patch" castShadow receiveShadow geometry={nodes['grass-patch'].geometry} material={materials.colormap5} position={[-35.439, 0, 91.913]} />
        <mesh name="square_forest10" castShadow receiveShadow geometry={nodes.square_forest10.geometry} material={materials.Green_011} position={[-19, -1, 1]} />
        <mesh name="square_forestToPlain10" castShadow receiveShadow geometry={nodes.square_forestToPlain10.geometry} material={materials.Material_7_001} position={[-21, -1, 5]} rotation={[0, Math.PI / 2, 0]} />
        <mesh name="square_plain10" castShadow receiveShadow geometry={nodes.square_plain10.geometry} material={materials.Material_0} position={[-47, -1, 17]} />
        <mesh name="square_plainToRock_corner_A2" castShadow receiveShadow geometry={nodes.square_plainToRock_corner_A2.geometry} material={materials.Material_8_001} position={[21, -1, 95]} rotation={[-Math.PI, 0, -Math.PI]} />
        <mesh name="square_plainToRock_detail2" castShadow receiveShadow geometry={nodes.square_plainToRock_detail2.geometry} material={materials.BrownDark_001} position={[15, -1, 95]} rotation={[0, -Math.PI / 2, 0]} />
        <mesh name="square_rock2" castShadow receiveShadow geometry={nodes.square_rock2.geometry} material={materials.Brown} position={[23, -1, 95]} />
        <skinnedMesh name="Raccoon" geometry={nodes.Raccoon.geometry} material={materials.Atlas_002} skeleton={nodes.Raccoon.skeleton} position={[22, 0, 87.5]} rotation={[0, -Math.PI / 4, 0]} />
        <skinnedMesh name="Raccoon3" geometry={nodes.Raccoon3.geometry} material={materials.Atlas_002} skeleton={nodes.Raccoon3.skeleton} position={[-29.5, 0, 50.5]} rotation={[0, Math.PI / 4, 0]} />
        <skinnedMesh name="Dog" geometry={nodes.Dog.geometry} material={materials.Atlas_002} skeleton={nodes.Dog.skeleton} position={[-13.5, 0, 27]} rotation={[0, Math.PI / 4, 0]} />
        <skinnedMesh name="Chicken" geometry={nodes.Chicken.geometry} material={materials.Atlas_002} skeleton={nodes.Chicken.skeleton} position={[-8, 0, 58]} rotation={[0, Math.PI / 4, 0]} />
        <skinnedMesh name="Chicken4" geometry={nodes.Chicken4.geometry} material={materials.Atlas_002} skeleton={nodes.Chicken4.skeleton} position={[5.5, 0, 53]} rotation={[0, -Math.PI / 4, 0]} />
        <skinnedMesh name="Sheep" geometry={nodes.Sheep.geometry} material={materials.Atlas_002} skeleton={nodes.Sheep.skeleton} position={[-21, 0, 55]} rotation={[0, Math.PI / 3, 0]} />
        <skinnedMesh name="Sheep4" geometry={nodes.Sheep4.geometry} material={materials.Atlas_002} skeleton={nodes.Sheep4.skeleton} position={[-9.5, 0, 54]} rotation={[0, -Math.PI / 3, 0]} />
        <skinnedMesh name="Horse" geometry={nodes.Horse.geometry} material={materials.Atlas_002} skeleton={nodes.Horse.skeleton} position={[-3.5, 0, 71]} rotation={[0, -Math.PI / 3, 0]} />
        <skinnedMesh name="Wolf" geometry={nodes.Wolf.geometry} material={materials.Atlas_002} skeleton={nodes.Wolf.skeleton} position={[-1, 0, 66.5]} rotation={[0, -Math.PI / 6, 0]} />
        <skinnedMesh name="Wolf4" geometry={nodes.Wolf4.geometry} material={materials.Atlas_002} skeleton={nodes.Wolf4.skeleton} position={[-0.5, 0, 74]} rotation={[-Math.PI, -Math.PI / 4, -Math.PI]} />
        <skinnedMesh name="Pig" geometry={nodes.Pig.geometry} material={materials.Atlas_002} skeleton={nodes.Pig.skeleton} position={[-4.5, 0, 36.5]} rotation={[0, Math.PI / 4, 0]} />
        <skinnedMesh name="Cat" geometry={nodes.Cat.geometry} material={materials.Atlas_002} skeleton={nodes.Cat.skeleton} position={[-2.5, 0, 20.5]} rotation={[0, -Math.PI / 4, 0]} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/world/Plains-transformed.glb')
