/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./World/06Skylands.glb --transform -o C:\Users\emanu\next-portfolio\public\06Skylands.jsx --shadows 
Files: ./World/06Skylands.glb [1.65MB] > C:\Users\emanu\next-portfolio\public\06Skylands-transformed.glb [97.64KB] (94%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Skylands(props) {
  const { nodes, materials } = useGLTF('/models/world/Skylands-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.rocks.geometry} material={materials.colormap} position={[-9.5, -0.5, 30.5]} scale={[16, 8, 16]} />
      <mesh castShadow receiveShadow geometry={nodes.Cloud_02.geometry} material={materials.Color_Palette_01} position={[-5, 0.5, 38.5]} rotation={[0, 0.262, 0]} scale={3} />
      <mesh castShadow receiveShadow geometry={nodes.rocket_topA2.geometry} material={materials.PaletteMaterial001} position={[-9.5, 9.1, 30.5]} scale={2} />
      <mesh castShadow receiveShadow geometry={nodes['rocks-b'].geometry} material={materials.colormap2} position={[-28, 0, 32.5]} rotation={[0, Math.PI / 4, 0]} />
      <mesh castShadow receiveShadow geometry={nodes['ship-ocean-liner-small'].geometry} material={materials.colormap5} position={[-31.5, 0, 10.5]} rotation={[0, Math.PI / 4, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.square_sandToPlain10.geometry} material={materials.Material_9_001} position={[23, -1, 1]} />
    </group>
  )
}

useGLTF.preload('/models/world/Skylands-transformed.glb')
