/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\Skylands.glb --transform -o C:\Users\emanu\next-portfolio\public\Skylands.jsx --shadows -j 
Files: .\Skylands.glb [1.75MB] > C:\Users\emanu\next-portfolio\public\Skylands-transformed.glb [107.86KB] (94%)
*/

import React from "react";
import { useGLTF } from "@react-three/drei";
import { snapVerticesToGrid } from "@/lib/geometryUtility";

export function Skylands(props) {
  const { nodes, materials } = useGLTF(
    "/models/World/Skylands-transformed.glb",
  );
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.rocks.geometry}
        material={materials.colormap}
        position={[-9.5, -0.5, 30.5]}
        scale={[16, 8, 16]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cloud_025.geometry}
        material={materials.Color_Palette_01}
        position={[-10.5, 0.5, 21.5]}
        scale={3}
      />
      <group position={[-9.5, 2.7, 30.5]} scale={2}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_2.geometry}
          material={materials.PaletteMaterial001}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_2_1.geometry}
          material={materials.PaletteMaterial001}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_2_2.geometry}
          material={materials.PaletteMaterial001}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_2_3.geometry}
          material={materials.PaletteMaterial001}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cloud_01.geometry}
        material={materials.Color_Palette_012}
        position={[35.5, 0.5, 21.5]}
        scale={3}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cloud_012.geometry}
        material={materials.Color_Palette_012}
        position={[11.5, 0, 30]}
        scale={3}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cloud_014.geometry}
        material={materials.Color_Palette_012}
        position={[38.5, 0, 44]}
        scale={3}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cloud_017.geometry}
        material={materials.Color_Palette_012}
        position={[31, 0, 34]}
        scale={3}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cloud_018.geometry}
        material={materials.Color_Palette_012}
        position={[-32, 0, 44]}
        scale={3}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cloud_03.geometry}
        material={materials.Color_Palette_012}
        position={[11, 1.5, 26.5]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={3}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cloud_032.geometry}
        material={materials.Color_Palette_012}
        position={[15, 0, 42.5]}
        scale={3}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cloud_034.geometry}
        material={materials.Color_Palette_012}
        position={[-36.5, 0, 25]}
        scale={3}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cloud_02.geometry}
        material={materials.Color_Palette_012}
        position={[16.5, 0.5, 28.5]}
        scale={3}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cloud_022.geometry}
        material={materials.Color_Palette_012}
        position={[10, 0.5, 41]}
        scale={3}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cloud_023.geometry}
        material={materials.Color_Palette_012}
        position={[-8.5, 0.5, 47]}
        scale={3}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["rocks-b"].geometry}
        material={materials.colormap2}
        position={[-28, 0, 32.5]}
        rotation={[0, Math.PI / 4, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["rocks-b4"].geometry}
        material={materials.colormap2}
        position={[-14.5, 0, 9.5]}
        rotation={[0, -Math.PI / 6, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["rocks-b5"].geometry}
        material={materials.colormap2}
        position={[24.5, 0, 18.5]}
        rotation={[0, -Math.PI / 6, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["rocks-c"].geometry}
        material={materials.colormap2}
        position={[39, 0, 9]}
        rotation={[Math.PI, -1.309, Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["rocks-a"].geometry}
        material={materials.colormap2}
        position={[42, 0, 31.5]}
        rotation={[0, -Math.PI / 6, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["rocks-a4"].geometry}
        material={materials.colormap2}
        position={[26, 0, 49]}
        rotation={[0, Math.PI / 6, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.meteor_detailed2.geometry}
        material={materials.PaletteMaterial001}
        position={[8.5, 2.5, 20]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.meteor_detailed3.geometry}
        material={materials.PaletteMaterial001}
        position={[18.5, 2.5, 32.5]}
        scale={4}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["ship-ocean-liner-small"].geometry}
        material={materials.colormap5}
        position={[-31.5, 0, 10.5]}
        rotation={[0, Math.PI / 4, 0]}
      />
      <group position={[-47, -1, 1]} rotation={[0, Math.PI / 2, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={snapVerticesToGrid(nodes.mesh_11.geometry)}
          material={materials.PaletteMaterial001}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={snapVerticesToGrid(nodes.mesh_11_1.geometry)}
          material={materials.PaletteMaterial001}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={snapVerticesToGrid(nodes.mesh_11_2.geometry)}
          material={materials.Material_9_001}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={snapVerticesToGrid(nodes.mesh_11_3.geometry)}
          material={materials.PaletteMaterial001}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/models/World/Skylands-transformed.glb");
