/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./World/00Village.glb --transform -o C:\Users\emanu\next-portfolio\public\00Village.jsx --shadows 
Files: ./World/00Village.glb [6.47MB] > C:\Users\emanu\next-portfolio\public\00Village-transformed.glb [413.05KB] (94%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Village(props) {
  const { nodes, materials } = useGLTF('/models/world/Village-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.square_forest10.geometry} material={materials.Green_006} position={[-31, -1, 17]} />
      <group position={[-47, -1, 15]} rotation={[0, -Math.PI / 2, 0]}>
        <mesh castShadow receiveShadow geometry={nodes.mesh_1.geometry} material={materials.Water_006} />
        <mesh castShadow receiveShadow geometry={nodes.mesh_1_1.geometry} material={materials.BrownDark_006} />
      </group>
      <mesh castShadow receiveShadow geometry={nodes.fence_stone_straight.geometry} material={materials.hexagons_medieval} position={[-4, -0.1, 26]} rotation={[0, Math.PI / 2, 0]} scale={4} />
      <mesh castShadow receiveShadow geometry={nodes.Tree_2_E_Color1.geometry} material={materials.forest} position={[-26, 0, 19]} />
      <mesh castShadow receiveShadow geometry={nodes['patch-grass-foliage'].geometry} material={materials.colormap} position={[-30, 0, 19]} />
      <mesh castShadow receiveShadow geometry={nodes['rock-a'].geometry} material={materials.colormap2} position={[-22, 0, 24]} scale={5} />
    </group>
  )
}

useGLTF.preload('/models/world/Village-transformed.glb')
