/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\Village.glb --transform -o C:\Users\emanu\next-portfolio\public\Village.jsx --shadows -j 
Files: .\Village.glb [5.62MB] > C:\Users\emanu\next-portfolio\public\Village-transformed.glb [268.91KB] (95%)
*/

import React from "react";
import { useGLTF } from "@react-three/drei";
import { snapVerticesToGrid } from "@/lib/geometryUtility";

export function Village(props) {
  const { nodes, materials } = useGLTF("/models/World/Village-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.building_archeryrange_blue.geometry}
        material={materials.hexagons_medieval}
        position={[-13, -0.1, 15]}
        scale={4}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.fence_stone_straight.geometry}
        material={materials.hexagons_medieval}
        position={[-4, -0.1, 26]}
        rotation={[0, Math.PI / 2, 0]}
        scale={4}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mountain_A.geometry}
        material={materials.hexagons_medieval}
        position={[18, 2, 11]}
        scale={4}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mountain_A5.geometry}
        material={materials.hexagons_medieval}
        position={[-23.206, 2, 1.912]}
        rotation={[0, Math.PI / 3, 0]}
        scale={4}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree_2_E_Color1.geometry}
        material={materials.forest}
        position={[-26, 0, 19]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree_2_E_Color14.geometry}
        material={materials.forest}
        position={[-4, 0, 3]}
        rotation={[0, Math.PI / 6, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree_2_E_Color16.geometry}
        material={materials.forest}
        position={[30, 0, 28]}
        rotation={[0, -Math.PI / 3, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree_2_E_Color17.geometry}
        material={materials.forest}
        position={[22, 0, -6]}
        rotation={[-Math.PI, -Math.PI / 4, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree_2_E_Color18.geometry}
        material={materials.forest}
        position={[6, 0, -6]}
        rotation={[0, Math.PI / 3, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree_2_D_Color1.geometry}
        material={materials.forest}
        position={[-31, 0, 30]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree_2_B_Color1.geometry}
        material={materials.forest}
        position={[-34, 0, 19]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree_2_A_Color1.geometry}
        material={materials.forest}
        position={[-43, 0, 28]}
        rotation={[0, -Math.PI / 6, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree_2_A_Color14.geometry}
        material={materials.forest}
        position={[-41, 0, 6]}
        rotation={[0, Math.PI / 4, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree_2_A_Color15.geometry}
        material={materials.forest}
        position={[-43, 0, -9]}
        rotation={[0, -0.262, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree_2_A_Color16.geometry}
        material={materials.forest}
        position={[-6, 0, -8]}
        rotation={[0, Math.PI / 4, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree_2_A_Color17.geometry}
        material={materials.forest}
        position={[24, 0, 29]}
        rotation={[0, -Math.PI / 6, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree_2_A_Color18.geometry}
        material={materials.forest}
        position={[42, 0, 17]}
        rotation={[0, -Math.PI / 6, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree_2_A_Color19.geometry}
        material={materials.forest}
        position={[38, 0, -7]}
        rotation={[0, -Math.PI / 6, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree_2_C_Color1.geometry}
        material={materials.forest}
        position={[31, 0, -2]}
        rotation={[0, 0.262, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree_2_C_Color14.geometry}
        material={materials.forest}
        position={[-43, 0, -1]}
        rotation={[0, -Math.PI / 6, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["patch-grass-foliage"].geometry}
        material={materials.colormap}
        position={[-30, 0, 19]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["patch-grass-foliage4"].geometry}
        material={materials.colormap}
        position={[-9, 0, 4]}
        rotation={[0, Math.PI / 6, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["patch-grass-foliage5"].geometry}
        material={materials.colormap}
        position={[0, 0, -5]}
        rotation={[0, -Math.PI / 4, 0]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["patch-grass-foliage6"].geometry}
        material={materials.colormap}
        position={[40, 0, 25]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["patch-grass-foliage7"].geometry}
        material={materials.colormap}
        position={[41, 0, 0]}
        rotation={[0, -Math.PI / 6, 0]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Grass_2_D_Color1.geometry}
        material={materials.forest}
        position={[-29, 0, 30]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Grass_2_D_Color14.geometry}
        material={materials.forest}
        position={[-21, 0, 19]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Grass_2_D_Color15.geometry}
        material={materials.forest}
        position={[-22, 0, 11]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Grass_2_D_Color16.geometry}
        material={materials.forest}
        position={[-37, 0, 18]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Grass_2_D_Color17.geometry}
        material={materials.forest}
        position={[-41, 0, 30]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Grass_2_D_Color18.geometry}
        material={materials.forest}
        position={[-43, 0, 10]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Grass_2_D_Color19.geometry}
        material={materials.forest}
        position={[-39, 0, -6]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Grass_2_D_Color110.geometry}
        material={materials.forest}
        position={[-14, 0, 5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Grass_2_D_Color111.geometry}
        material={materials.forest}
        position={[-4, 0, -11]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Grass_2_D_Color112.geometry}
        material={materials.forest}
        position={[-2, 0, 4]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Grass_2_D_Color113.geometry}
        material={materials.forest}
        position={[10, 0, -7]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Grass_2_D_Color114.geometry}
        material={materials.forest}
        position={[17, 0, -11]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Grass_2_D_Color115.geometry}
        material={materials.forest}
        position={[26, 0, -4]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Grass_2_D_Color116.geometry}
        material={materials.forest}
        position={[26, 0, -12]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Grass_2_D_Color117.geometry}
        material={materials.forest}
        position={[28, 0, -6]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Grass_2_D_Color118.geometry}
        material={materials.forest}
        position={[35, 0, -5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Grass_2_D_Color119.geometry}
        material={materials.forest}
        position={[36, 0, -12]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Grass_2_D_Color120.geometry}
        material={materials.forest}
        position={[45, 0, 6]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Grass_2_D_Color121.geometry}
        material={materials.forest}
        position={[38, 0, 13]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Grass_2_D_Color122.geometry}
        material={materials.forest}
        position={[45, 0, 20]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Grass_2_D_Color123.geometry}
        material={materials.forest}
        position={[35, 0, 21]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Grass_2_D_Color124.geometry}
        material={materials.forest}
        position={[45, 0, 30]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Grass_2_D_Color125.geometry}
        material={materials.forest}
        position={[28, 0, 30]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Grass_2_D_Color126.geometry}
        material={materials.forest}
        position={[26, 0, 25]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Grass_2_D_Color127.geometry}
        material={materials.forest}
        position={[22, 0, 24]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Grass_2_C_Color1.geometry}
        material={materials.forest}
        position={[-25, 0, 22]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Grass_2_C_Color14.geometry}
        material={materials.forest}
        position={[-34, 0, 30]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Grass_2_C_Color15.geometry}
        material={materials.forest}
        position={[-35, 0, 21.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Grass_2_C_Color16.geometry}
        material={materials.forest}
        position={[-46, 0, 29.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Grass_2_C_Color17.geometry}
        material={materials.forest}
        position={[-45, 0, 24.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Grass_2_C_Color18.geometry}
        material={materials.forest}
        position={[-46, 0, 10.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Grass_2_C_Color19.geometry}
        material={materials.forest}
        position={[-45, 0, -0.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Grass_2_C_Color110.geometry}
        material={materials.forest}
        position={[-32, 0, -13]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Grass_2_C_Color111.geometry}
        material={materials.forest}
        position={[-16, 0, 7.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Grass_2_C_Color112.geometry}
        material={materials.forest}
        position={[-8, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Grass_2_C_Color113.geometry}
        material={materials.forest}
        position={[5.5, 0, -3]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Grass_2_C_Color114.geometry}
        material={materials.forest}
        position={[29, 0, -1.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Grass_2_C_Color115.geometry}
        material={materials.forest}
        position={[40, 0, -6]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Grass_2_C_Color116.geometry}
        material={materials.forest}
        position={[45.5, 0, -4]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Grass_2_C_Color117.geometry}
        material={materials.forest}
        position={[45.5, 0, 14]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Grass_2_C_Color118.geometry}
        material={materials.forest}
        position={[38, 0, 6]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Grass_1_D_Color1.geometry}
        material={materials.forest}
        position={[-9.5, 0, 29.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["rock-a"].geometry}
        material={materials.colormap2}
        position={[-22, 0, 24]}
        scale={5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["rock-a4"].geometry}
        material={materials.colormap2}
        position={[-37, 0, 29]}
        rotation={[0, -Math.PI / 4, 0]}
        scale={5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["rock-a5"].geometry}
        material={materials.colormap2}
        position={[-39, 0, 10]}
        scale={5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["rock-a6"].geometry}
        material={materials.colormap2}
        position={[-7, 0, -4]}
        scale={5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["rock-a7"].geometry}
        material={materials.colormap2}
        position={[1, 0, 5]}
        rotation={[0, -1.309, 0]}
        scale={5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["rock-a8"].geometry}
        material={materials.colormap2}
        position={[14, 0, -10]}
        rotation={[0, -Math.PI / 6, 0]}
        scale={5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["rock-a9"].geometry}
        material={materials.colormap2}
        position={[43, 0, -10]}
        rotation={[0, -1.309, 0]}
        scale={5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["rock-a10"].geometry}
        material={materials.colormap2}
        position={[38, 0, 18]}
        rotation={[-Math.PI, -Math.PI / 6, -Math.PI]}
        scale={5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["rock-a11"].geometry}
        material={materials.colormap2}
        position={[33, 0, 31]}
        rotation={[-Math.PI, -Math.PI / 4, -Math.PI]}
        scale={5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["rock-b"].geometry}
        material={materials.colormap2}
        position={[-45, 0, 20]}
        scale={5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["rock-b4"].geometry}
        material={materials.colormap2}
        position={[-45, 0, 5]}
        rotation={[0, -Math.PI / 4, 0]}
        scale={5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["rock-b5"].geometry}
        material={materials.colormap2}
        position={[-38, 0, -10]}
        scale={5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["rock-b6"].geometry}
        material={materials.colormap2}
        position={[0, 0, -13]}
        rotation={[0, -Math.PI / 6, 0]}
        scale={5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["rock-b7"].geometry}
        material={materials.colormap2}
        position={[30, 0, -10]}
        scale={5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["rock-b8"].geometry}
        material={materials.colormap2}
        position={[41, 0, 9]}
        rotation={[0, -Math.PI / 4, 0]}
        scale={5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.waterlily_B.geometry}
        material={materials.hexagons_medieval5}
        position={[-37.5, 0, 24]}
        scale={5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.waterlily_B4.geometry}
        material={materials.hexagons_medieval5}
        position={[-40, 0, 16.5]}
        rotation={[0, -1.309, 0]}
        scale={5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.waterlily_A.geometry}
        material={materials.hexagons_medieval5}
        position={[-28, 0, 26]}
        scale={5}
      />
      <group position={[-17, -1, 11]}>
        <mesh
          castShadow
          receiveShadow
          geometry={snapVerticesToGrid(nodes.mesh_17.geometry)}
          material={materials.BrownDark}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={snapVerticesToGrid(nodes.mesh_17_1.geometry)}
          material={materials.Green}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={snapVerticesToGrid(nodes.mesh_17_2.geometry)}
          material={materials.Water}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/models/World/Village-transformed.glb");
