/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\Blockchain.glb --transform -o C:\Users\emanu\next-portfolio\public\Blockchain.jsx --shadows 
Files: .\Blockchain.glb [29.9KB] > C:\Users\emanu\next-portfolio\public\Blockchain-transformed.glb [3.78KB] (87%)
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function Blockchain(props) {
  const { nodes, materials } = useGLTF(
    "/models/aboutCards/Blockchain-transformed.glb"
  );
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.MeshInstance3D10.geometry}
        material={materials.Nodes}
        position={[2.407, 0.75, 1.861]}
        rotation={[0, Math.PI / 4, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.MeshInstance3D11.geometry}
        material={materials.Connections}
        position={[0, 0.75, -3]}
        rotation={[0, Math.PI / 4, 0]}
      />
    </group>
  );
}

useGLTF.preload("/models/aboutCards/Blockchain-transformed.glb");
