/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\Design.glb --transform -o C:\Users\emanu\next-portfolio\public\Design.jsx --shadows 
Files: .\Design.glb [1.01MB] > C:\Users\emanu\next-portfolio\public\Design-transformed.glb [121.78KB] (88%)
*/

import React, { useMemo } from "react";
import { GizmoViewport, Grid, useGLTF } from "@react-three/drei";
import { Tree } from "./minecraft/Tree";
import { Model } from "./minecraft/model";
import { Bee } from "./minecraft/Bee";
import { Sheep } from "./minecraft/Sheep";
import { Allay } from "./minecraft/Allay";
import { enableShadows } from "@/lib/enableShadows";

export function Design(props) {
  const { scene } = useGLTF("/models/aboutCards/Design-transformed.glb");

  const optimizedScene = useMemo(() => {
    return enableShadows(scene.clone());
  }, [scene]);
  return (
    <group {...props} dispose={null}>
      <primitive object={optimizedScene} />

      <group scale={[0.9, 0.9, 0.9]}>
        <GizmoViewport
          position={[9, 7, 4]}
          scale={[1, 1, 1]}
          axisColors={["#f33352", "#87d602", "#298cf5"]}
          labelColor="black"
          disabled={true}
        />
        <Grid
          fadeDistance={4000}
          position={[0, 0.01, 0]}
          args={[21, 11]}
          cellColor="#888888"
          sectionColor="#444444"
          cellSize={1}
          fadeFrom={0}
          sectionSize={8}
          cellThickness={1}
        />
        <axesHelper args={[2]} position={[-10, 0.01, 5]} />
        <Tree />
        <Model />
        <Bee />
        <Sheep />
        <Allay />
      </group>
    </group>
  );
}

useGLTF.preload("/models/aboutCards/Design-transformed.glb");
