/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\Games.glb --transform -o C:\Users\emanu\next-portfolio\public\Games.jsx --shadows 
Files: .\Games.glb [98.06MB] > C:\Users\emanu\next-portfolio\public\Games-transformed.glb [3.37MB] (97%)
*/

import React from "react";
import { useGraph } from "@react-three/fiber";
import { useGLTF } from "@react-three/drei";
import { SkeletonUtils } from "three-stdlib";

export function Games(props) {
  const { scene } = useGLTF("/models/aboutCards/Games-transformed.glb");
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);
  const { nodes, materials } = useGraph(clone);
  return (
    <group {...props} dispose={null}>
      <primitive object={nodes.GLTF_created_0_rootJoint} />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.BLT_LuckyCards_006.geometry}
        material={materials.standardSurface1_002}
        position={[-8.1, 0.12, -2.2]}
        rotation={[0.054, 0.261, -0.014]}
        scale={0.4}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.BLT_Seal_001.geometry}
        material={materials.standardSurface2}
        position={[-8.485, 0.225, -2.808]}
        rotation={[1.621, -0.014, -0.261]}
        scale={0.4}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.BLT_JokerSet09_014.geometry}
        material={materials.standardSurface1}
        position={[-6.05, 0.01, -2.6]}
        rotation={[0, -0.262, 0]}
        scale={0.4}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.BLT_ChipsStakes_004.geometry}
        material={materials.standardSurface1_001}
        position={[-7.3, 0.1, -4.3]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.3}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.BLT_TarotSet_019.geometry}
        material={materials.standardSurface12}
        position={[-3.65, 0.01, -2.4]}
        rotation={[0, Math.PI / 6, 0]}
        scale={0.3}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube_002_Esquie_0.geometry}
        material={materials.Esquie}
        position={[-6.9, 0.04, 2.25]}
        rotation={[Math.PI, -Math.PI / 6, 0]}
        scale={1.5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.alicia_mask.geometry}
        material={materials.PaletteMaterial001}
        position={[-3.505, 0.542, 3.496]}
        rotation={[0.083, -0.775, 0.067]}
        scale={0.015}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_2.geometry}
        material={materials.bluepower}
        position={[-4.071, 3.7, -4.531]}
        rotation={[Math.PI, 1.309, Math.PI / 3]}
        scale={0.015}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_3.geometry}
        material={materials.GhostCube}
        position={[-4.071, 3.7, -4.531]}
        rotation={[Math.PI, 1.309, Math.PI / 3]}
        scale={0.015}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_8.geometry}
        material={materials.OutbreakPerfectedBarrel}
        position={[6.89, 2.25, -1.154]}
        rotation={[2.591, -0.301, -1.751]}
        scale={6}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_9.geometry}
        material={materials.OutbreakPerfectedTubes}
        position={[6.89, 2.25, -1.154]}
        rotation={[2.591, -0.301, -1.751]}
        scale={6}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_13.geometry}
        material={materials.PaletteMaterial002}
        position={[6.89, 2.25, -1.154]}
        rotation={[2.591, -0.301, -1.751]}
        scale={6}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_19.geometry}
        material={materials.OutbreakPerfectedStock}
        position={[6.89, 2.25, -1.154]}
        rotation={[2.591, -0.301, -1.751]}
        scale={6}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.ArmsBB_Texture1_0.geometry}
        material={materials.Texture1}
        position={[1.275, 1.813, -1.981]}
        rotation={[-1.45, 0.421, -0.288]}
        scale={1.5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Eye1BB_EyesBakgtound_0.geometry}
        material={materials.EyesBakgtound}
        position={[0.213, 3.181, -1.841]}
        rotation={[-1.508, -0.599, 0.375]}
        scale={1.5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.HatBB_hat_0.geometry}
        material={materials.material}
        position={[-0.919, 4.2, -2.569]}
        rotation={[-Math.PI / 2, 0, -0.262]}
        scale={1.5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Lip1BB_lips_0.geometry}
        material={materials.lips}
        position={[-1.177, 2.57, -1.865]}
        rotation={[-1.643, -0.264, -0.271]}
        scale={1.5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane_Helices_0.geometry}
        material={materials.PaletteMaterial003}
        position={[-0.682, 4.548, -2.505]}
        rotation={[-Math.PI / 2, 0, -0.262]}
        scale={1.5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Pupil1BB_eyes_0.geometry}
        material={materials.eyes}
        position={[0.333, 3.277, -1.504]}
        rotation={[-1.508, -0.599, 0.375]}
        scale={1.5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_7.geometry}
        material={materials.glass}
        position={[5.888, 3.6, -3.907]}
        rotation={[-0.096, -0.435, -0.041]}
        scale={7.5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_72.geometry}
        material={materials.materialsmodelspropsmetal_box_001}
        position={[5.386, 1.493, -2.948]}
        rotation={[0, Math.PI / 9, 0]}
        scale={0.075}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_22.geometry}
        material={materials.Material_0012}
        position={[3.737, 0.7, -1.922]}
        rotation={[2.247, 1.122, -0.253]}
        scale={0.125}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_10.geometry}
        material={materials.Material_009}
        position={[3.737, 0.7, -1.922]}
        rotation={[2.247, 1.122, -0.253]}
        scale={0.125}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube_Body_0.geometry}
        material={materials.Body}
        position={[1.72, 6.1, -3.5]}
        rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube_Material_001_0.geometry}
        material={materials.Eyes}
        position={[1.72, 6.1, -3.5]}
        rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube_Material_002_0.geometry}
        material={materials.PaletteMaterial004}
        position={[1.72, 6.1, -3.5]}
        rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube_Material_023_0.geometry}
        material={materials.Wings}
        position={[1.72, 6.1, -3.5]}
        rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_5_001.geometry}
        material={materials.blinn1SG}
        position={[-2, 0.69, 1.6]}
        rotation={[-Math.PI / 2, 0, -2.877]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_7_001.geometry}
        material={materials.blinn3SG}
        position={[1.1, 0.676, 1.2]}
        rotation={[-Math.PI / 2, 0, 2.621]}
        scale={0.01}
      />
      <skinnedMesh
        geometry={nodes.Object_92.geometry}
        material={materials.portal_gun}
        skeleton={nodes.Object_92.skeleton}
        position={[5.51, 3.405, -3.098]}
        rotation={[-0.096, -0.435, -0.041]}
        scale={7.5}
      />
    </group>
  );
}

useGLTF.preload("/models/aboutCards/Games-transformed.glb");
