/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\Minecraft.glb --transform -o C:\Users\emanu\next-portfolio\public\Minecraft.jsx --shadows -f png 
Files: .\Minecraft.glb [4.63MB] > C:\Users\emanu\next-portfolio\public\Minecraft-transformed.glb [435.1KB] (91%)
*/

import React from "react";
import { useGraph } from "@react-three/fiber";
import { useGLTF } from "@react-three/drei";
import { SkeletonUtils } from "three-stdlib";

export function Minecraft(props) {
  const { scene } = useGLTF("/models/aboutCards/Minecraft-transformed.glb");
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);
  const { nodes, materials } = useGraph(clone);
  return (
    <group {...props} dispose={null}>
      <primitive object={nodes.Waist_2} />
      <primitive object={nodes.Right_Leg_2} />
      <primitive object={nodes.Left_Leg_2} />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_100.geometry}
        material={materials.pKaDkdyuuvylYHt}
        position={[-1.639, 0.92, 0.561]}
        rotation={[Math.PI / 2, 0, -2.094]}
        scale={0.08}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_105.geometry}
        material={materials.ZtrFkpzRROyZncn}
        position={[-1.639, 0.92, 0.561]}
        rotation={[Math.PI / 2, 0, -2.094]}
        scale={0.08}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_107.geometry}
        material={materials.PaletteMaterial001}
        position={[-1.639, 0.92, 0.561]}
        rotation={[Math.PI / 2, 0, -2.094]}
        scale={0.08}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Wood_Log_A.geometry}
        material={materials.resource}
        position={[0.516, 0.75, -0.875]}
        rotation={[0, Math.PI / 6, 0]}
        scale={3}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.bookA.geometry}
        material={materials.PaletteMaterial002}
        position={[-6.25, 0.25, 1.25]}
        rotation={[-1.841, 0.253, 2.425]}
        scale={2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Grass_2_D_Color1.geometry}
        material={materials.forest}
        position={[3.25, 0, 1.75]}
      />
      <skinnedMesh
        geometry={nodes.Waist2.geometry}
        material={materials.material_0}
        skeleton={nodes.Waist2.skeleton}
        position={[-0.34, 0.5, -0.189]}
        rotation={[-Math.PI, Math.PI / 3, -Math.PI]}
        scale={3}
      />
      <skinnedMesh
        geometry={nodes.Right_Leg2.geometry}
        material={materials.material_0}
        skeleton={nodes.Right_Leg2.skeleton}
        position={[-0.518, 0.5, -0.498]}
        rotation={[1.582, 0.051, -1.781]}
        scale={3}
      />
      <skinnedMesh
        geometry={nodes.Left_Leg2.geometry}
        material={materials.material_0}
        skeleton={nodes.Left_Leg2.skeleton}
        position={[-0.162, 0.5, 0.119]}
        rotation={[1.61, 0.035, -2.409]}
        scale={3}
      />
    </group>
  );
}

useGLTF.preload("/models/aboutCards/Minecraft-transformed.glb");
