/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Minecraft.glb --transform -o C:\Users\emanu\next-portfolio\public\Minecraft.jsx --shadows 
Files: Minecraft.glb [13.46MB] > C:\Users\emanu\next-portfolio\public\Minecraft-transformed.glb [643.34KB] (95%)
*/

import React from "react";
import { useGraph } from "@react-three/fiber";
import { useGLTF } from "@react-three/drei";
import { SkeletonUtils } from "three-stdlib";

export function Minecraft(props) {
  const { scene } = useGLTF("/models/aboutCards/Minecraft-transformed.glb");
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);
  const { nodes, materials } = useGraph(clone);
  return (
    <group {...props} dispose={null}>
      <primitive object={nodes.Waist_2} />
      <primitive object={nodes.Right_Leg_2} />
      <primitive object={nodes.Left_Leg_2} />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.chair_stool_wood.geometry}
        material={materials.furniture_texture}
        position={[0.236, 0, 0]}
        rotation={[-Math.PI, Math.PI / 4, -Math.PI]}
        scale={4}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_12.geometry}
        material={materials.zNRfbdNyoCOxSDD}
        position={[-0.471, 2.6, 0.707]}
        rotation={[Math.PI / 2, 0, -2.356]}
        scale={0.08}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_20.geometry}
        material={materials.PaletteMaterial001}
        position={[-0.471, 2.6, 0.707]}
        rotation={[Math.PI / 2, 0, -2.356]}
        scale={0.08}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_35.geometry}
        material={materials.GzMrvkTsmRxvOJz}
        position={[-0.471, 2.6, 0.707]}
        rotation={[Math.PI / 2, 0, -2.356]}
        scale={0.08}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_53.geometry}
        material={materials.ItKEDAaOJloGKSH}
        position={[-0.471, 2.6, 0.707]}
        rotation={[Math.PI / 2, 0, -2.356]}
        scale={0.08}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_55.geometry}
        material={materials.xEcnbqMzoZoLkIZ}
        position={[-0.471, 2.6, 0.707]}
        rotation={[Math.PI / 2, 0, -2.356]}
        scale={0.08}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_62.geometry}
        material={materials.YMmdfGRsPviDXYd}
        position={[-0.471, 2.6, 0.707]}
        rotation={[Math.PI / 2, 0, -2.356]}
        scale={0.08}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_69.geometry}
        material={materials.sqkqSXQCeccDMmm}
        position={[-0.471, 2.6, 0.707]}
        rotation={[Math.PI / 2, 0, -2.356]}
        scale={0.08}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_77.geometry}
        material={materials.WiyOPYJEeiHNVjF}
        position={[-0.471, 2.6, 0.707]}
        rotation={[Math.PI / 2, 0, -2.356]}
        scale={0.08}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_83.geometry}
        material={materials.PaletteMaterial002}
        position={[-0.471, 2.6, 0.707]}
        rotation={[Math.PI / 2, 0, -2.356]}
        scale={0.08}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_91.geometry}
        material={materials.DthpMXUDOFLFvyk}
        position={[-0.471, 2.6, 0.707]}
        rotation={[Math.PI / 2, 0, -2.356]}
        scale={0.08}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_107.geometry}
        material={materials.HlQwFCAPWzetDQy}
        position={[-0.471, 2.6, 0.707]}
        rotation={[Math.PI / 2, 0, -2.356]}
        scale={0.08}
      />
      <skinnedMesh
        geometry={nodes.Waist2.geometry}
        material={materials.material_0}
        skeleton={nodes.Waist2.skeleton}
        position={[0.589, 2.25, -0.354]}
        rotation={[-Math.PI, Math.PI / 4, -Math.PI]}
        scale={3}
      />
      <skinnedMesh
        geometry={nodes.Right_Leg2.geometry}
        material={materials.material_0}
        skeleton={nodes.Right_Leg2.skeleton}
        position={[0.337, 2.25, -0.605]}
        rotation={[1.595, 0.047, -2.043]}
        scale={3}
      />
      <skinnedMesh
        geometry={nodes.Left_Leg2.geometry}
        material={materials.material_0}
        skeleton={nodes.Left_Leg2.skeleton}
        position={[0.841, 2.25, -0.102]}
        rotation={[1.617, 0.024, -2.671]}
        scale={3}
      />
    </group>
  );
}

useGLTF.preload("/models/aboutCards/Minecraft-transformed.glb");
