/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\Window.glb --transform -o C:\Users\emanu\next-portfolio\public\Window.jsx --shadows 
Files: .\Window.glb [161.95KB] > C:\Users\emanu\next-portfolio\public\Window-transformed.glb [7.48KB] (95%)
*/

import React, { Children } from "react";
import { Html, Text, useGLTF } from "@react-three/drei";
import { usePointerHover } from "@/lib/usePointerHover";

const colorBase = "##F1F3F4";

export function Window(props) {
  const { nodes, materials } = useGLTF(
    "/models/aboutCards/Window-transformed.glb"
  );

  console.log(props);

  const { handlePointerOver, handlePointerOut } = usePointerHover();
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Group_17svg.geometry}
        material={materials.PaletteMaterial001}
      />
      <Text
        color={colorBase}
        fontSize={0.3}
        position={[-3.85, 3.2, 0.01]}
        anchorX={"left"}
      >
        {props.file}
      </Text>
      <group onPointerOver={handlePointerOver} onPointerOut={handlePointerOut}>
        <mesh position={[5.02, 3.2, 0.001]} rotation={[0, 0, 0]}>
          <planeGeometry args={[1.6, 0.7]} />
          <meshBasicMaterial transparent opacity={0} color={"hotpink"} />
        </mesh>
        <Text
          color={colorBase}
          fontSize={0.3}
          position={[4.45, 3.2, 0.01]}
          anchorX={"left"}
        >
          {"Reset"}
        </Text>
      </group>
      <Html position={[0, -0.4, 0.001]} distanceFactor={10} transform occlude>
        {props.children}
      </Html>
    </group>
  );
}

useGLTF.preload("/models/aboutCards/Window-transformed.glb");
