/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\Document.glb --transform -o C:\Users\emanu\next-portfolio\public\Document.jsx --shadows 
Files: .\Document.glb [57.24KB] > C:\Users\emanu\next-portfolio\public\Document-transformed.glb [3.88KB] (93%)
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function DocumentLogo(props) {
  const { nodes, materials } = useGLTF(
    "/models/footerCards/Document-transformed.glb"
  );
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["document-text-svgrepo-comsvg"].geometry}
        material={materials.Material}
      />
    </group>
  );
}

useGLTF.preload("/models/footerCards/Document-transformed.glb");
