/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\Github.glb --transform -o C:\Users\emanu\next-portfolio\public\Github.jsx --shadows 
Files: .\Github.glb [57.22KB] > C:\Users\emanu\next-portfolio\public\Github-transformed.glb [4.02KB] (93%)
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function GithubLogo(props) {
  const { nodes, materials } = useGLTF(
    "/models/footerCards/Github-transformed.glb"
  );
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["github-marksvg"].geometry}
        material={materials.Material}
      />
    </group>
  );
}

useGLTF.preload("/models/footerCards/Github-transformed.glb");
