/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\Linkedin.glb --transform -o C:\Users\emanu\next-portfolio\public\Linkedin.jsx --shadows 
Files: .\Linkedin.glb [71.92KB] > C:\Users\emanu\next-portfolio\public\Linkedin-transformed.glb [4.47KB] (94%)
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function LinkedinLogo(props) {
  const { nodes, materials } = useGLTF(
    "/models/footerCards/Linkedin-transformed.glb"
  );
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["linkedin-svgrepo-comsvg"].geometry}
        material={materials.Material}
      />
    </group>
  );
}

useGLTF.preload("/models/footerCards/Linkedin-transformed.glb");
