/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\PaperPlane.glb --transform -o C:\Users\emanu\next-portfolio\public\PaperPlane.jsx --shadows 
Files: .\PaperPlane.glb [20.22KB] > C:\Users\emanu\next-portfolio\public\PaperPlane-transformed.glb [2.3KB] (89%)
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function PaperPlaneLogo(props) {
  const { nodes, materials } = useGLTF(
    "/models/footerCards/PaperPlane-transformed.glb"
  );
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["paper-plane-svgrepo-comsvg"].geometry}
        material={materials.Material}
      />
    </group>
  );
}

useGLTF.preload("/models/footerCards/PaperPlane-transformed.glb");
