/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./claw-machine.glb --transform -o C:\Users\emanu\next-portfolio\public\claw-machine.jsx --shadows 
Files: ./claw-machine.glb [88.2KB] > C:\Users\emanu\next-portfolio\public\claw-machine-transformed.glb [10.42KB] (88%)
*/

import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function ClawMachine(props) {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF('/claw-machine-transformed.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group>
        <mesh name="claw-machine" castShadow receiveShadow geometry={nodes['claw-machine'].geometry} material={materials.colormap}>
          <mesh name="rotate-y" castShadow receiveShadow geometry={nodes['rotate-y'].geometry} material={materials.colormap} position={[0, 0.65, 0]} />
        </mesh>
        <mesh name="(_ignore)" castShadow receiveShadow geometry={nodes['(_ignore)'].geometry} material={materials.glass} position={[0, 0.25, 0]} />
      </group>
    </group>
  )
}

useGLTF.preload('/claw-machine-transformed.glb')
