/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\Flag.glb --transform -o C:\Users\emanu\nextjs-portfolio\public\Flag.jsx --shadows -M -j 
Files: .\Flag.glb [29.69KB] > C:\Users\emanu\nextjs-portfolio\public\Flag-transformed.glb [8.35KB] (72%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Flag(props) {
  const { nodes, materials } = useGLTF('/Flag-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.flag001.geometry} material={materials.Body} />
      <mesh castShadow receiveShadow geometry={nodes.flag001_1.geometry} material={materials.Top} />
      <mesh castShadow receiveShadow geometry={nodes.flag001_2.geometry} material={materials.Body} />
    </group>
  )
}

useGLTF.preload('/Flag-transformed.glb')
