/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\Flag.glb -o C:\Users\emanu\nextjs-portfolio\public\Flag.jsx --shadows --keepmeshes --keepmaterials 
*/

import React, { useMemo } from 'react'
import { useGLTF } from '@react-three/drei'
import { useSpring, animated } from '@react-spring/three'

export function Flag(props) {
  const { nodes, materials } = useGLTF('/models/Flag.glb')

  const poleSpring = useSpring({
    color: props.reached ? "#FFA500" : "#FFFFFF",
    config: { duration: 1500 }
  })
  
  const flagSpring = useSpring({
    color: props.reached ? "#E10600" : "#FFFFFF",
    config: { duration: 1500 }
  })

  const AnimatedMaterialTop = useMemo(() => animated.meshStandardMaterial, [])
  const AnimatedMaterialFlag = useMemo(() => animated.meshStandardMaterial, [])

  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.flag001.geometry} material={materials.Body} />
      <mesh castShadow receiveShadow geometry={nodes.flag001_1.geometry}>
        <AnimatedMaterialTop {...materials.Top} color={poleSpring.color} />

      </mesh>
      <mesh castShadow receiveShadow geometry={nodes.flag001_2.geometry}>
        <AnimatedMaterialFlag 
          {...materials.Flag} 
          color={flagSpring.color}

        />
      </mesh>
    </group>
  )
}

useGLTF.preload('/models/Flag.glb')