/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./hotel.glb --transform -o C:\Users\emanu\next-portfolio\public\hotel.jsx --shadows 
Files: ./hotel.glb [446.28KB] > C:\Users\emanu\next-portfolio\public\hotel-transformed.glb [20.02KB] (96%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Hotel(props) {
  const { nodes, materials } = useGLTF('/hotel-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes['building-j'].geometry} material={materials.colormap} />
    </group>
  )
}

useGLTF.preload('/hotel-transformed.glb')
