/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./ship-pirate-medium.glb --transform -o C:\Users\emanu\next-portfolio\public\ship-pirate-medium.jsx --shadows 
Files: ./ship-pirate-medium.glb [186.77KB] > C:\Users\emanu\next-portfolio\public\ship-pirate-medium-transformed.glb [12.57KB] (93%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function PirateShip(props) {
  const { nodes, materials } = useGLTF('/ship-pirate-medium-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes['ship-pirate-medium'].geometry} material={materials.colormap} />
    </group>
  )
}

useGLTF.preload('/ship-pirate-medium-transformed.glb')
