/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\sedan-sports.glb --transform --shadows --keepgroups 
Files: .\sedan-sports.glb [177.69KB] > C:\Users\emanu\next-portfolio\sedan-sports-transformed.glb [13.1KB] (93%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function SedanSports(props) {
  const { nodes, materials } = useGLTF('/sedan-sports-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group>
        <mesh castShadow receiveShadow geometry={nodes.body.geometry} material={materials.colormap} position={[0, 0.15, -0.025]} />
      </group>
    </group>
  )
}

useGLTF.preload('/sedan-sports-transformed.glb')
