/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./slot-machine.glb --transform -o C:\Users\emanu\next-portfolio\public\slot-machine.jsx --shadows 
Files: ./slot-machine.glb [70.28KB] > C:\Users\emanu\next-portfolio\public\slot-machine-transformed.glb [7.94KB] (89%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function SlotMachine(props) {
  const { nodes, materials } = useGLTF('/slot-machine-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes['gambling-machine'].geometry} material={materials.colormap} />
    </group>
  )
}

useGLTF.preload('/slot-machine-transformed.glb')
