/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 spaceship.glb --transform --shadows --keepgroups --output C:/Users/emanu/next-portfolio/public/World.jsx 
Files: spaceship.glb [34.03KB] > C:\Users\emanu\next-portfolio\public\spaceship-transformed.glb [5.18KB] (85%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Spaceship(props) {
  const { nodes, materials } = useGLTF('/spaceship-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group>
        <group rotation={[-Math.PI, 0, -Math.PI]}>
          <mesh castShadow receiveShadow geometry={nodes.mesh_0.geometry} material={materials.metal} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_0_1.geometry} material={materials.metalDark} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_0_2.geometry} material={materials.dark} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_0_3.geometry} material={materials.metalRed} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/spaceship-transformed.glb')
