/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./statue.glb --transform -o C:\Users\emanu\next-portfolio\public\statue.jsx --shadows 
Files: ./statue.glb [67.75KB] > C:\Users\emanu\next-portfolio\public\statue-transformed.glb [6.72KB] (90%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Statue(props) {
  const { nodes, materials } = useGLTF('/statue-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.statue.geometry} material={materials.colormap} />
    </group>
  )
}

useGLTF.preload('/statue-transformed.glb')
