/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\public\models\world.glb --transform --shadows 
Files: .\public\models\world.glb [2.12MB] > C:\Users\emanu\next-portfolio\world-transformed.glb [54.78KB] (97%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function WorldModel(props) {
  const { nodes, materials } = useGLTF('/models/world-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.square_forest.geometry} material={materials.PaletteMaterial001} position={[-31, -1, 1]} />
      <mesh castShadow receiveShadow geometry={nodes['roof-flat-border-straight'].geometry} material={materials.colormap} position={[-3, 0, 20]} />
      <mesh castShadow receiveShadow geometry={nodes['floor-old'].geometry} material={materials.colormap4} position={[-13, 0, 21]} rotation={[0, -Math.PI / 2, 0]} scale={4} />
      <mesh castShadow receiveShadow geometry={nodes.bridge_side_stoneRound.geometry} material={materials.PaletteMaterial002} position={[-10, -0.1, 21]} rotation={[0, Math.PI / 2, 0]} scale={2} />
      <mesh castShadow receiveShadow geometry={nodes.body.geometry} material={materials.colormap5} position={[-10, 0.4, 19.975]} />
    </group>
  )
}

useGLTF.preload('/world-transformed.glb')
