/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\world.glb --transform --shadows 
Files: .\world.glb [5.58MB] > C:\Users\emanu\nextjs-portfolio\world-transformed.glb [1.29MB] (77%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/world-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.square_forest_detail2.geometry} material={materials.PaletteMaterial001} position={[-31, -1, 65]} rotation={[0, Math.PI / 2, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.square_forestToPlain2.geometry} material={materials.Material_7_001} position={[-47, -1, 85]} rotation={[0, Math.PI / 2, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.square_plainToRock2.geometry} material={materials.Material_8_001} position={[-47, -1, 161]} rotation={[0, Math.PI / 2, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.square_rockToSand2.geometry} material={materials.Material_9_001} position={[-47, -1, 233]} rotation={[0, Math.PI / 2, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.fence_stone_straight.geometry} material={materials.hexagons_medieval} position={[-4, -0.1, 26]} rotation={[0, Math.PI / 2, 0]} scale={4} />
      <mesh castShadow receiveShadow geometry={nodes.platform.geometry} material={materials.colormap} position={[-16, 0.5, 76]} scale={6} />
      <mesh castShadow receiveShadow geometry={nodes['floor-old'].geometry} material={materials.colormap2} position={[-3, 0, 206]} rotation={[0, -Math.PI / 2, 0]} scale={4} />
      <mesh castShadow receiveShadow geometry={nodes.body.geometry} material={materials.colormap3} position={[-3, 0.15, 203.475]} />
      <mesh castShadow receiveShadow geometry={nodes.Props_Broken_Rope_Bridge_01.geometry} material={materials.Color_Palette_01} position={[13, -3, 209.5]} scale={1.5} />
    </group>
  )
}

useGLTF.preload('/world-transformed.glb')
